### ISSUE TITLE
Upgrade org.junit.jupiter to version 5.4.0 and org.junit.platform to 1.4.0

### ISSUE THREAD

**Issue by ptirador** [strongbox/strongbox#1016]
We need to upgrade to the latest version of JUnit. This implies changing the version from groups `org.junit.jupiter` to version `5.4.0` and `org.junit.platform` to `1.4.0`.

Among the new features, we have:

- New `junit-jupiter` dependency-aggregating artifact for simplified dependency management in build tools. This would change a Maven build from this:

```
<project>
	...
	<properties>
		<junit.jupiter.version>5.3.1</junit.jupiter.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	...
</project>
```

to this:

```
<project>
	...
        <properties>
		<junit.jupiter.version>5.4.0</junit.jupiter.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	...
</project>
```

## Release notes
See [release notes](https://junit.org/junit5/docs/5.4.0/release-notes/) from this new version.

## Tasks

- [ ] Change the `pom.xml` file from [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) to upgrade to the versions indicated above.

- [ ] Change the `pom.xml` files from [`strongbox`](github.com/strongbox/strongbox) which have `org.junit.jupiter` groups to adapt to the new artifact `junit-jupiter`.

- [ ] Make sure that the project still builds.

- [ ] Make sure that both the unit and the integration tests are still passing. This can be checked by executing:
```
mvn clean install -Dintegration.tests
```

**Comment by juliodias** [comment]
Hi @ptirador, can I do this?

**Comment by carlspring** [comment]
@juliodias ,

Please, feel free to pick up this issue and to also join out [chat](https://chat.carlspring.org/)! :)

**Comment by LeifBrooks** [comment]
I can take this, if it is not currently being worked on

**Comment by carlspring** [comment]
Go for it!
