### ISSUE TITLE
Drop the need for the unboundid-maven-plugin and replace any tests that need with an alternative solution

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1080]
# Task Description
* [ ] Drop the `unboundid-maven-plugin` from the `strongbox-security/strongbox-security-api/pom.xml` and any references to it in Maven profiles.
* [ ] Check what tests (if there are still any) need this plugin.
* [ ] Remove the `unboundid-maven-plugin` from the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/).
* [ ] Remove the `unboundid-maven-plugin` from the [`strongbox-docs`](https://github.com/strongbox/strongbox-docs/blob/master/docs/developer-guide/building-the-code.md).

**Note:** This task is similar to #1079 and relates to #1130.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
Won't drop.
