### ISSUE TITLE
Test our build with JDK 9 and fix any issues with it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1109]
# Task Description

We need to test our builds against JDK 9. If any issues are discovered, we need to list them and address them.

```
WARNING: HK2 service reification failed for [org.glassfish.jersey.jaxb.internal.XmlRootElementJaxbProvider$General] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/xml/bind/PropertyException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2314)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1310)
	at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1306)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1306)
	at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1249)
	at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
	at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:144)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:178)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:128)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:179)
	at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:723)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:678)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:458)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2205)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:122)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1350)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1345)
	at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1407)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1332)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1321)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
	at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:187)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:248)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772)
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
	at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at org.carlspring.strongbox.client.RestArtifactResolver.get(RestArtifactResolver.java:92)
	at org.carlspring.strongbox.client.RestArtifactResolver.get(RestArtifactResolver.java:68)
	at org.carlspring.strongbox.client.ArtifactResolverIntegrationTest$MultiHttpClientConnThread.run(ArtifactResolverIntegrationTest.java:89)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.PropertyException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 63 more
MultiException stack 2 of 2
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
	implementation=org.glassfish.jersey.jaxb.internal.XmlRootElementJaxbProvider$General
	contracts={javax.ws.rs.ext.MessageBodyReader,javax.ws.rs.ext.MessageBodyWriter}
	scope=javax.inject.Singleton
	qualifiers={}
	descriptorType=CLASS
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@3ed832ec
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=61
	locatorId=1
	identityHashCode=298184292
	reified=false)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:689)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:458)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2205)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:122)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1350)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1345)
	at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1407)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1332)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1321)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:354)
	at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:187)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:248)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2022)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:765)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:772)
	at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:97)
	at org.glassfish.jersey.client.RequestProcessingInitializationStage.apply(RequestProcessingInitializationStage.java:67)
	at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:308)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at org.carlspring.strongbox.client.RestArtifactResolver.get(RestArtifactResolver.java:92)
	at org.carlspring.strongbox.client.RestArtifactResolver.get(RestArtifactResolver.java:68)
	at org.carlspring.strongbox.client.ArtifactResolverIntegrationTest$MultiHttpClientConnThread.run(ArtifactResolverIntegrationTest.java:89)


[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Strongbox: Masterbuild 1.0-SNAPSHOT:
[INFO] 
[INFO] Strongbox: Resources [Common] ...................... SUCCESS [  4.013 s]
[INFO] Strongbox: Resources [Storage API] ................. SUCCESS [  0.388 s]
[INFO] Strongbox: Resources ............................... SUCCESS [  0.067 s]
[INFO] Strongbox: Commons ................................. SUCCESS [  6.391 s]
[INFO] Strongbox: Configuration ........................... SUCCESS [  1.868 s]
[INFO] Strongbox: Data Service ............................ SUCCESS [  2.890 s]
[INFO] Strongbox: Client .................................. FAILURE [ 39.597 s]
[INFO] Strongbox: Metadata [Maven API] .................... SKIPPED
[INFO] Strongbox: Testing [Core] .......................... SKIPPED
[INFO] Strongbox: Security API ............................ SKIPPED
[INFO] Strongbox: Storage [Core] .......................... SKIPPED
[INFO] Strongbox: Event API ............................... SKIPPED
[INFO] Strongbox: Authentication API ...................... SKIPPED
[INFO] Strongbox: User Management ......................... SKIPPED
[INFO] Strongbox: Authentication Provider [Default] ....... SKIPPED
[INFO] Strongbox: Authentication Support .................. SKIPPED
[INFO] Strongbox: Authentication Provider [LDAP] .......... SKIPPED
[INFO] Strongbox: Authentication Providers ................ SKIPPED
[INFO] Strongbox: Authentication Registry ................. SKIPPED
[INFO] Strongbox: Security ................................ SKIPPED
[INFO] Strongbox: Testing [Storage] ....................... SKIPPED
[INFO] Strongbox: Storage [API] ........................... SKIPPED
[INFO] Strongbox: Cron [API] .............................. SKIPPED
[INFO] Strongbox: Cron [Tasks] ............................ SKIPPED
[INFO] Strongbox: Storage [Maven Layout Provider] ......... SKIPPED
[INFO] Strongbox: Storage [Nuget Layout Provider] ......... SKIPPED
[INFO] Strongbox: Masterbuild ............................. SKIPPED
[INFO] Strongbox: Web Forms ............................... SKIPPED
[INFO] Strongbox: REST Client ............................. SKIPPED
[INFO] Strongbox: Testing [Web] ........................... SKIPPED
[INFO] Strongbox: Testing ................................. SKIPPED
[INFO] Strongbox: Cron .................................... SKIPPED
[INFO] Strongbox: Storage [P2 Layout Provider] ............ SKIPPED
[INFO] Strongbox: Storage [NPM Layout Provider] ........... SKIPPED
[INFO] Strongbox: Storage [Raw Layout Provider] ........... SKIPPED
[INFO] Strongbox: Storage Maven Layout .................... SKIPPED
[INFO] Strongbox: Storage Layout Providers ................ SKIPPED
[INFO] Strongbox: Storage ................................. SKIPPED
[INFO] Strongbox: AQL ..................................... SKIPPED
[INFO] Strongbox: Web Core ................................ SKIPPED
[INFO] Strongbox: Distribution ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:01 min
[INFO] Finished at: 2019-03-16T21:51:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project strongbox-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/spas/Desktop/strongbox/strongbox-client/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/spas/Desktop/strongbox/strongbox-client && /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java -Xmx1024m -Xms512m '-Dstrongbox.download.indexes.storage-common-proxies.*=false' '-Dstrongbox.download.indexes.storage-springsource-proxies.*=false' -Dstrongbox.download.indexes=false '-Dstrongbox.download.indexes.storage-sbt-proxies.*=false' -Dstrongbox.npm.remote.changes.enabled=false org.apache.maven.surefire.booter.ForkedBooter /Users/spas/Desktop/strongbox/strongbox-client/target/surefire 2019-03-16T21-50-44_768-jvmRun1 surefire845990772165133978tmp surefire_08458110855541266741tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.carlspring.strongbox.client.ArtifactResolverIntegrationTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/spas/Desktop/strongbox/strongbox-client && /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java -Xmx1024m -Xms512m '-Dstrongbox.download.indexes.storage-common-proxies.*=false' '-Dstrongbox.download.indexes.storage-springsource-proxies.*=false' -Dstrongbox.download.indexes=false '-Dstrongbox.download.indexes.storage-sbt-proxies.*=false' -Dstrongbox.npm.remote.changes.enabled=false org.apache.maven.surefire.booter.ForkedBooter /Users/spas/Desktop/strongbox/strongbox-client/target/surefire 2019-03-16T21-50-44_768-jvmRun1 surefire845990772165133978tmp surefire_08458110855541266741tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.carlspring.strongbox.client.ArtifactResolverIntegrationTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:991)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:837)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

# Tasks

* [ ] Attempt building with JDK 9.
* [ ] Report any build issues.
* [ ] Investigate and fix all build issues.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by spasbelev** [comment]
With JDK 9 had to 
`        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
`
to the strongbox-client to make the build to compile and tests pass

**Comment by carlspring** [comment]
@spasbelev ,

Thanks for looking into this!

The dependency needs to be defined in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/) under the `<dependencyManagement/>` section. You should then use it under the `strongbox-client`'s `pom.xml` file (and wherever else necessary) without a version.

**Comment by abuukasyah** [comment]
is still open to try ?

**Comment by carlspring** [comment]
Yes, feel free to look into it!

**Comment by BartoszDabek** [comment]
Everything works fine with OracleJDK 9.
For OpenJDK 9 there was one dependency that was required to update: strongbox/strongbox-parent#32.

The versioning of Java in open jdk 9 has changed and aspectj dependency resolves it it as version 1.4. version. More details [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=515612).

One more problem I occured was related with security issues.
`java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

I had to copy _cacerts_ from oracle jdk into openjdk in order to resolve this problem. More details [here](https://askubuntu.com/questions/971059/17-10-openjdk-and-oracle-jdk-8-and-9-the-trustanchors-parameter-must-be-non-empt)

**Comment by adbjo** [comment]
Hello! We are a group of CS students interested in solving this issue. Should be done by friday.

**Comment by dscntr17** [comment]
Hello,

Is this open for me to take a look at this?

**Comment by carlspring** [comment]
You can try building and running it, bit it should work. We should put this on hold, as we don't have the infrastructure to run the tests under a different SDK right now.

**Comment by steve-todorov** [comment]
@dscntr17 if you are interested, you could checkout #1111 since it is more likely for us to support only the LTS versions which as of now are JDK8 and JDK11. We could get Github Actions to run the main build (excluding s-w-i-t) :)

**Comment by carlspring** [comment]
Closing this as we now have support for JDK 8 and 11 (the JDK 11 support will be added via #1676).
