### ISSUE TITLE
Test our build with JDK 10 and fix any issues with it 

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1110]
# Task Description

We need to test our builds against JDK 10. If any issues are discovered, we need to list them and address them.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by spasbelev** [comment]
JDK 10 needs same fix as JDK9 to the strongbox-client pom.xml file
<dependency> 
<groupId>javax.xml.bind</groupId> <artifactId>jaxb-api</artifactId> <version>2.3.0</version> </dependency>
Without the added dependency will have following failure: https://gist.github.com/spasbelev/94b3670614110a58dd48117216fd00be

**Comment by BartoszDabek** [comment]
JDK 10 compiles and runs well with changes applied in #strongbox/strongbox-parent#32.

Tested with OracleJDK 10.0.2 and OpenJDK 10.0.2.

- [x]  Building the code and running mvn spring-boot:run in the strongbox-web-core still starts up the application correctly.
- [x] Building the code and running the strongbox-distribution from a zip or tar.gz still works.
- [x] The tests in the strongbox-web-integration-tests still run properly.
