### ISSUE TITLE
Test our build with JDK 11 and fix any issues with it 

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1111]
# Task Description

We need to test our builds against JDK 11. If any issues are discovered, we need to list them and address them.

Please, note that the languages level (both `source` and `target`) should be preserved at `1.8`. The Jenkins infrastructure building and testing the code is still at 1.8, (running a JDK 8), so this code should still be compilable and runnable under a 1.8 JDK.

# Tasks

* [x] Fix the `java.lang.InstantiationException` and `java.lang.NoSuchMethodException` reported in CronJobDuplicationCheckStrategiesRegistry with JDK11 ( #1779 )
* [x] Fix the `java.lang.NoClassDefFoundError: sun/reflect/Reflection` in the `strongbox-ldap-authentication-provider` ( #1780 )
* [x] Fix the failing tests 
  * [x] Fix the test failures in the `NpmArtifactControllerTestIT` under JDK11 ( #1781 )
  * [x] Fix the test failures in the `ParallelDownloadRemoteArtifactTest` under JDK11 ( #1782 )
* [x] Strongbox instance startup fails on JDK11 ( #1785 )

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov

**Comment by spasbelev** [comment]
Running with JDK 11  had to add         
```
<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
 </dependency>
```
to the strongbox-configuration component

Then had 2 failing tests with following output :https://gist.github.com/spasbelev/d092e6c4ca5f392267b39678ec95b55f

**Comment by cheemcheem** [comment]
Running with JDK 11 on macOS I had to add the same dependency as above to both strongbox-configuration and strongbox-client before I could reach the same 2 failing tests.

So now the following is in both `strongbox-client/pom.xml` and `strongbox-configuration/pom.xml`:
```xml
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>
```
and the following failures occurred:
 
[Maven Output](https://gist.github.com/cheemcheem/bced12b4c9d59ce676ae7bd1eb4dc549)
[Surefire Output](https://gist.github.com/cheemcheem/e46172a1c0550818d0d8a8769df93931)
[Maven Version](https://gist.github.com/cheemcheem/4af975c4250d0254222b4ea09c28e315)

**Comment by PrzemyslawCieslik** [comment]
somebody doing this or can I take it?

**Comment by carlspring** [comment]
@PrzemyslawCieslik ,

Feel free to try out the explanations above and confirm them.

**Comment by Sanketh-Maturi** [comment]
Hey, can I take this up?

**Comment by mehtakaran9** [comment]
Can I try this out? @carlspring

**Comment by carlspring** [comment]
@mehtakaran9 ,

Are you familiar with JDK 11?

**Comment by Rama000777** [comment]
@carlspring is somebody working on this? can i work on this?

**Comment by carlspring** [comment]
Hi @Rama000777 ,

Thanks for offerring to help! Perhaps you could have a look at #1782 and investigate the reason for that failing test under JDK11?

**Comment by steve-todorov** [comment]
@carlspring / @sbespalov do we have more JDK11 issues which need to be fixed or is this task ready to be closed? :)

**Comment by carlspring** [comment]
Thanks to everyone involved! :)

@steve-todorov: We don't have JDK11 related tasks, per se, (or, at least -- not that I'm aware of), but we do have that one follow-up task for the migration away from the Tanuki wrapper.
