### ISSUE TITLE
Add a dependency exclusion for guava in org.carlspring.maven:maven-commons

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1116]
# Task Description

It seems that `org.carlspring.maven:maven-commons` depends on a vulnerable version Guava. Snyk.io is reporting the following:

*Deserialization of Untrusted Data*

Vulnerable module: `com.google.guava:guava`
Introduced through: `org.carlspring.maven:maven-commons@1.4`
Detailed paths and remediation
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven.shared:maven-common-artifact-filters@3.0.1` › `org.apache.maven:maven-core@3.3.9` › `org.apache.maven:maven-aether-provider@3.3.9` › `org.apache.maven:maven-model-builder@3.3.9` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven.shared:maven-common-artifact-filters@3.0.1` › `org.apache.maven:maven-core@3.3.9` › `org.apache.maven:maven-model-builder@3.3.9` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven:maven-core@3.3.9` › `org.apache.maven:maven-aether-provider@3.3.9` › `org.apache.maven:maven-model-builder@3.3.9` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven.shared:maven-common-artifact-filters@3.0.1` › `org.apache.maven:maven-core@3.3.9` › `com.google.inject:guice@4.0` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven:maven-core@3.3.9` › `com.google.inject:guice@4.0` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Introduced through: `org.carlspring.strongbox:strongbox-cron-tasks@1.0-SNAPSHOT` › `org.carlspring.maven:maven-commons@1.4` › `org.apache.maven:maven-core@3.3.9` › `org.apache.maven:maven-model-builder@3.3.9` › `com.google.guava:guava@18.0`
Remediation: No remediation path available.
Vulnerable functions
`com.google.common.util.concurrent.AtomicDoubleArray.readObject()`
Overview
`com.google.guava:guava` is a set of core libraries that includes new collection types (such as multimap and multiset,immutable collections, a graph library, functional types, an in-memory cache and more.

Affected versions of this package are vulnerable to Deserialization of Untrusted Data.

During deserialization, two Guava classes accept a caller-specified size parameter and eagerly allocate an array of that size:

* `AtomicDoubleArray` (when serialized with Java serialization)
* `CompoundOrdering` (when serialized with GWT serialization)

An attacker may be able to send a specially crafted request which with then cause the server to allocate all it's memory, without validation whether the data size is reasonable.

# Tasks

* [ ] Add a dependency exclusion for Guava in the `strongbox-parent` for the `maven-commons.
* [ ] Check that the snyk.io pull request validation passes.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] Running the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by arjanvanderborg** [comment]
Hello Carl, found out about the Strongbox project and would like to help. Okay if I pick up this one?

**Comment by arjanvanderborg** [comment]
@carlspring Okay if I pick up this one?

**Comment by carlspring** [comment]
Yes, feel free to pick it up! :)

**Comment by ptirador** [comment]
@carlspring: Does this still apply?

**Comment by carlspring** [comment]
@ptirador :

I'm not 100% sure, but there's definitely quite a few things you can help us fix in the `maven-common` dependencies, if you're up for it.

**Comment by carlspring** [comment]
Closing as obsolete.
