### ISSUE TITLE
Re-work our REST API doc generation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1123]
# Task Description

This is the master task for the re-working of our REST API-s doc generation.

# Tasks

* [ ] Restore the generation of our Swagger documentation (#1124)
* [ ] Set up our documentation to work with Spring Boot + Springfox + Swagger (#1125)
* [ ] Stylize our REST API's docs (#1126)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by devshashankb** [comment]
Can i work on this?

**Comment by carlspring** [comment]
Yes, you pick #1126.
