### ISSUE TITLE
Restore the generation of our Swagger documentation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1124]
# Task Description

At the moment, our Swagger documentation is no longer being generated. This used to be done in the [`strongbox-webapp`](https://github.com/strongbox/strongbox/), check [here](https://github.com/strongbox/strongbox-webapp/blob/master/pom.xml#L204). However, with our recent migration to Spring Boot, we dropped the need for the [`strongbox-webapp`](https://github.com/strongbox/strongbox/) and the [`strongbox-assembly`](https://github.com/strongbox/strongbox-assembly/), as our whole application is, in essence, in the `strongbox-web-core` (which is where `strongbox-web-core-${project.version}-spring-boot.jar` is being produced; this is then packaged into the `strongbox-distribution`).

This task is a sub-task of #1123 .

# Tasks

We need to:
* [x] Restore the Maven [Swagger generation profile](https://github.com/strongbox/strongbox-webapp/blob/master/pom.xml#L204) and add it to the `strongbox-web-core`'s `pom.xml`.
* [x] Restore the Swagger templates from [here](https://github.com/strongbox/strongbox-webapp/tree/master/src/main/swagger/templates) to `strongbox-web-core/src/main/swagger/templates`.
* [ ] Figure out where to package the produced Swagger documentation to, so that Spring Boot would be able to display it properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by cbrianhill** [comment]
PR #1175 uses the `springfox-swagger` module to render OpenAPI at runtime rather than at build time.  There is an additional dependency on a webjar, `springfox-swagger-ui`, which provides Swagger UI so that the application can render a web page as well.

Because we use our own resource handler mappings, making `swagger-ui` render from strongbox required some changes to these mappings, one to add the `/swagger-ui.html` page, and one to enable content from webjars to be returned by the spring-boot app.

The PR does not add any styling, only the default swagger-ui styling was implemented.

**Comment by cbrianhill** [comment]
I've updated PR https://github.com/strongbox/strongbox/pull/1175 to render the docs at our customary URI, `/docs/rest/api.html`.  To do this, I've included an altered version of `/swagger-ui.html` and `springfox.js` from https://github.com/springfox/springfox/tree/master/springfox-swagger-ui, which use updated path information to find the resources they need.

I investigated whether we could use configuration to adjust these URLs, and came across https://github.com/springfox/springfox/issues/2250.  This issue indicates that springfox-swagger-ui's authors intend users to use their implementation only as an example, and customize as needed.

Since we will be styling this in accordance with strongbox's UI, this seems like a fair approach.
