### ISSUE TITLE
Stabilize our dependencies

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1130]
# Task Description

We have the following list of snapshot dependencies:
* Our own projects:
  * [ ] Return the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/) to be a sub-module of the [`strongbox`](https://github.com/strongbox/strongbox/) project.
  * [ ] Make the the [`strongbox-db`](https://github.com/strongbox/strongbox-db/) not extend the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/).
  * [ ] [`maven-commons:1.4-SNAPSHOT`](https://github.com/carlspring/maven-commons/) : Used for our Maven layout provider.
    * [x] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [x] Released: `1.4`.
    * [ ] Update the `strongbox-parent`.
  * [ ] [`commons-http:1.0-SNAPSHOT`](https://github.com/carlspring/commons-http/)
    * [ ] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [ ] Released: `1.0`.
    * [ ] Update the `strongbox-parent`.
  * [ ] [`commons-io:1.0-SNAPSHOT`](https://github.com/carlspring/commons-io/)
    * [x] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [ ] Released: `1.0`.
    * [ ] Update the `strongbox-parent`.
  * [ ] [`logback-configuration:1.0-SNAPSHOT`](https://github.com/carlspring/logback-configuration/)
    * [ ] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [ ] Released: `1.0`.
    * [ ] Update the `strongbox-parent`.
* Our own Maven plugins:
  * [ ] [`little-proxy-maven-plugin:1.0-SNAPSHOT`](https://github.com/carlspring/little-proxy-maven-plugin/)
    * [ ] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [x] Released: `1.0`.
    * [ ] Update the `strongbox-parent`.
  * [x] [`unboundid-maven-plugin:1.1-SNAPSHOT`](https://github.com/carlspring/unboundid-maven-plugin/)
    * [x] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [x] Released: `1.1`.
    * [ ] Update the `strongbox-parent`.
* Third-party forked projects:
  * [ ] [`maven-indexer`](https://github.com/carlspring/maven-indexer/)
    * We need the following pull requests to be merged:
      * [ ] apache/maven-indexer#25
      * [ ] apache/maven-indexer#26
  * [ ] [JNuGet](https://bitbucket.org/strongbox/jnuget/src/default/)
    * [ ] Drop the dependencies to jnuget-core and jnuget-server dependencies (#1131)
  * [ ] [semantic-versioning](https://github.com/strongbox/semantic-versioning/)
    * [x] Fix `Jenkinsfile`.
    * [x] Fix Github webhooks.
    * [ ] Released: `0.9.34`.
    * [ ] Update the `strongbox-parent`.
