### ISSUE TITLE
Drop the dependencies to jnuget-core and jnuget-server

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1131]
# Task Description

This task is a follow-up to #611 (#1106) and is required for #1130.

Dropping these dependencies currently causes compilation error, as it's looking for a few more classes from JNuGet.

# Tasks

The goal of this issue it to move the rest of **JNuget** classes under the respective sub-packages of `org.carlspring.strongbox`:
* [ ] `ru.aristar.jnuget.files.Framework`
* [ ] `ru.aristar.jnuget.files.Hash`
* [ ] `ru.aristar.jnuget.files.NugetFormatException`
* [ ] `ru.aristar.jnuget.files.Nupkg`
* [ ] `ru.aristar.jnuget.files.nuspec.NuspecFile`
* [ ] `ru.aristar.jnuget.files.nuspec.NuspecFile.Metadata` 
* [ ] `ru.aristar.jnuget.rss.PackageEntry` 
* [ ] `ru.aristar.jnuget.rss.PackageFeed` (will be handled in #1213)
* [ ] Also `ru.aristar.jnuget.Version` usage should be replaced with `org.semver.Version` the same way it was implemented in [#611](https://github.com/strongbox/strongbox/issues/611).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sbespalov** [comment]
within this issue the rest of *JNuget* classes should be moved under `org.carlspring.strongbox` package:
```
ru.aristar.jnuget.files.Framework; 
ru.aristar.jnuget.files.Hash; 
ru.aristar.jnuget.files.NugetFormatException; 
ru.aristar.jnuget.files.Nupkg; 
ru.aristar.jnuget.files.nuspec.NuspecFile; 
ru.aristar.jnuget.files.nuspec.NuspecFile.Metadata; 
ru.aristar.jnuget.rss.PackageEntry; 
ru.aristar.jnuget.rss.PackageFeed; 
```

Also `ru.aristar.jnuget.Version` usage should be replaced with `org.semver.Version` same way as it was implemented within [#611](https://github.com/strongbox/strongbox/issues/611)

**Comment by sbespalov** [comment]
the follow-up tasks will be to get rid of `Hash`, `NuspecFile`, `NuspecFile` files and rework `PackageFeed.writeXml` method with `org.springframework.web.servlet.view.feed.AbstractAtomFeedView` based controller.

**Comment by carlspring** [comment]
I've updated the description, as per @sbespalov 's explanation.

@sbespalov : Should we have a separate task for this:
> the follow-up tasks will be to get rid of `Hash`, `NuspecFile`, `NuspecFile` classes and rework `PackageFeed.writeXml` method with `org.springframework.web.servlet.view.feed.AbstractAtomFeedView` based controller.

(I think it would make more sense).
