### ISSUE TITLE
Implement the TestRepository.RemoteRepository annotation support

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1147]
# Task Description

Currently there is `TestRepository` annotation, which can be used to create and inject `Repository` instance in **JUnit** tests.
This feature should be improved with Proxy repositories support.
* [ ] Create the `TestRepository.RemoteRepository` annotation like below:
```
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public static @interface RemoteRepository
{
    String url();
}
```
* [ ] Add the `TestRepositoryContext.remoteRepository` field
* [ ] Provide the `RemoteRepository` instance (if there is one) within `TestRepositoryContext` initialization
* [ ] Initialize the `MutableRepository.remoteRepository` field within the `TestRepositoryContext.open()` method, if there is `RemoteRepository` instance provided
* [ ] Make Unit Test for `@RemoteRepository` annotation

Finally the `RemoteRepository` should be used like below:
```
@Test
void testRepoteRepository(@TestRepository(layout = "Maven 2",
                                          storage = "storage0",
                                          repository = "r1")
@TestRepository.RemoteRepositry(url="http://repo1.maven.org/maven2/") remoteMavenCentralTestRepository)
{
...
}
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sbespalov** [comment]
done within [#1159](https://github.com/strongbox/strongbox/pull/1159)
