### ISSUE TITLE
Drop ResourceCloser and replace it with try-with-resources statements

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1168]
# Task Description

We should drop `org.carlspring.strongbox.resource.ResourceCloser` and use [native SDK features]( https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) instead.

# Tasks

The following classes are affected:
* [ ] `org.carlspring.strongbox.artifact.generator.NugetPackageGenerator`
* [ ] `org.carlspring.strongbox.services.ArtifactManagementServiceImplTest`
* [ ] `org.carlspring.strongbox.storage.metadata.MavenMetadataManager`
* [ ] `org.carlspring.strongbox.resource.ResourceCloser`
* [ ] `org.carlspring.strongbox.security.certificates.KeyStoreManager`
* [ ] `org.carlspring.strongbox.client.ArtifactResolverIntegrationTest`
* [ ] `org.carlspring.strongbox.controllers.BaseController`

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.
# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by prbobba** [comment]
I can take a look at this. 
For better understanding -- https://www.baeldung.com/java-try-with-resources

**Comment by carlspring** [comment]
Please, feel free to pick this up, @prbobba!

**Comment by prbobba** [comment]
I will definitely need some more time on this.

**Comment by ogryniuk** [comment]
@prbobba 

Do you still work on this issue?

**Comment by carlspring** [comment]
@ogryniuk : It's been 10 days since @prbobba said he'd look into this. I believe it's safe for you to pick it up, as we'd have probably seen a PR for it by now. So, please feel free to proceed! :)

**Comment by smolamarcin** [comment]
Hello. Please, assign this task to me.

**Comment by carlspring** [comment]
Hi, @smolamarcin !

@ogryniuk is currently looking into this. Would you like to join our 
our [chat channel](https://chat.carlspring.org/) to find out more on what other tasks you could help with? :)

**Comment by ogryniuk** [comment]
Hi @smolamarcin 

Yes, I am on this issue now. But there are plenty of others that are available
