### ISSUE TITLE
Implement Pypi Feeds

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1185]
# Task Description

We need to implement support for PyPi feeds.

# Tasks

The following tasks will need to be carried out:
* [ ] [Newest Packages Feed](https://warehouse.pypa.io/api-reference/feeds/#newest-packages-feed)
* [ ] [Latest Updates Feed](https://warehouse.pypa.io/api-reference/feeds/#latest-updates-feed)
* [ ] [Project and release activity details](https://warehouse.pypa.io/api-reference/feeds/#project-and-release-activity-details)

# Task Relationships

This task:
* Is a sub-task of: #807 
* Depends on: #809 
* Relates to: #1179 

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by LSariel** [comment]
Could I give this a go? :)

**Comment by carlspring** [comment]
Hi @LSariel ,

Feel free to pick it up. Is it clear what needs to be done? Would you like to join
our [chat channel](https://chat.carlspring.org/)?

**Comment by LSariel** [comment]
Thank you! :) 
I'm not 100% sure that I know exactly what should be done, but I'll take a closer look at it after work to make it clearer.

**Comment by LSariel** [comment]
Hi! I just wanted to update that I'm starting to work on this now. I suddenly got ill, but am fine now. :)

**Comment by carlspring** [comment]
Hi!
Okay! Good luck!

**Comment by LSariel** [comment]
Really sorry. But due too an accident I won't be able to work anymore on this before school starts again. Hoping to be able to take up some other issue when everything is back in order!

**Comment by carlspring** [comment]
Hi!

Get well soon! Thanks for letting us know.

This task is now up for grabs.
