### ISSUE TITLE
Create a database to maven-indexer exporter

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1202]
# Task Description

For our Maven support, we need to create an index exporter. This will be used by cron tasks to produce Lucene indexes and incremental indexes using the [`maven-indexer`](https://github.com/apache/maven-indexer/), so that other repository managers, as well as IDE-s could be able to integrate with our repository manager.

Initially, our implementation was such that we were using the Maven indexer for the Maven repositories as the place where artifacts records would be indexed. However, we're now storing this information in the database and the goal is to drop most of our code for the indexer (we've already deprecated most our code for this, including our tests) and only produce such indexes via scheduled task.

# Classes of Interest

* `org.carlspring.strongbox.domain.ArtifactEntry`
* `org.carlspring.strongbox.artifact.coordinates.MavenArtifactCoordinates`
* `org.carlspring.strongbox.storage.indexing.*`

Generally, you will be interested in having a look at the classes from the `strongbox-storage-maven-layout-provider` and the `strongbox-db-*` modules.

Note:
* To enable the (deprecated) Maven Indexer, use `-Dmaven.indexer.enabled=true`.
* We have our own fork of the `maven-indexer`. We have been perhaps the main contributors for the `6.0` release and we've been contributing more fixes as well. We use our fork because we want to know that the snapshot dependency against which we're running is stable. We're using a snapshot dependency, because not all of our PR-s have been merged yet and because it's not yet clear when Apache will release a new version of the `maven-indexer`.

# Tasks

The following tasks will need to be carried out:
* [ ] Rebase #702 and use as a starting point to continue the work.
* [ ] Move the work to a new branch in the upstream (called `issue-1202/maven-index-exporter`), so that more OSS developers could help with it.
* [ ] **TODO:** @fuss86 : Could you please list the remaining tasks here?

# See Also

* [`strongbox-db`](https://github.com/strongbox/strongbox-db/)
* [Strongbox: Maven Indexer Support](https://strongbox.github.io/developer-guide/maven-indexer.html) 
* [Strongbox: Maven 2 Layout Provider](https://strongbox.github.io/developer-guide/layout-providers/maven-2-layout-provider.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@fuss86 ,

I've asked @cbrianhill to investigate the requirements and continue your work on this. Could you please guide him when necessary?

@cbrianhill ,

Please, feel free to gather all questions and finding here for future references.

Thanks! :)

**Comment by carlspring** [comment]
Also, @cbrianhill ,

Perhaps @slachiewicz will also be able to advise, or help with this task.

**Comment by fuss86** [comment]
Hi @cbrianhill ,

have you had a chance to start working on it ? Do you have any questions ?

**Comment by cbrianhill** [comment]
Hi @fuss86, I just got into this last night.  Mostly read the code in your branch, rebased, and looked at the old, deprecated implementation.  No questions just yet!

**Comment by fuss86** [comment]
Great, let me know if there is anything :)

**Comment by fuss86** [comment]
@carlspring , 

could you please confirm that we **will no longer need** the ability to search for artifacts using the `maven indexer` ?

**Comment by carlspring** [comment]
Yeah, I think that all of our searching should be done through OrientDB.

**Comment by sbespalov** [comment]
> Yeah, I think that all of our searching should be done through OrientDB.

@carlspring  this probably means that we should drop the `ArtifactSearchServiceImpl` and `SearchProvider` in favor of `AqlController` and `AqlSearchService`.

is there an issue for this?

**Comment by sbespalov** [comment]
BTW, we can try to use [Lucene FullText Index](http://orientdb.com/docs/3.0.x/indexing/Full-Text-Index.html) within this task. This will be probably the best way in case if it will suit

**Comment by cbrianhill** [comment]
A couple of questions for @carlspring , @fuss86 :

1. Do we wish to maintain the API functionality to rebuild indexes?
2. Do we want to completely remove the old indexer, or leave it for some time, using properties to switch between the two?

**Comment by carlspring** [comment]
@cbrianhill .

1. For the moment, please don't concern yourself with the cron tasks for rebulding the indexes.
2. We don't want to completely drop the `maven-indexer` for the moment. It's actually not really used anywhere anymore and we've disabled the code for it.

This task concerns only the exporting of the data from OrientDB to a Maven index.

**Comment by fuss86** [comment]
@cbrianhill did you give up ?  :)

**Comment by cbrianhill** [comment]
@fuss86 , @carlspring , no, not given up, but haven't had much time to contribute in the past couple of months.  I want to jump back onto this if no one else has picked it up.

**Comment by fuss86** [comment]
Thanks @cbrianhill , but unfortunately I picked it up https://github.com/strongbox/strongbox/pull/702

Please look around and choose another one :)

**Comment by cbrianhill** [comment]
👍 thanks @fuss86 , will grab another issue!

**Comment by carlspring** [comment]
Implemented by @fuss86.
