### ISSUE TITLE
Update the inceptionYear in all pom.xml files to 2019

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1211]
# Task Description

Go over all the `pom.xml` files and update the `<inceptionYear>` to `2019`.

These changes will have to be applied to the following projects:
* [x] [`strongbox`](https://github.com/strongbox/strongbox/)
* [x] [`strongbox-db`](https://github.com/strongbox/strongbox-db/)
* [x] [`strongbox-npm-metadata`](https://github.com/strongbox/strongbox-npm-metadata/)
* [ ] [`strongbox-examples`](https://github.com/strongbox/strongbox-examples/)
* [x] [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by syakubov** [comment]
On it.

**Comment by carlspring** [comment]
Hi @syakubov!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

If the tag hasn't been added to the `pom.xml` files of the rest of the repositories, then we need to add it with the correct year.

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with. I see you have experience with C++. We have some tasks related to NuGet. Perhaps you'd like to join and have a look at them as well...? :)

Kind regards,

Martin

**Comment by syakubov** [comment]
@carlspring ,

I wanted to ask in chat but for whatever reason the server is not responding for the past hour.

In  [`strongbox`](https://github.com/strongbox/strongbox/) for example, there are pom.xml files without the tag as well. So, just to be clear, **we want every single pom.xml file to contain <inceptionYear>2019</inceptionYear/>**, even in the repos that contain other pom.xml files that have the tag, correct? For example, in the strongbox-cron directory, the pom.xml file looks like this:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.carlspring.strongbox</groupId>
        <artifactId>strongbox-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>strongbox-cron</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Strongbox: Cron</name>

    <scm>
        <url>https://github.com/strongbox/strongbox/</url>
        <connection>scm:git:git://github.com/strongbox/strongbox.git</connection>
        <developerConnection>scm:git:git://github.com/strongbox/strongbox.git</developerConnection>
    </scm>

    <modules>
        <module>strongbox-cron-api</module>
        <module>strongbox-cron-tasks</module>
    </modules>

</project>

But for the strongbox-commons directory:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.carlspring.strongbox</groupId>
        <artifactId>strongbox-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>strongbox-commons</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Strongbox: Commons</name>

    <licenses>
        <license>
            <name>Apache 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>A business-friendly OSS license</comments>
        </license>
    </licenses>

    <organization>
        <name>Carlspring Consulting &amp; Development Ltd.</name>
        <url>http://www.carlspring.org/</url>
    </organization>

    <inceptionYear>2019</inceptionYear>

    <scm>
        <url>https://github.com/strongbox/strongbox/</url>
        <connection>scm:git:git://github.com/strongbox/strongbox.git</connection>
        <developerConnection>scm:git:git://github.com/strongbox/strongbox.git</developerConnection>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>

                <configuration>
                    <systemPropertyVariables>
                        <strongbox.home>${project.build.directory}/strongbox</strongbox.home>
                        <logging.dir>${strongbox.vault}/logs</logging.dir>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <useDefaultDelimiters>false</useDefaultDelimiters>
                    <delimiters>
                        <delimiter>@{*}</delimiter>
                    </delimiters>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>strongbox-common-resources</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.carlspring.commons</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.carlspring.commons</groupId>
            <artifactId>commons-http</artifactId>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.lambdista</groupId>
            <artifactId>try</artifactId>
            <version>0.3.1</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${version.guava}</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jul-to-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jaxb-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
        </dependency>
    </dependencies>

</project>

Where would you like the tag in the first type of pom.xml file?

**Comment by carlspring** [comment]
Hi,

I was actually thinking of the same thing. Could you please go over all the `pom.xml` files in each of the listed project and:
* If they don't have the `inceptionYear` defined, add it and set it to `2019`
* If they have it, then update the version accordingly

Thanks! :)

**Comment by syakubov** [comment]
I see, and as long as the tag is a direct child of the root tag, that should be fine?

**Comment by carlspring** [comment]
> I see, and as long as the tag is a direct child of the root tag, that should be fine?

Not sure what you mean by this.

The chat is working fine. Do you have proxy/firewall issues?

**Comment by syakubov** [comment]
Sorry, I meant at the top level of the hierarchy, i.e. not nested in any other tags. Upon further analysis I think that is the case, I'll put it close to the top of the file.

**Comment by carlspring** [comment]
Thanks for your help, @syakubov and congratulations on your first set of pull requests! :)
