### ISSUE TITLE
Drop our dependency on the semantic-versioning project and remove the fork

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1214]
# Task Description

We only need one class from the `semantic-versioning` project which we now have a fork of.

# Tasks

The following tasks will need to be carried out:
* [x] Copy the original class to our project and call it `SemanticVersion`.
* [x] Drop our dependency on `semantic-versioning` from the `pom.xml`-s.
* [ ] Delete the fork.
* [ ] Delete the Jenkins job.

# Task Relationships

This task:
* Is required for: #1130
* Is a follow-up of: #611
* Relates to: #1131
