### ISSUE TITLE
NuGet 2.0 layout support finalization

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1215]
# Task Description

This is the master task for the NuGet 2.0 protocol support.

# Tasks

The following tasks will need to be carried out:
* [ ] #1131 : Drop the dependencies to jnuget-core and jnuget-server
* [ ] #1214 : Drop our dependency on the semantic-versioning project and remove the fork
* [ ] #1146 : Get rid of TempNupkgFile
