### ISSUE TITLE
Update our documentation regarding the configuration files

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1216]
# Task Description

As a follow-up to #965, we need to update our documentation. We should:
* [ ] Add a page called "The strongbox.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* [ ] Add a page called "The strongbox-authorization.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* [ ] Add a page called "The strongbox-cron-tasks.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* [ ] Add a page called "The strongbox-security-users.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* [ ] Update the [Application Properties](https://strongbox.github.io/user-guide/application-properties.html) page.
* [ ] Update the [Routing Rules](https://strongbox.github.io/user-guide/artifact-routing-rules.html) page.

**Comment by steve-todorov** [comment]
@carlspring what is expected to be updated in the `Application Properties` page?

**Comment by ggold7046** [comment]
@carlspring , @sbespalov  , @fuss86 

what is to be added into the files "The strongbox.yaml file",  "The strongbox-authorization.yaml file" , "The strongbox-cron-tasks.yaml file", "The strongbox-security-users.yaml file" ?
