### ISSUE TITLE
OrientDB Studio does not work in strongbox-distribution

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1251]
# Task Description

OrientDB Studio is not reachable at `http://localhost:2480/studio/index.html` when Strongbox is started from the `strongbox-distribution.tar.gz`. However, if you are starting it via `cd strongbox-web-core && mvn spring-boot:run` it's working as expected. It looks like OrientDB Studio is unable to locate the resources it needs.

We have added a smoke test for this.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works and OrientDB Studio starts properly and is accessible.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task is a follow-up of: #1087 , strongbox/strongbox-docs#22.

# Help

Please [join our chat](join-chat) and ping @steve-todorov or @carlspring when you create a PR so one of us can approve the testing stages in our CI.

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

[join-chat]: https://chat.carlspring.org/

**Comment by fuss86** [comment]
@steve-todorov , how did you try to run the distribution ? Using wrapper executable ?

1. If we try to run the distribution as `java -jar strongbox-distribution-1.0-SNAPSHOT/strongbox-1.0-SNAPSHOT/lib/strongbox-web-core-1.0-SNAPSHOT-spring-boot.jar` then `setenv.conf` does not have effect and all values are taken from `application.properties` from `strongbox-commons` module.

2. running windows executable `wrapper-windows-x86-64.exe` does not work

![Screenshot_29](https://user-images.githubusercontent.com/12829566/56998999-be6f7300-6bad-11e9-9b20-42f6d96640db.png)

3. running `strongbox.bat` works but the result is the same as in 1.

**Comment by cbrianhill** [comment]
I've finally found the issue.  For me, at least, the root DB path when I start strongbox from the distribution contains a relative path that uses `..` to go back up the directory tree.  You can see the line in OrientDB source code I'm referring to here:

https://github.com/orientechnologies/orientdb/blob/develop/server/src/main/java/com/orientechnologies/orient/server/network/protocol/http/command/get/OServerCommandGetStaticContent.java#L249

**Comment by cbrianhill** [comment]
After conversation with @carlspring, we will not invest in a major refactor wrapper, and we do not want to include `strongbox-vault` inside the application install directory because we want that directory to be independent to better support upgrades.  We'll update the wrapper to explicitly list `/opt/strongbox-vault` as the data directory, and add some notes to the documentation to instruct users that they'll need to change the configuration if they don't install in the customary location.

**Comment by carlspring** [comment]
We should avoid hardcoding things at all cost. We should either consider submitting a patch to OrientDB, or think of a better way to do it.

**Comment by cbrianhill** [comment]
This is now working from strongbox-distribution, with only the caveat that, when starting Strongbox with OrientDB Studio enabled, the path to `strongbox-vault` needs to be an absolute path without `..` as a path segment.

Strongbox documentation at https://strongbox.github.io/developer-guide/getting-started-with-persistence.html has been updated to provide this instruction for our users.

The following issue has been raised on OrientDB, asking to loosen the upward directory traversal check:  https://github.com/orientechnologies/orientdb/issues/8859

**Comment by carlspring** [comment]
Thanks for following up on this @cbrianhill ! :)

**Comment by sbespalov** [comment]
@steve-todorov can you please verify the PR above?

**Comment by steve-todorov** [comment]
@sbespalov It looks like your PR fixes it. Thanks! :)
