### ISSUE TITLE
Implement a test that creates a raw proxy repository and attempts to download an artifact through it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1252]
# Task Description

We need a new test to be added to the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project that creates a raw proxy repository and resolves an artifact through it.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new module called `raw` under the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project.
* [ ] Add a new test in the module that creates a `Raw` proxy repository to `https://services.gradle.org/distributions/` and attempts to download `https://services.gradle.org/distributions/gradle-5.3-bin.zip`.

# References

* The [strongbox.yaml](https://strongbox.github.io/user-guide/configuration-files/strongbox-yaml.html)
* Our [REST API](https://strongbox.github.io/user-guide/rest-api.html).
* `org.carlspring.strongbox.client.RestClient` : This class should provide you the means to create a repository over the REST API. It might need to be improved.
* Have a look at the other modules in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project and try to follow the same approach of doing things.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by bamarch** [comment]
I will start working on this issue

**Comment by bamarch** [comment]
- [ ]  Create a new module called raw under the strongbox-web-integration-tests project.

**Comment by bamarch** [comment]
work-in-progress branch:
https://github.com/strongbox/strongbox-web-integration-tests/commit/558d45cf6f8b0b82361035545e1adb25373bbe6a

todo:

- [ ] debug adding the proxy repo
- [ ] download the artifact

**Comment by bamarch** [comment]
Ran into something that gave me pause...

___________________________

When I docker-compose in my new module, and run my test, the intention is:
- create a new storage
- create a new repository - but, it fails 😞
- ... I will do other stuff later

my work-in-progress branch is here, this is the part where I add a new repository
github.com/strongbox/strongbox-web-integration-tests/blob/558d45cf6f8b0b82361035545e1adb25373bbe6a/raw/src/it/proxy-repository/test-raw-proxy-repository.groovy#L71

this is the output where it fails to create a new repository (I modified the method to return the response, not just the status code) 
gist.github.com/bamarch/fc2c705638a6c805aa3b1b61a473cee0#file-gistfile1-txt-L116
___________________________

sergey suggested I try the following:

1. there also should be a message, so you can try to read it from response you have
2. if message is not clear you can try to check the StoragesConfigurationController.addOrUpdateRepository method and see what can cause this response
3. if it still not clear you can start strongbox with spring-boot:run (or directly from your IDE) and try to debug same requests there

___________________________

I am unblocked and back on track, but will be M.I.A. until Monday due to holidays

**Comment by bamarch** [comment]
back from hols, and I spent today finishing up PR #1334

I will continue on this task (#1252) later in the week

**Comment by bamarch** [comment]
In my pom.xml, which I based off the npm one, I had to make a change that resolves a recursive expression cycle

It was only my IDE that complained, not running mvn on the command line (although my IDE shoud be using system mvn...)

My change works fine locally but it might cause issues on jenkins? 

![image](https://user-images.githubusercontent.com/24650490/59460469-759f1100-8e1f-11e9-84e3-3425fe978352.png)

**Comment by bamarch** [comment]
> if it still not clear you can start strongbox with spring-boot:run (or directly from your IDE) and try to debug same requests there

this was a great tip

I could run strongbox using spring boot, directly in my IDE, and then run my raw s-w-i-t with 
`mvn -DskipJetty clean install -U`

this meant I could debug the requests as they came in and were handled

**Comment by bamarch** [comment]
ok raw proxy repo created, just left is todo:

- download the artifact
- cleanup

**Comment by carlspring** [comment]
@bamarch ,

You shouldn't have to modify any of these properties. What was the reason to do so?

**Comment by bamarch** [comment]
@carlspring 

If I run  maven lifecycle goals via IDEA (clean/install...) I get errors i.e. ‘recursive expression cycles’.

This is due to apparently cyclical definitions of strongbox.host and strongbox.port...

I only get this in IDEA, not when running via the command line (even though  I configured IDEA to use the system maven, not the bundled one)

I’m wondering if there is some setting that needs tweaking in Intellij to prevent this - for now the changes I show above give me a workaround

**Comment by bamarch** [comment]
@carlspring so I had another look at the maven settings

it detected profiles in the pom.xml, as so:

![image](https://user-images.githubusercontent.com/24650490/59489179-c182a200-8e81-11e9-8cc4-57abf064d122.png)

if I just removed them from the box 

![image](https://user-images.githubusercontent.com/24650490/59489252-f131aa00-8e81-11e9-8c26-ce3709eb67d8.png)

Then it will run in IDEA, even with the original pom.xml properties

**Comment by bamarch** [comment]
OK @carlspring the branch is basically ready, it works when I run it via maven

But, I am having issues when running it inside a container via docker-compose

running `cd raw && mvn -U clean install` (works)
![image](https://user-images.githubusercontent.com/24650490/59567523-2bac6a00-906f-11e9-8a97-d805f19b3790.png)

running `cd raw && docker-compose up` (exits)
![image](https://user-images.githubusercontent.com/24650490/59567563-a1b0d100-906f-11e9-8624-74003f969307.png)

it might be that the download is timing out, because this file is around 90mb and my home internet speed is very slow - any ideas?

I have tried it a few times now, via my IDE, maven, docker - the issue only happens when using docker-compose

this is my branch:
https://github.com/bamarch/strongbox-web-integration-tests/tree/issue-1252/raw

**Comment by bamarch** [comment]
`docker-compose --verbose up`
![image](https://user-images.githubusercontent.com/24650490/59567696-336d0e00-9071-11e9-90f4-40651648210c.png)

```
strongbox-web-integration-tests-raw_1  | Attempting to download http://localhost:48080/storages/storage-raw-proxies/raw-gradle-distributions-proxy/gradle-5.3-bin.zip
compose.cli.verbose_proxy.proxy_callable: docker wait <- (u'21636672cf3eda0d0bc51a421e6b62059ed08b764059715c75b689354f7709b4')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- (u'21636672cf3eda0d0bc51a421e6b62059ed08b764059715c75b689354f7709b4')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/21636672cf3eda0d0bc51a421e6b62059ed08b764059715c75b689354f7709b4/wait HTTP/1.1" 200 30
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/21636672cf3eda0d0bc51a421e6b62059ed08b764059715c75b689354f7709b4/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker wait -> {u'Error': None, u'StatusCode': 0}
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {u'AppArmorProfile': u'docker-default',
 u'Args': [u'clean', u'install', u'-U'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'mvn', u'clean', u'install', u'-U'],
             u'Domainname': u'',
             u'Entrypoint': None,
             u'Env': [u'PATH=/java/jdk8u202-b08/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
                      u'USER_ID=1000',
...
```

**Comment by bamarch** [comment]
not much extra info when also passing --debug flag to mvn command

![image](https://user-images.githubusercontent.com/24650490/59567962-3f0e0400-9074-11e9-88c3-64706498617f.png)

**Comment by bamarch** [comment]
Opening this PR https://github.com/strongbox/strongbox-web-integration-tests/pull/49

to see if the issue still happens on Jenkins

**Comment by bamarch** [comment]
> Opening this PR [strongbox/strongbox-web-integration-tests#49](https://github.com/strongbox/strongbox-web-integration-tests/pull/49)
> 
> to see if the issue still happens on Jenkins

it's looking good on jenkins (Y)
