### ISSUE TITLE
Set up a new module for smoke tests and add basic tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1253]
# Task Description

We need a new test to be added to the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project that creates a raw proxy repository and resolves an artifact through it.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new module called `smoke-tests` under the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project.
* [ ] Add smoke tests:
  * [ ] Login
  * [ ] Logout
  * [ ] Search for a Maven artifact
  * [ ] OrientDB Studio is working (#1251). For this, the OrientDB Studio will have to be enabled

# References

* Our [REST API](https://strongbox.github.io/user-guide/rest-api.html).
* `org.carlspring.strongbox.client.RestClient` : This class might need to be improved, but should provide most of the required methods.
* Have a look at the other modules in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project and try to follow the same approach of doing things.

# Task Relationships

This task relates to: #1087, #1251 .

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@steve-todorov: Could you please provide a list of things you'd like for us to be testing? Thanks! :)

**Comment by Gcolon021** [comment]
@carlspring Claiming.
