### ISSUE TITLE
Minor refactoring of the strongbox-data-service module

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1257]
# Task Description

We need a minor refactoring of the `strongbox-data-service` module.

# Tasks

The following tasks will need to be carried out:
* OrientDB configuration-related refactoring:
  * [ ] Create package called `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `InMemoryOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `EmbeddedOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Move `CommonOrientDbConfig` under `org.carlspring.strongbox.config.orientdb`.
  * [ ] Rename `OrientDBProfile` to `OrientDbProfile` and move it under `org.carlspring.strongbox.config.orientdb`.
* Hazelcast configuration-related refactoring:
  * [ ] Create package called `org.carlspring.strongbox.config.hazelcast`.
  * [ ] Move `HazelcastConfiguration` under `org.carlspring.strongbox.config.hazelcast`.
  * [ ] Move `HazelcastInstanceId` under `org.carlspring.strongbox.config.hazelcast`.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by faissalwise** [comment]
Hi ,

Can I take this up?

**Comment by carlspring** [comment]
Hi @faissalwise!

Thanks for offering, but I'm afraid this has already been done by @rathan-naik in #1258.
