### ISSUE TITLE
Cleanup our dependency tree and make sure we have no dependencies on commons-collections 3.x

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1262]
# Task Description

Some of our dependencies seem to be bringing along vulnerable versions of `commons-collections`. We should scan the Maven dependency for all modules and define dependency exclusions for any dependencies that are bringing along versions of `commons-collections`, such as version `3.2.1`. The dependency exclusions should be defined in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent) project. We should override such dependencies by defining dependencies to newer versions of  `commons-collections` such as `commons-collections4`, version `4.3`. 

Please, note that:
* Newer versions of `commons-collections` have been renamed to `commons-collections4`.
* Some code changes might be likely as well.

# Acceptance Test

* [ ] Running `mvn dependency:tree` ( `mvn dependency:tree | grep commons-collections` ) should not yield any 3.x dependencies.
* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ganeshselvaraj86** [comment]
Hello

This is Ganesh. I would like to contribute to the project. I am facing dependency issues while trying to build this project. Can someone help?

I have cloned this project locally and ran mvn clean install.

Could not find artifact org.carlspring.strongbox:strongbox-db-server:jar:1.0-SNAPSHOT

Thanks

**Comment by pavanp73** [comment]
Hello,

I would like to work on this.

Thanks.

**Comment by carlspring** [comment]
@ganeshselvaraj86 : I don't think you've followed the Developer's Guide very well, in particular the [Getting Started](https://deploy-preview-26--strongbox.netlify.com/developer-guide/getting-started.html) and [How To Build The Code](https://deploy-preview-26--strongbox.netlify.com/developer-guide/building-the-code.html) articles.

**Comment by carlspring** [comment]
@pavanp73 , @ganeshselvaraj86 , would you like to join our [chat channel](https://chat.carlspring.org/)?

**Comment by ganeshselvaraj86** [comment]
> @ganeshselvaraj86 : I don't think you've followed the Developer's Guide very well, in particular the [Getting Started](https://deploy-preview-26--strongbox.netlify.com/developer-guide/getting-started.html) and [How To Build The Code](https://deploy-preview-26--strongbox.netlify.com/developer-guide/building-the-code.html) articles.

I am able to fix the problem. I have missed the Getting Started section.
