### ISSUE TITLE
Upgrade to jackson 2.9.9

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1285]
# Task Description

We need to upgrade to Jackson 2.9.9.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version of the Jackson dependencies in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/) project.
* [ ] Update the version of the Jackson dependencies in the [`strongbox-proto-parent`](https://github.com/strongbox/strongbox-proto-parent/) project.
* [ ] Update the version of the Jackson dependencies in the [`strongbox-npm-metadata`](https://github.com/strongbox/strongbox-npm-metadata/) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ptirador** [comment]
Hi, I'd like to take this up.

**Comment by carlspring** [comment]
Go for it!

**Comment by ptirador** [comment]
@carlspring: I've created 3 PRs,one for each project, they're referenced here. Please take a look whenever you can.
