### ISSUE TITLE
 CronTaskConfigurationDto should base on java.util.UUID not on java.lang.String 

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1300]
# Task Description

We need to change the [CronTaskConfigurationDto#uuid](https://github.com/strongbox/strongbox/blob/master/strongbox-cron/strongbox-cron-api/src/main/java/org/carlspring/strongbox/cron/domain/CronTaskConfigurationDto.java#L21) type from `String` to [UUID](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html)

It will affect following classes (at least):
Changes should be made at least within:

* [ ] `org.carlspring.strongbox.cron.domain.CronTaskConfigurationDto`
* [ ] `org.carlspring.strongbox.cron.services.CronJobSchedulerService`
* [ ] `org.carlspring.strongbox.cron.services.CronTaskDataService`
* [ ] `org.carlspring.strongbox.controllers.cron.CronTaskController`

We should ensure [UUID](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html) is used between application layers.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@ptirador ,

As you've already done some work on the cron tasks before, would you perhaps like to look into this?

**Comment by ptirador** [comment]
@fuss86 @carlspring : When we dispatch a cron event:
```
public void dispatchCronTaskCreatedEvent(String cronTaskName)
    {
        CronTaskEvent event = new CronTaskEvent(CronTaskEventTypeEnum.EVENT_CRON_TASK_SAVED.getType(), cronTaskName);

        logger.debug("Dispatching CronTaskEventTypeEnum.EVENT_CRON_TASK_SAVED event for '{}'...", cronTaskName);

        dispatchEvent(event);
    }
```

What should be passed, the cron task name or the cron task UUID?

**Comment by carlspring** [comment]
What do you propose? I think it should probably be the UUID, but I'm not sure...

**Comment by ptirador** [comment]
Currently the name is being used, I think it should probably be the UUID too.

**Comment by carlspring** [comment]
It looks like we're on the same page. Please, proceed with converting it to use UUID instead.
