### ISSUE TITLE
Minor class name refactoring in the strongbox-aql module

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1309]
# Task Description

The classes in the `strongbox-aql` project under the `org.carlspring.strongbox.aql` package are inconsistently named. All classes starting with `AQL*` should be renamed to `Aql*`.

# Tasks

The following classes will need to be renamed:

* [ ] `AqlExpressionDialect`
* [ ] `AQLExpressionVisitor`
* [ ] `AqlMapping`
* [ ] `AQLPaginatorVisitor`
* [ ] `AqlQueryParser`
* [ ] `AQLQueryVisitor`
* [ ] `AQLStatementVisitor`

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by abhishek-iitj** [comment]
Would like to work on this one.
@carlspring Should I proceed?

**Comment by carlspring** [comment]
Hi @abhishek-iitj ,

Please, feel free to proceed and to join our [chat channel](https://chat.carlspring.org/).

Thanks!

**Comment by michan94** [comment]
If this issue hasn't been resolved yet, I can go through it quickly

**Comment by carlspring** [comment]
@michan94 ,

Thanks for offering to help, but @abhishek-iitj , has already implemented this in #1321 . We're still waiting for him to sign the ICLA. If he hasn't done so within the next 3-4 days, we can close #1321 and you can have a go at it.

**Comment by abhishek-iitj** [comment]
I just emailed the signed ICLA to Carl.

Thanks & Regards

--
Abhishek Sah
https://abhishek-iitj.github.io
