### ISSUE TITLE
Re-work the NuGet tests to use the new annotations

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1327]
# Task Description

As a follow-up to #1295 , #1303 , #1304 , we need our existing tests for the NuGet layout provider to be re-worked to use the `NugetTestArtifact` and `NugetTestRepository` annotations instead.

Please, note:
* This task involves quite a few test cases and it can be done in chunks -- you can fix one, or more tests and create a pull request and link it to this task.
* Multiple people can work on this task. For this to work out properly, please add a comment, when you decide to pick some test(s) to work on, so that others know not to work on them.
* This task is good for new joiners who have sufficient experience with JUnit and testing and will quickly help them learn more about the project.

# What Needs To Be Done

* There should be no creation of repositories and test resources (such as artifacts) in initialization methods annotated with `@BeforeAll`, or `@BeforeEach`, such as, for example, `initialize()` methods.
* At the moment, the test methods are all creating their own test repositories and artifacts. The code for this will have to be dropped and replaced with the annotations.
* Drop the `removeRepositories()` methods.
* Drop the `cleanUp()` methods.
* Each test method needs to generate its own test repository (or repositories) and test resources (typically, artifacts).

# Tasks

The following tests under the `strongbox-storage-nuget-layout-provider` module will need to be evaluated and re-worked:

* [x] `org.carlspring.strongbox.artifact.coordinates.NugetArtifactConverterTest` (@ptirador)
* [x] `org.carlspring.strongbox.artifact.generator.NugetArtifactGenerator` (@ptirador)
* [x] `org.carlspring.strongbox.cron.jobs.BaseCronJobWithNugetIndexingTestCase` (@ptirador)
* [x] `org.carlspring.strongbox.cron.jobs.RegenerateNugetChecksumCronJobTestIT` (@ptirador)
* [x] `org.carlspring.strongbox.dependency.snippet.NugetDependencyFormatterTest` (@ptirador)
* [x] `org.carlspring.strongbox.nuget.filter.NugetFilterODataParserTestCase` (@ptirador)
* [x] `org.carlspring.strongbox.providers.repository.NugetGroupRepositoryProviderTest` (@ptirador)
* [x] `org.carlspring.strongbox.storage.indexing.NugetRemoteRepositoryTest` (@ptirador)
* [x] `org.carlspring.strongbox.storage.metadata.nuget.TempNupkgFileTest` (@ptirador)
* [x] `org.carlspring.strongbox.storage.metadata.nuget.rss.PackageFeedTest` (@ptirador)
* [x] `org.carlspring.strongbox.testing.TestCaseWithNugetArtifactGeneration` (@ptirador)

# Task Relationships

This task:
* Depends on:  #1295, #1303 , #1304 .
* Relates to: #1165 , #1328 .
* Is required for: #947 .

# Useful Links

* [Writing Tests: Getting started](https://strongbox.github.io/developer-guide/writing-tests.html)
* [Writing Tests: JUnit5](https://strongbox.github.io/developer-guide/junit-user-guide.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @ptirador 
  * @sbespalov
  * @fuss86

**Comment by ajaybhat** [comment]
I can pick this up.

**Comment by ptirador** [comment]
I'd like to pick this up if @ajaybhat is not working on it.

**Comment by carlspring** [comment]
Go for it!

**Comment by carlspring** [comment]
Thanks @ptirador and @sbespalov for looking into this! :)

@ptirator: Do you have the before and after build times? It would be cool to compare them and see how this impacted the build times.
