### ISSUE TITLE
Re-work the NPM tests to use the new annotations

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1328]
# Task Description

As a follow-up to #1294 , #1301 , #1302 , we need our existing tests for the NuGet layout provider to be re-worked to use the `NpmTestArtifact` and `NpmTestRepository` annotations instead.

Please, note that this task is good for new joiners who have sufficient experience with JUnit and testing and will quickly help them learn more about the project.

# What Needs To Be Done

* There should be no creation of repositories and test resources (such as artifacts) in initialization methods annotated with `@BeforeAll`, or `@BeforeEach`, such as, for example, `initialize()` methods.
* At the moment, the test methods are all creating their own test repositories and artifacts. The code for this will have to be dropped and replaced with the annotations.
* Drop the `removeRepositories()` methods.
* Drop the `cleanUp()` methods.
* Each test method needs to generate its own test repository (or repositories) and test resources (typically, artifacts).

# Tasks

The following tests under the `strongbox-storage-npm-layout-provider` module will need to be evaluated and re-worked:

* [ ] `org.carlspring.strongbox.artifact.coordinates.NpmArtifactCoorinatesTest`
* [ ] `org.carlspring.strongbox.cron.jobs.FetchChangesFeedCronJobTestIT`
* [ ] `org.carlspring.strongbox.testing.NpmRepositoryTestCase`
* [ ] `org.carlspring.strongbox.dependency.snippet.NpmDependencyFormatterTest`

# Task Relationships

This task:
* Depends on:  #1294 , #1301 , #1302 .
* Relates to: #1165 , #1327 .
* Is required for: #948 .

# Useful Links

* [Writing Tests: Getting started](https://strongbox.github.io/developer-guide/writing-tests.html)
* [Writing Tests: JUnit5](https://strongbox.github.io/developer-guide/junit-user-guide.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @ptirador 
  * @sbespalov
  * @fuss86

**Comment by VishwajeetNehra** [comment]
Hi, I'd like to work on this issue

**Comment by priyanka-tyagi** [comment]
@carlspring could I work on this issue?

**Comment by priyanka-tyagi** [comment]
I am picking up this issue. 😀

**Comment by carlspring** [comment]
Hi!

@VishwajeetNehra : Sorry, I seem to have missed your comments.

@priyanka-tyagi : Please, feel free to pick this up!

This should be a quick and easy task. If you guys are looking for more tasks, please feel free to pick up tests in #1165 and #1327.

**Comment by ptirador** [comment]
Hi! I'd like to pick this up.

**Comment by carlspring** [comment]
Great! Thank you!
