### ISSUE TITLE
Create a MavenTestRepository annotation

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1332]
# Task Description

As part of our on-going efforts to re-work our tests, so that they're simpler and easier to parallelize and, in continuation of our recent, work on getting test annotations for the easier generation of test repositories and artifacts, we need to implement an Maven-specific annotation for test repositories. Please, refer to the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html) for more details on how this is implemented. At the moment, the tests are using the generic `TestRepository` annotation which is layout provider independent.

# Tasks

* [ ] Implement a `MavenTestRepository` annotation.
* [ ] Update the tests in the `strongbox-storage-maven-layout-provider` to use the `MavenTestRepository`, instead of the generic `TestRepository` annotation.
* [ ] Update the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html).

# Task Relationships

This task:
* Relates to: #1165 , #1303, #1304 , #1305 .

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sarthak-sopho** [comment]
Hi! I want to take up this issue. Can anyone tell me how to get started? :)
Thanks

**Comment by fuss86** [comment]
Have you read the [documentation](https://strongbox.github.io/developer-guide/writing-tests.html) ?

**Comment by carlspring** [comment]
This has actually already been implemented as the `MavenRepository` annotation.
(My bad).
