### ISSUE TITLE
Handle Checked Exceptions With Lambda Expression

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1368]
# Task Description

We should introduce helper classes/methods like [here](https://dzone.com/articles/how-to-handle-checked-exception-in-lambda-expressi) to help us deal with limitations of lambda expressions and checked exceptions. We should at least create 2 classes/methods:

* [ ] `ThrowingFunction.unchecked`
* [ ] `ThrowingConsumer.unchecked`
* [ ] `ThrowingSupplier.unchecked`

and try to get rid of `UndeclaredThrowableException` and `RuntimeException` calls wherever possible, as long as it does not make a code less transparent and clear.

Example of valid usage: consider [this part of code](https://github.com/strongbox/strongbox/blob/master/strongbox-data-service/src/main/java/com/orientechnologies/orient/object/jpa/OJPAObjectDatabaseTxEntityManagerFactory.java#L69). It could be rewritten like this

```
Connection connection = ThrowingSupplier.unchecked(dataSource::getConnection)
                                        .get();
```

We can do similar refactoring in the follow up tasks. We can also try to find loops in the source code, that were not able to use lambdas before, but will be using proposed classes/methods.

# Acceptance Test

* [ ] Building the code and running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] Running the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by adavid9** [comment]
@fuss86 Hi Przemyslaw, I can start to work on that one ;)

**Comment by carlspring** [comment]
Welcome back, @adavid9 ! Feel free to dig into it!
