### ISSUE TITLE
Upgrade to Jackson >= 2.9.9.1

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1390]
# Task Description

[CVE-2019-12814](https://nvd.nist.gov/vuln/detail/CVE-2019-12814)
(moderate severity)
*Vulnerable versions:* >= `2.0.0`, < `2.9.9.1`
*Patched version:* `2.9.9.1`

A Polymorphic Typing issue was discovered in FasterXML `jackson-databind` `2.x` through `2.9.9`. When Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint and the service has JDOM 1.x or 2.x jar in the classpath, an attacker can send a specifically crafted JSON message that allows them to read arbitrary local files on the server.

# Tasks

The following tasks will need to be carried out:
* [ ] Upgrade the version of Jackson in the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent)
* [ ] Upgrade the version of Jackson in the [`strongbox-proto-parent`](https://github.com/strongbox/strongbox-proto-parent)
* [ ] Check the version of Jackson in the [`strongbox-npm-metadata`](https://github.com/strongbox/strongbox-npm-metadata)

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by mahendraramesh** [comment]
@carlspring Please let me know if i can help with this ticket. I can update the pom files for both strongbox-parent and strongbox-proto-parent.

**Comment by manikantanallagatla** [comment]
@carlspring: I've created 2 PRs (one for each project) ready for merging, https://github.com/strongbox/strongbox-proto-parent/pull/3, https://github.com/strongbox/strongbox-parent/pull/35.
 Please take a look whenever you can.

**Comment by carlspring** [comment]
Hi,

Thanks for looking into this. You will also need to apply it to the `strongbox-npm-metadata` project as well.

**Comment by manikantanallagatla** [comment]
@carlspring I have created PR to the strongbox-npm-metadata as well: https://github.com/strongbox/strongbox-npm-metadata/pull/10

**Comment by carlspring** [comment]
Hi @manikantanallagatla ,

Thank you for your contribution!

Have you actually tested this? Have you gone over the acceptance test criteria? We cannot accept pull requests without these tests passing. You will need to sign the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page.

There's now also a newer version of Jackson. It appears the `jackson-databind` dependencies now have their own independent versioning and we might need a separate property for this.

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by hduhar** [comment]
@carlspring i am willing to working on fixing this if this has not been fixed yet.

**Comment by carlspring** [comment]
@hduhar : Would you mind picking another task instead?

**Comment by mslowiak** [comment]
Updated jackson to version 2.10.0
