### ISSUE TITLE
Make the OrientDB settings configurable

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1393]
# Task Description

At the moment, the OrientDB configuration is stored in three different `properties` files, based on the Spring profile to be used:
* `orientdb_EMBEDDED.properties`
* `orientdb_MEMORY.properties`
* `orientdb_REMOTE.properties`

We need to be able to configure this via the `strongbox.yaml` instead and to drop the `properties` files.

# Tasks

The following tasks will need to be carried out:
* [ ] Make the OrientDB settings configurable via the `strongbox.yaml`.
* [ ] Make the OrientDB settings configurable via the controller.
* [ ] Make the OrientDB settings configurable via the UI.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
@carlspring there is something we need to discuss regarding this task, so it's better hold a little

**Comment by cbrianhill** [comment]
@sbespalov , @carlspring wanted me to reach out to you about this task.  We can take a similar approach to #1419 implementing this, which will give the ability to control the configurations for Hazelcast, but making configuration part of `strongbox.yaml` and editable via API / UI will run into the same limitations I faced in trying to implement #1392 .

**Comment by sbespalov** [comment]
@cbrianhill we probably won't be able to have OrientDB configurable with UI as you noticed. 

Another thing is that this task seems obsolete to me because we already have OrientDB settings configurable with Spring Environment properties (see [CommonOrientDbConfig#orientDbServerProperties](https://github.com/strongbox/strongbox/blob/master/strongbox-data-service/src/main/java/org/carlspring/strongbox/config/orientdb/CommonOrientDbConfig.java#L44)).


So following to this issue description we have below:

> At the moment, the OrientDB configuration is stored in three different properties files, based on the Spring profile to be used:

To be clear this is not a Spring Profile, but just Java System Property `strongbox.orientdb.profile` which can be `orientdb_MEMORY`, `orientdb_EMBEDDED` and `orientdb_REMOTE` as mentoned in task description.

> We need to be able to configure this via the strongbox.yaml instead and to drop the properties files.

this can't be done because this property files provides the default values for OrientDB configuration properties depending on `strongbox.orientdb.profile` value, so we can't just move this into `application.yaml` because default values depends on profile. The only thing we can do here is replace this property files with `@ConfigurationProperties` bean instances `@Conditional` on `strongbox.orientdb.profile` value.

>  Make the OrientDB settings configurable via the strongbox.yaml.

this is not possible as described above

>  Make the OrientDB settings configurable via the controller.

not possible

>  Make the OrientDB settings configurable via the UI.

not possible

**Comment by carlspring** [comment]
Closing this, as it will become obsolete with #1649 ( #1676 ).
