### ISSUE TITLE
Implement UI for 

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1394]
# Task Description

We need to implement a UI for the logging functionality.

# Tasks

The following tasks will need to be carried out:
* [ ] Implement UI for the logging configuration
  * [ ] Make it possible to add a logger for a new package
  * [ ] Make it possible to update a logger for an existing package
  * [ ] Make it possible to delete a logger for an existing package
* [ ] Log file operations:
  * [ ] Browse log files
  * [ ] Download a log file
  * [ ] Tail a log file in real time using Websockets

# Classes of Interest

* `org.carlspring.strongbox.controllers.LoggingManagementController`
* `org.carlspring.logging.services.LoggingManagementService` [check here](https://github.com/carlspring/logback-configuration/tree/master/logback-configuration-core/src/main/java/org/carlspring/logging/services)
  
# Useful Links

* [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui/)
* [Strongbox Wiki](https://strongbox.github.io/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
