### ISSUE TITLE
Implement UI for the cron tasks

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1395]
# Task Description

We need to implement a UI for the cron tasks.

# Tasks

The following tasks will need to be carried out:
* [ ] Implement UI for the configuration of cron tasks
  * [ ] Make it possible to add a new cron task
  * [ ] Make it possible to update an existing cron task
  * [ ] Make it possible to delete an existing cron task
* [ ] Filtering
* [ ] Cron task operations:
  * [ ] Browse all cron tasks
  * [ ] Pause/Unpause a running cron task (this functionality is not yet implemented)
  * [ ] Terminate a running cron task
  * [ ] View the output of a cron task (this functionality is not yet implemented)

# Useful Information

**Classes of Interest**

* [strongbox-cron](https://github.com/strongbox/strongbox/tree/master/strongbox-cron)
* `org.carlspring.strongbox.controllers.cron.CronTaskController`

# Task Relationships

This task:
* Depends on: #1373 

# Useful Links

* [Strongbox Cron Tasks](https://strongbox.github.io/user-guide/configuration-files/strongbox-cron-tasks-yaml.html)
* [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui/)
* [Strongbox Wiki](https://strongbox.github.io/)
* [Strongbox REST API](https://strongbox.github.io/user-guide/rest-api.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov
  * @carlspring
  * @fuss86
  * @sbespalov

**Comment by steve-todorov** [comment]
This task still depends on #1373, but in the mean time we can do partial UI for the tasks in the list with `(proceed)` at the end.
