### ISSUE TITLE
Implement UI for the LDAP configuration

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1396]
# Task Description

We need to implement a UI for the LDAP configuration.

# Tasks

The following tasks will need to be carried out:
* [ ] Enable/Disable LDAP configuration
* [ ] Configure LDAP settings
* [ ] Test LDAP configuration

# Useful Information

**Classes of Interest**

* `org.carlspring.strongbox.controllers.configuration.security.ldap.LdapAuthenticatorConfigurationController`

# Useful Links

* [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui/)
* [Strongbox Wiki](https://strongbox.github.io/)
* [Strongbox REST API](https://strongbox.github.io/user-guide/rest-api.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov
  * @carlspring
  * @fuss86
  * @sbespalov
