### ISSUE TITLE
Implement strict checksum validation for proxy repositories resolving from remotes

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1398]
# Task Description

We need to implement checksum validation for artifacts that are being resolved via repositories in Strongbox.

Each layout provider exposes a list of checksum formats that it supports. The artifact files in the remote will (typically) have these checksums available, unless the remote is configured to not have them, or unless they have been uploaded in a non-standard way (for example, using `curl`).

Logic when an artifact file has been requested from the remote, for all supported checksum files:
* Attempt to resolve the matching checksum files.
* If a layout provider supports more than one checksum format, (for example, Maven supports `md5` and `sha1`),
  * If both checksum files exist on the remote:
    * Download and store them under the local file system of the proxy repository.
    * Validate using both checksums.
      * If both pass, the validation is successful.
      * If one fails, the validation should fail.
  * If only one of the checksum files exist on the remote:
    * Download and store the file under the local file system of the proxy repository.
    * Validate using checksums.
      * If both pass, the validation is successful
      * If one fails, the validation should fail

Please note that the solution needs to be implemented in a generic enough way that works for all layout providers.

# Tasks

The following tasks will need to be carried out:
* [ ] Implement the checksum validation, as describe above.
* [ ] Make this functionality configurable globally for all repositories via the `strongbox.yaml`.
* [ ] Make this functionality configurable per repository via the `strongbox.yaml`.
* [ ] Make these setitngs configurable via the UI.

# Classes of Interest

TODO:
@sbespalov , @fuss86 : Could you please list the classes that are involved in this?

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
> @strongbox/core-developers : Discuss what HTTP error code should be returned. Possible options: 403, 406, 409. Any other suggestions? Please, comment!

I think `409 Conflict` will suit better in case of checksum validation failed, so it will be treated as checksums conflict. Also it will not affect on UI unlike `403`, which means the security restrictions for us at most cases.

Also we should have same issue for hosted repositories. Currently we already have `ChecksumCacheManager` which is used for uploaded artifacts checksum validation, but there is no clear result in case of invalid checksums. So we should probably use the same HTTP code for hosted repositories as for proxy ones.

@carlspring in addition recently we think to make strict checksum validation configurable per repository.

**Comment by fuss86** [comment]
> Each layout provider exposes a list of checksum formats that it supports.

I don't think we have it, @carlspring .

> I think 409 Conflict will suit better in case of checksum validation failed

I think it's good option too.

**Comment by steve-todorov** [comment]
We can't use `403` for sure because as @sbespalov mentioned it would cause issues in the UI would be misleading to the user.

It looks like the only sane status code would be `409` :+1:  :)

**Comment by carlspring** [comment]
@fuss86 :
> > Each layout provider exposes a list of checksum formats that it supports.
> 
> I don't think we have it, @carlspring .

We actually support this via the [`AbstractLayoutProvider.getDigestAlgorithmSet()`](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/main/java/org/carlspring/strongbox/providers/layout/AbstractLayoutProvider.java#L75). (Thanks, @sbespalov!).

I've updated the description. Thanks!
:)

**Comment by Zernerus** [comment]
Hi, I'd like to try solving this issue, if it's still available!

**Comment by carlspring** [comment]
Hello again, @Zernerus !

Go for it! Feel free to ask any questions.

**Comment by atul46** [comment]
i'm interested in contributing to this issue.

**Comment by adbjo** [comment]
Hello! We are a group of CS students interested in solving this issue. Should be done by friday (28/2).
@carlspring

**Comment by carlspring** [comment]
@adbjo,

Feel free to pick this upand to join our [chat channel](https://chat.carlspring.org/), where you can find some more details on what sort of tasks you could help out with.

**Comment by tushar-corbic** [comment]
Hi, I'd like to try solving this issue.
