### ISSUE TITLE
Expose logging configuration properties for s-w-i-t

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1412]
# Task Description
Currently there is no way to enable debug logging for s-w-i-t. 

# Tasks

The following tasks will need to be carried out:
* [x] Expose `logging.debug` property as `STRONGBOX_DEBUG` environment variable
* [x] Expose `logging.console.enabled` property as `STRONGBOX_LOG_CONSOLE_ENABLED` environment variable
* [x] Expose `logging.file.enabled` property as `STRONGBOX_LOG_FILE_ENABLED` environment variable

# Task Relationships

This task:
* Relates to: SB-1400

**Comment by steve-todorov** [comment]
@sbespalov I was thinking that we should probably add a warning comments over these environment variables both in `strongbox/strongbox` and `strongbox/strongbox-web-integraion-tests`. The comment should mention that changing these will require changes in the opposite project and the pipeline code. If we ever decide to change this - it will for sure break everything down the line so it would be good to have it in mind. Maybe something like this would  be enough:

```
/** 
 * Changes to this env variable must also be applied to [strongbox/strongbox || strongbox/strongbox-web-integration-tests] and possibly the pipeline. 
 * Please ping us in the main channel to confirm.
 */
```
