### ISSUE TITLE
Get rid of ArtifactManagementServiceImplTest#setArtifactsTimestampAndRedeploy

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1443]
# Task Description
Currently there is workaround method `ArtifactManagementServiceImplTest#setArtifactsTimestampAndRedeploy` which targets to make SNAPSHOT timestamps suit for `MavenRepositoryFeatures.removeTimestampedSnapshots` logic when SNAPSHOT versions should be removed by date. We need to rework the `MavenRepositoryFeatures.removeTimestampedSnapshots` parameters to be able to pass a date as parameter when removing SNAPSHOT versions older then specified amount of days.

# Tasks

The following tasks will need to be carried out:
* [ ] There should be a new `MavenRepositoryFeatures` method 
```
    public void removeTimestampedSnapshots(String storageId,
                                           String repositoryId,
                                           String artifactPath,
                                           int numberToKeep,
                                           Date keepDate)
```
this method should be called by original `removeTimestampedSnapshots` with `keepPeriod` parameter.
* [ ] Use `removeTimestampedSnapshots` method with `Date keepDate` parameter within `testRemoveTimestampedSnapshotsWithPreviousDate` test case
* [ ] Drop the `setArtifactsTimestampAndRedeploy` method from `ArtifactManagementServiceImplTest`

# Task Relationships

This task:
* Relates to: [PR #1434](https://github.com/strongbox/strongbox/pull/1434)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by us3rna** [comment]
Can I work on this issue?

**Comment by carlspring** [comment]
Hi @us3rna ,

If course! Is the description clear enough? Please, feel free to join our [chat channel](https://chat.carlspring.org/) for more help.

Martin

**Comment by pyashwanthkumar** [comment]
@Daniel-Jacob 
are you still working on this?

**Comment by pyashwanthkumar** [comment]
@carlspring @sbespalov 
Can I start working on this issue?

**Comment by carlspring** [comment]
Hi @pyashwanthkumar ,

Yes, please!

**Comment by pyashwanthkumar** [comment]
I almost finished development on the issue. There is a small part which needs fixing i.e promoting backward compatibility of our java method. Currently, I am working on that. Will update once its done.

**Comment by pyashwanthkumar** [comment]
Hi @carlspring @sbespalov 

`removeTimestampedSnapshots` with keepPeriod parameter should call the new `removeTimestampedSnapshots` with keepDate parameter. How do we set this date? Should we derive it from keepPeriod?

**Comment by carlspring** [comment]
@pyashwanthkumar : Did you open a pull request for this?
