### ISSUE TITLE
Implement support for the npm login command

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1480]
# Task Description

We would like to add support for the `npm adduser` command. (This is the same as `npm login`).

# Tasks

The following tasks will need to be carried out:
* [x] Investigate what exactly needs to be done to implement this.
* [x] Implement the support for the command (in the [`NpmController`](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java)).
* [x] Add a new test case to the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/).

# Useful Links

* [NPM: `npm adduser`](https://docs.npmjs.com/cli/adduser)
* [NPM: `npm adduser` (sources)](https://github.com/npm/cli/blob/latest/lib/adduser.js)
* [How does `npm login` work underneath the covers?](https://stackoverflow.com/questions/58347926/how-does-npm-login-npm-adduser-work-underneath-the-covers)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by LeifBrooks** [comment]
cool if I take this?

**Comment by carlspring** [comment]
Sure! Go for it! :)

**Comment by steve-todorov** [comment]
@LeifBrooks in case you get error 400 - you might need to checkout #1481. I'm not sure if it won't interfere with this task. :)

**Comment by LeifBrooks** [comment]
@steve-todorov thanks I'll check it out

**Comment by LeifBrooks** [comment]
This is in progress. I've wired up the endpoint, but I might have a question or two for you guys in a bit.

**Comment by carlspring** [comment]
Shoot! :)

**Comment by LeifBrooks** [comment]
[Uploading adduser_twice_verdaccio.txt…]()

**Comment by LeifBrooks** [comment]
As @sbespalov suggested in chat, I will:
1. Verify the npm user credentials in the NpmController, similar to how it is done in LoginController
2. Return success message that the user was created, or error message that user is not a strongbox user

**Comment by LeifBrooks** [comment]
@sbespalov Ok so I ran into an issue, and I would like some design advice, if possible.

In my NpmLoginAuthenticationSupplier.java:

`@override
public boolean supports(@nonnull HttpServletRequest request)
{
this.npmUser = deserializeNpmUser(request);

    return "PUT".equalsIgnoreCase(request.getMethod()) &&
            request.getContentType()!=null &&
            request.getContentType().contains(MediaType.APPLICATION_JSON_VALUE) &&
            isValidNpmUser(this.npmUser);
}`

This causes a lot of issues, because the HttpServletRequest can only have the input stream read from once, which causes it to be null for other suppliers. I'm trying to validate that the npm adduser datastructure is being sent, before accepting it with the npm supplier.

Should we add a HttpServletRequestWrapper like is mentioned here: [https://stackoverflow.com/questions/34804205/how-can-i-read-request-body-multiple-times-in-spring-handlermethodargumentresol](url) 


Or should I not validate this way, and just validate with the URI?

**Comment by LeifBrooks** [comment]
@sbespalov, actually I think just looking for "/-/user/org.couchdb.user:" in the URI might be a better approach. We only care about requests with that.

**Comment by carlspring** [comment]
Would it be possible to add a test case to the `strongbox-web-integration-tests` for this as well? :)

**Comment by steve-todorov** [comment]
Looks like this issue did not auto close so I'm doing it now :)
