### ISSUE TITLE
npm install @angular/core is broken and will return 400 bad request

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1481]
# Bug Description

Issuing the command below will return an HTTP 400:

```
npm install @angular/core
```

# Expected Behavior

The command succeeds.

# Tasks

* [ ] Investigate the bug and provide steps to reproduce it.
* [ ] Fix the bug.
* [ ] Create a test case for this under the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project.

# Useful Information

The code for the NPM layout provider is split across two projects:
* [`strongbox-npm-metadata`](https://github.com/strongbox/strongbox-npm-metadata/) : This contains all the code related to the NPM metadata.
* The [`strongbox-web-core`](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/) contains the Spring controller for this called [NpmArtifactController](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java).
* In addition, there is a separate project called [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) where all the integration tests for various build tools reside.
* You can checkout the [strongbox-examples](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm#prepare-project-workspace) project which shows how you can configure NPM to use Strongbox. Use `http://localhost:48080/storages/storage-npm/npmjs` instead the mentioned repository in the example.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by shubhamivane** [comment]
Can I work on this issue?

**Comment by carlspring** [comment]
I believe @LeifBrooks and @pyashwanthkumar have already expressed an interest to look into it, but if you would still like to investigate, feel free to do so and report back your findings. Otherwise, you can have a look around our issue tracker for something else to pick up.

Please, feel free to join our [chat channel](https://chat.carlspring.org/).

**Comment by pyashwanthkumar** [comment]
Some findings on this issue - 

get request is being made with the following uri `/storages/storage-npm/npmjs/@angular/core/-/core-9.0.0-next.8.tgz`

the error is cause of `<next.8>` does not match format `(\d+)\.(\d+)(?:\.)?(\d*)(\.|-|\+)?([0-9A-Za-z-.]*)?`

It's a semantic version format issue

**Comment by sbespalov** [comment]
@pyashwanthkumar the version seems should be `9.0.0-next.8` but not just `next.8`, so probably we got wrong version somewhere in our code.

**Comment by sbespalov** [comment]
the problem can be related with Spring MVC mapping in `NpmArtifactController#downloadPackageWithScope`, so in case of version contains `-` it cuts the version and it starts from last `-` character. 

if this assumption is true then we can try to use regular expressions within Spring MVC mapping, something similar with `NugetArtifactController.searchPackages`

**Comment by carlspring** [comment]
I would like to suggest that you create a thorough list of valid npm package names (including their versions) and add a test case that tries to resolve them. This way we can make sure we don't break it again in the future.

**Comment by steve-todorov** [comment]
That's a good idea. I actually found this issue by accident while doing a plain `npm install @angular/core`. It doesn't specify a version but will try to get the latest version which in this particular case happens to be `9.0.0-next.8`. :)
