### ISSUE TITLE
Minor package refactoring and cleanup under the strongbox-maven-metadata-api module

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1482]
# Task Description

The [`strongbox-maven-metadata-api`](https://github.com/strongbox/strongbox/tree/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api) module requires some minor package refactoring.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new package called `org.carlspring.strongbox.storage.metadata.maven` under the [`strongbox-maven-metadata-api`](https://github.com/strongbox/strongbox/tree/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api) module.
* [ ] Move all the sub-packages and direct classes in [`strongbox-maven-metadata-api`](https://github.com/strongbox/strongbox/tree/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-maven-metadata-api) from `org.carlspring.strongbox.storage.metadata` to `org.carlspring.strongbox.storage.metadata.maven`.
* [ ] Move the `org.carlspring.strongbox.io.filters.ArtifactVersionDirectoryFilter` under `org.carlspring.strongbox.maven.io.filters.ArtifactVersionDirectoryFilter`.
* [ ] Make sure this is applied to to the test code.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by leonmak** [comment]
I would like to try this

**Comment by carlspring** [comment]
Okay! Go for it! :)
