### ISSUE TITLE
Improve TempDirBooter and cleanup tmp related code

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1487]
# Task Description

We need to improve [TempDirBooter](https://github.com/strongbox/strongbox/blob/master/strongbox-commons/src/main/java/org/carlspring/strongbox/booters/TempDirBooter.java) and generally fix global `tmp` related code. 

# Tasks

The following tasks will need to be carried out:
* [ ]  we should throw an exception in [TempDirBooter](https://github.com/strongbox/strongbox/blob/master/strongbox-commons/src/main/java/org/carlspring/strongbox/booters/TempDirBooter.java)  if `System.getProperty("java.io.tmpdir") == null` (is it even possible ?)
* [ ] `org.carlspring.strongbox.booters.TempDirBooter#createTempDir` should be private 
* [ ] we should not use defaults as `Paths.get(propertiesBooter.getVaultDirectory(), "tmp")` - `java.io.tmpdir` has to be specified
* [ ] `java.io.tmpdir` creation should be locked similarly to https://github.com/strongbox/strongbox/issues/1457 (see related task description) 
* [ ] `org.carlspring.strongbox.booters.PropertiesBooter#tempDirectory` should be dropped as it is not used almost anywhere
* [ ] ```
if (System.getProperty("java.io.tmpdir") == null)
        {
            System.setProperty("java.io.tmpdir", getVaultDirectory() + "/tmp");
 }
``` should be dropped from `org.carlspring.strongbox.booters.PropertiesBooter` - we shouldn't set up this value in Runtime.

# Task Relationships

This task:
* Is a follow-up of: https://github.com/strongbox/strongbox/issues/1457

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@fuss86,

Thanks for creating this follow-up task!

@TheKeySpammer ,

Would you like to look into this as well?

**Comment by TheKeySpammer** [comment]
Working on it.

**Comment by ykabusalah** [comment]
Can I try this?

**Comment by carlspring** [comment]
@ykabusalah ,

@TheKeySpammer is already looking into this.

**Comment by TheKeySpammer** [comment]
Regarding **System.getProperty("java.io.tmpdir")**
After doing research about tmp directory and how it is handled by java I came to following conclusion.

- Initially the System property java.io.tmpdir is set by JDK by calling underlying get_temp_directory() system call. Temp directories are handled by Operating System, therefore temp directory is always initially available to java. But, this system property can be changed or unset by another piece of java code therefore java.io.tmpdir can return null. So we should throw an exception for null tmpdir as a precautionary method.

**Comment by TheKeySpammer** [comment]
@fuss86 Should I commit each task individually or complete all tasks and commit once and create a pull request.

**Comment by TheKeySpammer** [comment]
Regrading task
org.carlspring.strongbox.booters.PropertiesBooter#tempDirectory should be dropped as it is not used almost anywhere

tempDirectory is used in org.carlspring.strongbox.controllers.layout.maven.MavenArtifactControllerTest to build artifactdeployer
at line 828. How should we refactor it?

**Comment by fuss86** [comment]
> `tempDirectory` is used in `org.carlspring.strongbox.controllers.layout.maven.MavenArtifactControllerTest` to build artifactdeployer
> at line 828. How should we refactor it?

use property value under `java.io.tmpdir` key

**Comment by bono007** [comment]
Just a heads up that this has overlap w/ #1169 . However, this will go in before mine as we are leaving 1169 open and adding more functionality to it. I will keep the changes made here in mind.

**Comment by TheKeySpammer** [comment]
A question regarding task #1, throwing an exception in TempDirBooter Sytem.getProperty("java.io.tmpdir") == null. How should we handle the exception,

- Should we catch it in createTempDir and create a new tempDir in StrongboxHome?

- Or should we throw it out of the createTempDir function to be handled elsewhere?

**Comment by fuss86** [comment]
If `Sytem.getProperty("java.io.tmpdir") == null` then we should not allow the application to start.

**Comment by TheKeySpammer** [comment]
I have been trying to figure out a better way to solve this null value problem. ```System.getProperty("java.io.tmpdir") == null``` then the application should not start. If this is the case then there is no purpose of TempDirBooter, since we don't want setting up temp directory during run time. Since I am new to Spring Framework, I have been experimenting with quite a few different ideas. Here is what I think we should do:

- Remove TempDirBooter class.
- Add a tempDirectory property to PropertiesBooter class with annotation ```@Value("${java.io.tmpdir}")```. This way if the java.io.tmpdir is null, the application will fail to start.

Please review this suggestion, as I am pretty confused about how we should refactor this code.

**Comment by sbespalov** [comment]
@fuss86 @TheKeySpammer sorry for late response but this task seems a bit obsolete. We already have `LayoutFileSystem.getTempPath()` so we dont need this `TempDirBooter` and it should be dropped.
Regarding `MavenArtifactControllerTest` it was reworked within #954 and there is no direct temp dir usage there.

**Comment by carlspring** [comment]
Okay, in this case, let's close this.

@TheKeySpammer : Apologies for having wasted your time with this task!

**Comment by fuss86** [comment]
Shouldn't we drop `TempDirBooter` ? @carlspring  ?

**Comment by fuss86** [comment]
@carlspring if we don't need `<systemProperty>java.io.tmpdir=%STRONGBOX_HOME%/tmp</systemProperty>` in the `strongbox-distribution` then I think we should drop `TempDirBooter` and all code related with `java.io.tmpdir`
