### ISSUE TITLE
Upgrade org.hibernate:hibernate-validator to version 5.2.5.Final, 5.3.6.Final, 5.4.2.Final or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1493]
# Task Description

Our current version of `hibernate-validator` is prone to arbitrary code execution, as reported [here](https://snyk.io/vuln/SNYK-JAVA-ORGHIBERNATE-451605).

We need to upgrade this in [strongbox-parent](https://github.com/strongbox/strongbox-parent/) to a newer version and validate that things still work. Please, pick the latest version that still works. If none of them are compatible, please apply the necessary changes to fix things.

# Tasks

The following tasks will need to be carried out:
* [ ] Fork the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) and upgrade the version there. If this is a transitive dependency, check where it's coming from and either add an exclusion for it and explicitly override it, or do whatever else needs to be done.
* [ ] Check, if any code changes are required apply any fixes that might be needed.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by PrzemyslawCieslik** [comment]
somebody doing this or can i take it?

**Comment by carlspring** [comment]
Hi @PrzemyslawCieslik ,

Please, feel free to pick it up and to join our [chat channel](https://chat.carlspring.org/)! :)

**Comment by bsemexan** [comment]
The hibernate validator is <version.hibernate.validator>6.0.7.Final</version.hibernate.validator>
in the repo i forked. Does ti need to be tested or something?

**Comment by carlspring** [comment]
@bsemexan ,

I seem to have forgotten to add an "acceptance test" section in the description. Could you please have a look now?

**Comment by bsemexan** [comment]
When I have tried to build following this 
https://strongbox.github.io/developer-guide/building-the-code.html

It's failing at this part

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:59 min
[INFO] Finished at: 2019-10-08T11:42:20-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project strongbox-ldap-authentication-provider: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/berr/strongbox/strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :strongbox-ldap-authentication-provider

**Comment by carlspring** [comment]
This issue is still not properly resolved. Something is transitively bringing `org.hibernate:hibernate-validator`. The upgrade that @PrzemyslawCieslik did, defines the newest version, which seems to be under the following coordinates (note the change in the `groupId`):
```
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${version.hibernate.validator}</version>
            </dependency>
```

@PrzemyslawCieslik , @mslowiak : Would either of you like to pick this up? :)

**Comment by mslowiak** [comment]
I can look on it tomorrow :)

**Comment by carlspring** [comment]
Thanks, @mslowiak ! I've assigned it to you! :)

**Comment by carlspring** [comment]
Closing this again as a false-positive reported by snyk.io.

Apologies, guys, but it did look real, as it kept being reported.

@mslowiak : Thanks for having another look!
