### ISSUE TITLE
Module restructuring

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1496]
# Task Description

We are planning to do a refactoring that will:
* Bring the [`strongbox-parent`](http://github.com/strongbox/strongbox/) back under the [`strongbox`](http://github.com/strongbox/strongbox/) project.
* Bring the [`strongbox-npm-metadata`](http://github.com/strongbox/strongbox-npm-metadata/)  under the [`strongbox`](http://github.com/strongbox/strongbox/) project.

# Tasks

The following tasks will need to be carried out:
* [ ] Merge all outstanding pull requests in the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project and archive it.
* [ ] Merge all outstanding pull requests in the [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata/) project and archive it.
* [ ] Bring the [`strongbox-parent`](http://github.com/strongbox/strongbox/) back under the [`strongbox`](http://github.com/strongbox/strongbox/) project.
* [ ] Bring the [`strongbox-npm-metadata`](http://github.com/strongbox/strongbox-npm-metadata/)  under the [`strongbox`](http://github.com/strongbox/strongbox/) project.

# Task Relationships

This task:
* Depends on: #1456 ( strongbox/strongbox-parent#40,  #1485 , strongbox/strongbox-npm-metadata#11 )
* Relates to: #1130
