### ISSUE TITLE
 Make sure that no passwords are shown in the logs 

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1511]
# Task Description

When a user authenticates, the logs may contain his hashed password. We should make sure that we don't leak any credential information in the logs (even hashed passwords).

# Tasks

The following tasks will need to be carried out:
* [ ] Enumerate all possible classes that uses credentials / passwords  
* [ ] Make sure their `toString` methods do not contain sensitive data
* [ ] Make sure  credentials / passwords are not logged anywhere

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sairamvudatha** [comment]
@fuss86 Could I take this up?

**Comment by n00ner** [comment]
I want to help

**Comment by carlspring** [comment]
Feel free to dig in! :)

**Comment by bono007** [comment]
I would recommend doing this for all PII. If we are already going to be scouring logs for creds - it woulld be worth doing that as well. Could be done in a follow on ticket as well.

**Comment by carlspring** [comment]
I'm assuming you're referring to "personally identifiable information"?

If so, I believe the only information that we keep a record of is the username/e-mail, so I'm not quite sure what else we could sanitize and restrict.

**Comment by bono007** [comment]
Yep. Email would be one.

**Comment by theparselmouth** [comment]
Has someone taken this up already ?

**Comment by carlspring** [comment]
@theparselmouth , @n00ner said they'd look into it, but as we haven't seen a pull request yet, I'd say it's probably up for grabs, so you can have a go at it, if you like.

**Comment by n00ner** [comment]
@theparselmouth, try it =) 

I just studying and work slowly.

**Comment by RutgerDOW** [comment]
I'm participating at hacktoberfest and choose this issue to start working on.

**Comment by carlspring** [comment]
Hi @RutgerDOW ,

Feel free to look into it! Thanks for offering to help! :)

(As we haven't heard back from @n00ner , or seen a pull request, I believe it's safe to proceed).

**Comment by RutgerDOW** [comment]
- Enumerate all possible classes that uses credentials / passwords

Do you need tooling for it, or is manually search and output to enumeration satisfying? In last case, how will it be maintained?

- Make sure their toString methods do not contain sensitive data

Is a search and delete in the logged data the solution, or is must all password object or string be omitted from methods of toString object in underlying classes?

**Comment by carlspring** [comment]
I think you can start by ommitting things from the `toString` method and work your way through. Deleting things through the logger might be quite an undertaking...

**Comment by steve-todorov** [comment]
@carlspring / @fuss86 / @sbespalov in addition and as a fallback option, maybe we could try to configure `logback` to `mask` certain messages using [`replace`](http://logback.qos.ch/manual/layouts.html#replace) ([example](https://stackoverflow.com/questions/4607877/mask-passwords-with-logback))?

**Comment by fuss86** [comment]
@steve-todorov I think it might be hard to prepare a regex for such purpose. We can't predict it I think.

**Comment by deepank120896** [comment]
@carlspring
@fuss86
@sbespalov
@steve-todorov
Can I look into this?
Just a beginner, willing to learn about code

**Comment by steve-todorov** [comment]
Hi @deepank120896 - feel free to pick it up. You can also join our [chat](https://chat.carlspring.org/) if you have more questions. :)

**Comment by VishnuLakkimsetty** [comment]
Hi @deepank120896 - Are you contributing to this issue. If not I'm interested in contributing to this issue

**Comment by deepank120896** [comment]
@VishnuLakkimsetty Yes I am working on it

**Comment by Syntax753** [comment]
@deepank120896 Are you still working on this?

I've done a quick initial investigation and happy to continue. These would be the first files to look into:
```console
find . -type f -name '*.java' | grep -v "/test" | xargs grep -l password | xargs grep -l toString                                              
./strongbox-rest-client/src/main/java/org/carlspring/strongbox/client/RestClient.java
./strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/dto/UserDto.java
./strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/userdetails/SpringSecurityUser.java
./strongbox-security/strongbox-user-management/src/main/java/org/carlspring/strongbox/users/domain/UserData.java
./strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/password/PasswordAuthenticationProvider.java
./strongbox-security/strongbox-authentication-providers/strongbox-default-authentication-provider/src/main/java/org/carlspring/strongbox/authentication/api/CacheManagerAuthenticationCache.java
./strongbox-storage/strongbox-storage-core/src/main/java/org/carlspring/strongbox/configuration/MutableProxyConfiguration.java
./strongbox-client/src/main/java/org/carlspring/strongbox/client/ArtifactClient.java
```

**Comment by steve-todorov** [comment]
@Syntax753 feel free to pick this up if you're still interested and open a PR :)

**Comment by DSkilton** [comment]
Hiya. Is this issue still open, could I have a go at it?

**Comment by Syntax753** [comment]
Gosh I forgot about that - I didn't make progress so +1 from my side :)

**Comment by colinldbd** [comment]
Hi, I'm a contributor and I see this is a good first issue. Can you assign this issue to me so I can work on it?

Many thanks!

**Comment by carlspring** [comment]
@colinldbd : This project is on hold.

**Comment by khushbukareliya07** [comment]
Hi @carlspring - I would recommend adding an appropriate label for the status.

**Comment by carlspring** [comment]
@khushbukareliya07 : The point being? I assume you've read my last comment.
