### ISSUE TITLE
Implement strict checksum validation option for Repository

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1512]
# Task Description
We need to have an  `strictChecksum` option for `Repository` which will prevent of uploading artifacts with broken checksum. For now we have only `ERROR` log message in case of invalid checksum _(see `ArtifactManagementService.validateUploadedChecksumAgainstCache`)_. 

This should be configurable.

# Tasks

The following tasks will need to be carried out:
* [ ] Add `strictChecksum` property of type `boolean` for `org.carlspring.strongbox.storage.repository.Repository` interface
* [] Support `strictChecksum` option for `repositories` items in `strongbox.yaml`
* [ ] Throw `ArtifactStorageException` in case of `matchesChecksum` returns `false` and `Repository.isStrictChecksum() == true` within `ArtifactManagementService#validateUploadedChecksumAgainstCache`
* [ ] Provide Unit Tests covering new feature

# Useful Links

* [strongbox.yaml](https://strongbox.github.io/user-guide/configuration-files/strongbox-yaml.html)
* [Writing tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by tomasdaneshjo** [comment]
Hey, could I start working on this as my first issue?

**Comment by carlspring** [comment]
Hi!

Feel free to dig in! :)

**Comment by erikgajdos1997** [comment]
Hi, can I try to make this?

**Comment by carlspring** [comment]
Dig into it and have fun, @newarcher36 ! :)

**Comment by newarcher36** [comment]
Hi @sbespalov Just a quick question, which value do I set by default in the property strictChecksum in strongbox.yaml? Thanks

**Comment by sbespalov** [comment]
@newarcher36 let it be `true` by default

**Comment by carlspring** [comment]
@newarcher36 ,

Do you have a pull request for this in the `strongbox` project as well?

**Comment by newarcher36** [comment]
Hi @carlspring , yes I am proceeding to upload the PR for this issue

**Comment by carlspring** [comment]
> @newarcher36 let it be `true` by default

@sbespalov : I've just realized that perhaps this won't be a great idea, if it's set to `true` by default. For Maven repositories, it's fine and perhaps we can default to it being `true` there, but how about for Nuget, NPM and PyPi ones...? Does nuget.org expose checksums as downloadable files by default? Does npmjs.org? How about PyPi...?

@newarcher36 : Perhaps you could check the questions above, so we could have a clearer idea of how to do it? I think that for now, it seems to me that this should not be the default behaviour.

**Comment by steve-todorov** [comment]
This task is now up for grabs.
