### ISSUE TITLE
Rework `RepositoryManagementStrategy` repository initialization

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1515]
# Task Description
We are currently using the same `RepositoryManagementStrategy` when creating a new repository and when loading existing repositories from the configuration within application startup. This approach is wrong because all changes made for repository configuration (cron jobs, etc) will be overwritten on every application restart.

Within this task we need to use `RepositoryManagementStrategy` only once for each repository in following cases: 
- when we first time load repository form configuration 
- when we create new repository with API

# Tasks

The following tasks will need to be carried out:
* [ ] Confirm that `RepositoryManagementStrategy` behavior described above is relevant
* [ ] Suggest and approve solution
* [ ] Rework `RepositoryManagementStrategy` according approved solution
* [ ] Provide Unit Test with cases described within issue

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to:

# Useful Links

* [Repositories](https://strongbox.github.io/knowledge-base/repositories.html)
* [Layout Providers](https://strongbox.github.io/knowledge-base/layout-providers.html)
* [Writing tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by har-vy** [comment]
Hi @carlspring can I work on this? This is my first issue.

**Comment by carlspring** [comment]
Hi,

Feel free to look into it and to submit a pull request! :)

**Comment by har-vy** [comment]
@sbespalov I have started looking into the code and might need your help to understand it. I went through how repositories are being created and fetched from the same RepositoryManagementStrategy. But i couldn't understand how configurations for  are being overwritten during application startup.

**Comment by user062** [comment]
Hi,
It appears to me that @har-vy is not working on this.
if this is so, and if nobody minds,may i work on it?

**Comment by carlspring** [comment]
Hi!
Yes, please!

**Comment by GAlexMES** [comment]
I will hava a look into this.

**Comment by carlspring** [comment]
Okay, great! Good luck with it! :)

**Comment by zhongjis** [comment]
I am looking into this issue. I want to make sure no one else is working on this.

**Comment by carlspring** [comment]
Hi @zhongjis ,

Thanks for offering to help! Please, feel free to proceed!

**Comment by zhongjis** [comment]
Thank you @carlspring 
So I dug into it a bit and here are some updates I have for you guys. It is my first time doing it so I believe it is better for me to get any input possible before/during file modifying (for good). 

- [x] Confirm that RepositoryManagementStrategy behavior described above is relevant
1. I traced the behavior back to YamlFileManager.java'. 
2. The YamlFileManager.store() method will overwrite the existing configuration due to the YamlMapper is a java set. Looks like (This is my current thought, might be wrong but please let me know)
3. My detailed tracing roadmap: 
NpmRepositoryManagementStrategy -> 
AbstractRepositoryManagementStrategy -> 
ConfigurationManagementServiceImpl.doInit(), setConfiguration(), modifyInlock() -> 
configurationFileManager -> 
YamlFileManager.store() ->
yamlMapper.writeValue()
- [x] Suggest and approve solution
1. override YamlMapper.writeValue() to make sure configuration file persist if exist.
- [ ] Rework RepositoryManagementStrategy according approved solution
- [ ] Provide Unit Test with cases described within issue

**Comment by sbespalov** [comment]
@zhongjis thanks for your interest on this issue. Regarding your suggesion I would say that it goes a bit wrong direction. We shouldn't fix it in `YamlFileManager` because it used not only for `AbstractRepositoryManagementStrategy` and changes will affect other classes as well. The right solution will be something like we already have in [StoragesConfigurationController.java#L271](https://github.com/strongbox/strongbox/blob/master/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java#L271). So we probably should move this logic into `AbstractRepositoryManagementStrategy` so it will work same way for controller and for `StorageBooter`.

**Comment by zhongjis** [comment]
@sbespalov got it. will be looking into it

**Comment by zhongjis** [comment]
Thank you @carlspring 
So I dug into it a bit and here are some updates I have for you guys. It is my first time doing it so I believe it is better for me to get any input possible before/during file modifying (for good). 

- [ ] Confirm that RepositoryManagementStrategy behavior described above is relevant (in progress)
- [ ] Suggest and approve solution
- [ ] Rework RepositoryManagementStrategy according approved solution
- [ ] Provide Unit Test with cases described within issue

Update - December 28, 2019:
- Based on your (@sbespalov) feedback, I rechecked the code and found this under `ConfigurationManagementServiceImpl`'s `doInit()` (line 81 - line 88).

```
MutableConfiguration configuration;
if (!configurationFileManager.read()) {
	// if cannot (read the file, which means the file does not exist)
    configuration = configurationFileManager.read(); // null
} else {
    configuration = configurationFileManager.read(); // @Value("#{@propertiesPathResolver.resolve('strongbox.config.file','etc/conf/strongbox.yaml')}")
}
setConfiguration(configuration);
setRepositoryArtifactCoordinateValidators();
```

for the above code. I found two things confusing :
1. the in-method variable `configuration` also appears outside the method on line 68. I am wondering if this affacts anything
2. when the user make a change to the configuration file. Do the changes are made directly on `etc/conf/strongbox.yaml`? Or otherwise? 

And have a great holiday!

**Comment by sbespalov** [comment]
@zhongjis seems you should update your branch with latest master. The code in `ConfigurationManagementServiceImpl` is not like in your sample. Also it's not clear how your questions related with the task.

**Comment by zhongjis** [comment]
@sbespalov 

Sorry for the late reply and I am wondering if I got the issue wrong.

So basically, I want to check if the task here is:

Using **RepositoryManagementStrategy** when
- create a new repo -> stays the same
- load an existing repo from config -> first time loading an existing repo from config

**Comment by MuraliSRao** [comment]
Who is working on this issue now?

**Comment by carlspring** [comment]
Nobody in particular. Would you like to pick it up?

**Comment by MuraliSRao** [comment]
@carlspring  Thanks for your reply. Let me see whether I can make a progress.

**Comment by carlspring** [comment]
This task is now up for grabs.

**Comment by dreameral** [comment]
Can I work on this?

**Comment by ajitluhach** [comment]
Hi, if no one else is working on the issue, I'd like to take this up.
