### ISSUE TITLE
Create a new test for the deployment and resolution of large artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1518]
# Task Description

We need to add a test that tries to deploy a large artifact (2 GB) to each of the currently supported layout providers (Maven, NPM, NuGet, Raw) and then also resolve it.

The new tests should be added under the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/). There should be a new test each of sub-modules.

Please, note:
* Tthis cannot be done in the `strongbox-web-core` module, because the tests there are using restassured, which currently doesn't support large files (unless you'd like to fix this in restassured first and submit them a pull request for it :) ).
* This should be a relatively straight-forward task that's good for new-joiners, as it will help get a better understanding of how our integration tests work, as well as how we generate test artifacts.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a test for Maven.
* [ ] Create a test for NPM.
* [ ] Create a test for NuGet.
* [ ] Create a test for Raw.
* [ ] Make it possible to pass in a property that specifies the location for the artifact file that will be deployed. If the property is not null, do not generate the artifact; otherwise, generate the artifact file, (as can be seen in the rest of the tests). This might seem like a weird requirement, but it would help us with testing things on our CI infrastructure.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by dominusmars** [comment]
@carlspring can i try to test it ?

**Comment by wpater** [comment]
@dominusmars I am working on it.

**Comment by carlspring** [comment]
@dominusmars ,

Thanks for your interest! Feel free to join our [chat channel](https://chat.carlspring.org/) to find out what else you could help with!

**Comment by steve-todorov** [comment]
@wpater could you please let us know what's the state of this issue? You have created a draft PR - is it completed, is it ready for review?

**Comment by steve-todorov** [comment]
This task is now up for grabs! :)
