### ISSUE TITLE
Move the images for the Nuget (Visual Studio) example from the old wiki to the new one

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1521]
# Task Description

We have migrated our wiki from [the strongbox project](https://github.com/strongbox/strongbox/wiki) to [strongbox-docs](https://strongbox.github.io/) project. We appear to have some images still pointing to the old wiki and this prevents us from being able to shut down the old wiki, which is now obsolete and might be misleading people.

# Tasks

The following tasks will need to be carried out:
* [ ] Clone the docs from `git@github.com:strongbox/strongbox-docs` 
* [ ] Then move the images necessary images from `wiki/**` under `resources/images/nuget/` to `docs/assets/images` under the [`strongbox-docs`](https://github.com/strongbox/strongbox-docs/) repository. Make sure to preserve git history!
* [ ] Change the link for the images in the [hello-strongbox-nuget-visual-studio](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-nuget-visual-studio) to point to the new locations.
* [ ] Check if there are other images which have not been migrated and report/fix them.

# Useful Links

* [strongbox-docs](https://github.com/strongbox/strongbox-docs/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by JekRock** [comment]
Can I take this issue?

**Comment by carlspring** [comment]
Hi @JekRock ,

Feel free to look into it! Thanks for offering to help! :)

**Comment by JekRock** [comment]
Hi @carlspring ,

Glad to help!
I've made two pull request for this issue. Could you please check them out?

- [This](https://github.com/strongbox/strongbox-docs/pull/46) for copying images
- [This](https://github.com/strongbox/strongbox-examples/pull/16) for changing links for the images
