### ISSUE TITLE
Set up code coverage and quality analysis using Sonarqube

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1533]
# Task Description

This is the master task for setting up code coverage and quality analysis using Sonarqube.

# Tasks

The following tasks will need to be carried out:

**Code coverage tasks:**
* [ ] Get code coverage and code quality analysis to work with JaCoCo:
  * [ ] Get unit tests executed with the `maven-surefire-plugin` to produce JaCoCo coverage.
  * [ ] Get integration tests executed with the `maven-failsage-plugin` to produce JaCoCo coverage.
  * [ ] Merge the reports and publish them to Sonarqube.
* [ ] The code coverage and quality analysis should be done in a Maven profile and not be <activeByDefault/>.
* [ ] Code coverage in pull requests.
* [ ] PMD/CPD/Findbugs for code duplication and additional analysis.

**Apply this to the following projects:**
* [ ] [strongbox](https://github.com/strongbox/strongbox/)
* [ ] [strongbox-db](https://github.com/strongbox/strongbox-db/)
* [ ] [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by saratbeesa** [comment]
@carlspring , 

I checked the parent pom for strongbox project, jacoco configuration is already present in it. I tried to generate the jacoco coverage by building the project, but for some reason it is not getting generated. 

Due to these missing `.exec` files reporting fails to Codacy server , i think its hitting api.codacy.com service to log these metrics. 

I'm currently investigating why the jacoco files are not generated, by analysing the debug output of the build,. I found that the the default-test goal executed by maven doesn't contain the additional arguments that're specific to Jacoco agent. For some reason these parameters are not passed to the JVM that runs the tests. 

This ticket has not been updated for over a month now, is anyone still working on it ? Because I found the following tasks are already in place for strongbox repository atleast 

- Get unit tests executed with the maven-surefire-plugin to produce JaCoCo coverage.
-  Get integration tests executed with the maven-failsafe-plugin to produce JaCoCo coverage.
-  Merge the reports


Thanks, 
Sarat kumar Beesa.
