### ISSUE TITLE
Implement support for generating test artifacts with a specified size

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1534]
# Task Description

We need to be able to create test artifacts with a specified size.

This is the master task to help track things and the work should be done in the respective tasks listed below.

# Tasks

The following tasks will need to be carried out:
* [x] Implement support for generating test artifacts with a specified size for Maven ( #1535 )
* [x] Implement support for generating test artifacts with a specified size for NPM ( #1536 )
* [x] Implement support for generating test artifacts with a specified size for NuGet ( #1537 )
* [x] Implement support for generating test artifacts with a specified size for PyPi ( #1538 )
* [x] Implement support for generating test artifacts with a specified size for Raw ( #1540 )
* [x] Implement support for generating test artifacts with a specified size for RPM ( #1600 )

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by wpater** [comment]
Working on this one.

**Comment by carlspring** [comment]
Okay, thanks! I'll create the sub-tasks shortly. :)

**Comment by carlspring** [comment]
Thanks for your help, guys! :)
