### ISSUE TITLE
Implement support for generating test artifacts with a specified size for Maven

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1535]
# Task Description

We need to be able to create test artifacts with a specified size.

# Classes of Interest

* `org.carlspring.strongbox.artifact.generator.MavenArtifactGenerator`
* `org.carlspring.strongbox.testing.artifact.MavenTestArtifact`

# Tasks

The following tasks will need to be carried out:
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.artifact.generator.MavenArtifactGenerator`.
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.testing.artifact.MavenTestArtifact`.
* [ ] Add tests for this.

# Task Relationships

This task:
* Is a sub-task of: #1534 
* Relates to: #1536 , #1537 , #1538 , #1540

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
