### ISSUE TITLE
Implement support for generating test artifacts with a specified size for Npm

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1536]
# Task Description

We need to be able to create test artifacts with a specified size.

# Classes of Interest

* `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`
* `org.carlspring.strongbox.testing.artifact.NpmTestArtifact`

# Tasks

The following tasks will need to be carried out:
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`.
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.testing.artifact.NpmTestArtifact`.
* [ ] Add tests for this.

# Task Relationships

This task:
* Is a sub-task of: #1534 
* Relates to: #1535 , #1537 , #1538 , #1540 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by katsadim** [comment]
Hello, May I give it a try?

**Comment by wpater** [comment]
Hi, I am already on it. You can try with Raw or Nuget :).
