### ISSUE TITLE
Implement support for generating test artifacts with a specified size for Nuget

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1537]
# Task Description

We need to be able to create test artifacts with a specified size.

# Classes of Interest

* `org.carlspring.strongbox.artifact.generator.NugetArtifactGenerator`
* `org.carlspring.strongbox.testing.artifact.NugetTestArtifact`

# Tasks

The following tasks will need to be carried out:
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.artifact.generator.NugetArtifactGenerator`.
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.testing.artifact.NugetTestArtifact`.
* [ ] Add tests for this.

# Task Relationships

This task:
* Is a sub-task of: #1534 
* Relates to: #1535 , #1536 , #1538 , #1540 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by katsadim** [comment]
I would be interested in giving it a try

**Comment by carlspring** [comment]
Go for it!

**Comment by wpater** [comment]
@katsadim Are you working on it?

**Comment by carlspring** [comment]
@wpater : As we still haven't see a pull request for this, please, feel free to pick it up. Thank you! :)
