### ISSUE TITLE
Implement support for generating test artifacts with a specified size for Pypi

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1538]
# Task Description

We need to be able to create test artifacts with a specified size.

# Classes of Interest

* `org.carlspring.strongbox.artifact.generator.PypiArtifactGenerator`
* `org.carlspring.strongbox.testing.artifact.PypiTestArtifact`

# Tasks

The following tasks will need to be carried out:
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.artifact.generator.PypiArtifactGenerator`.
* [ ] Apply the necessary changes to the `org.carlspring.strongbox.testing.artifact.PypiTestArtifact`.
* [ ] Add tests for this.

# Task Relationships

This task:
* Is a sub-task of: #1534 
* Relates to: #1535 , #1536 , #1537, #1540

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by m-podhajski** [comment]
Hi, can I take this one?

**Comment by carlspring** [comment]
Hi!

Feel free to look into it! Thanks for offering to help! :)

**Comment by wpater** [comment]
@m-podhajski Are you working on it?

**Comment by m-podhajski** [comment]
yes, i am

**Comment by wpater** [comment]
@m-podhajski do you need help with that one?
