### ISSUE TITLE
Implement support for generating test artifacts with a specified size for Raw

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1540]
# Task Description

We need to be able to create test artifacts with a specified size.

# Classes of Interest

* `org.carlspring.strongbox.artifact.generator.RawArtifactGenerator`
* `org.carlspring.strongbox.testing.artifact.RawTestArtifact`

# Tasks

The following tasks will need to be carried out:
* [x] Apply the necessary changes to the `org.carlspring.strongbox.artifact.generator.RawArtifactGenerator`.
* [x] Apply the necessary changes to the `org.carlspring.strongbox.testing.artifact.RawTestArtifact`.
* [ ] Add tests for this.

# Task Relationships

This task:
* Is a sub-task of: #1534 
* Relates to: #1535 , #1536 , #1537, #1538 , #1582 
# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by JuWeber99** [comment]
Hey I whould like to get assigned so that I could give this a try.
Whould that be fine?

**Comment by carlspring** [comment]
Hi!

Sure, have a look at the existing pull request in the parent task (that was already merged) for the Maven task to see how this was implemented there. You'll have to do something similar.

**Comment by JuWeber99** [comment]
iĺl give it a shot... :)

**Comment by carlspring** [comment]
Okay, good luck! :)

**Comment by JuWeber99** [comment]
hey @carlspring i cant seem to get the build complete...
I followed the instructions and curled the settings.xml
anyway.. the code in the strongbox-cron-api in the class CronJobDuplicationCheckStrategiesRegistry.java 

maven gives me an error and says:
[26,109] unreported exception java.lang.InstantiationException; must be caught or declared to be thrown

I don't really wanna touch classes outside of my issue since I generally consider this confusing and not a good practice.
Do other ppl get this error too?

thanks for the help
Greetings!

**Comment by carlspring** [comment]
The build is passing under Linux, Windows and MacOS with JDK 8. We don't support newer versions.

**Comment by carlspring** [comment]
Feel free to join our [chat channel](https://chat.carlspring.org/) for more help.

**Comment by JuWeber99** [comment]
hey @carlspring its fine now i just built it with docker ;)

**Comment by carlspring** [comment]
Okay! Great!

**Comment by wpater** [comment]
@JuWeber99 are you working on it?

**Comment by JuWeber99** [comment]
hey I saw u alrdy are doing it right now. its fine since I have no time right now ;)
