### ISSUE TITLE
Implement support for the npm unpublish command

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1543]
# Task Description

Generally, unpublishing is poor practice, as it can break things for other projects, if they are already depending on the version of the artifact that is being remove. However, there are sometimes valid reasons to want to do so (for example, accidentally leaked credentials, or other sensitive data). Therefore, we would like to add support for the `npm unpublish` command.

For NPM repositories, we need to add a new configuration option to allow the unpublishing of artifacts. By default, this should be disabled for release repositories and only enabled for snapshot ones, (as the artifacts in them should be discardable at any time anyways).

The command should remove the files from the file system, as well as from the database.

# Tasks

The following tasks will need to be carried out:
* [ ] Define a `allowsUnpublishing` option for NPM repository configurations.
* [ ] Implement support for removing the files from the file system and database.
* [ ] Implement the `unpublish` commands: 
   * [ ] Unpublish a single version
   * [ ] Unpublish the entire package (when doing an `npm unpublish --force ...`)
* [ ] Update the [documentation](https://strongbox.github.io/developer-guide/layout-providers/npm-layout-provider.html).

# Useful Links

* [`npm unpublish`](https://docs.npmjs.com/cli/unpublish)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @sbespalov
  * @carlspring
  * @fuss86
  * @steve-todorov

**Comment by Bremys** [comment]
I would like to start working on this.

**Comment by carlspring** [comment]
Okay! Please, proceed! :)

**Comment by Bremys** [comment]
@carlspring There are two unpublish commands, one which unpublishes a single version and one which unpublishes the entire package (this one must have --force).
Do we need to support both?

**Comment by carlspring** [comment]
Yes, we do.

**Comment by carlspring** [comment]
@Bremys : How are things going?

**Comment by PrzemyslawCieslik** [comment]
Can I take it or somebody doing this?

**Comment by carlspring** [comment]
Hi @PrzemyslawCieslik  ,

Feel free to look into it! Thanks for offering to help! :)

**Comment by mpoznyak** [comment]
I will look into it
