### ISSUE TITLE
Implement support for pip search

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1546]
# Task Description

We need to implement support for the `pip sarch` command.

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate how the command works.
* [ ] Collect some sample traffic and attach it here.
* [ ] Implement the functionality.
* [ ] Add a test the the [strongbox-web-integration-tests]().
* [ ] Update the documentation to reflect that this command is supported.

# Task Relationships

This task:
* Is a sub-task of: #807
* Depends on: #810, #811, #816

# Useful Links

* [`pip search`](https://pip.pypa.io/en/stable/reference/pip_search/).
* [Finding packages to use](https://realpython.com/what-is-pip/#finding-packages-to-use)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by cvaram96** [comment]
Can I contribute on this task

**Comment by carlspring** [comment]
Hi @cvaram96!

Thanks for offering to help! I think it's too early for this task to be implemented! Feel free to join 
our [chat channel](https://chat.carlspring.org/), if you'd like to find out what other tasks you could help with.
