### ISSUE TITLE
Upgrade Spring Boot + Spring Security

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1552]
# Task Description

We need to upgrade to the latest versions of Spring Boot and Spring Security.

# Tasks

The following tasks will need to be carried out:
* [ ] Upgrade Spring Boot.
* [ ] Upgrade Spring Security.
* [ ] Apply any necessary refactoring.

# Task Relationships

This task:
* Relates to: spring-projects/spring-security/pull/7025

# Help

May God be with you! :)

**Comment by sbespalov** [comment]
Spring Security: v 5.2.0.RELEASE

**Comment by carlspring** [comment]
@sbespalov ,

Do you know what things will need to be refactored, once we've upgraded to the newest version of Spring Security? Could you add a list to the task, please? Thanks!

**Comment by sbespalov** [comment]
@carlspring tasks updated

**Comment by soapdogg** [comment]
Hi, 

I'm new to contributing and would love to work on this refactoring task. Thanks!

**Comment by carlspring** [comment]
@soapdogg (and anyone else for this matter),

Please, only pick this task, if you have experience with Spring Boot and Spring Security.

I would also like to invite you to join our [chat channel](https://chat.carlspring.org/) where you can find more details regarding what other tasks you might be able to help with.
