### ISSUE TITLE
Remove the maven-war-plugin from any pom.xml files that might be using it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1562]
# Task Description

We are no longer producing a `war` file, since we've now migrated to Spring Boot. The [strongbox-parent](https://github.com/strongbox/strongbox-parent/) still has the settings for the `maven-war-plugin`. We should remove this from all `pom.xml` files

# Tasks

The following tasks will need to be carried out:
* [x] Remove this from the [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/) project.
* [x] Remove this from the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project.
* [x] Remove this from all `pom.xml` files in the [strongbox](https://github.com/strongbox/strongbox/) project.

# Acceptance Test

* [x] Building the code with `mvn clean install -Dintegration.tests` still works.
* [x] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [x] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by ragcrix** [comment]
Is this task still open?

**Comment by carlspring** [comment]
Hi @ragcrix ,

Well, it's open, but there have already been two contributors offering pull requests for it. However, neither of them have responded to my request for them to sign the ICLA yet...

**Comment by carlspring** [comment]
Thanks, @ankii2189! :)
