### ISSUE TITLE
Clean up properties in the strongbox-parent

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1563]
# Task Description

We've migrated to `restassured` and, recently. Spring Boot. We need to double-check, if we still need these properties defined in the strongbox-parent:

```
        <!-- Default ports for local development: -->
        <port.jetty.listen>48080</port.jetty.listen>
        <port.jetty.shutdown>19081</port.jetty.shutdown>
        <strongbox.host>localhost</strongbox.host>
        <strongbox.port>${port.jetty.listen}</strongbox.port>
```

If we don't need them, then we should remove them and check, if the build still works.

# Tasks

The following tasks will need to be carried out:
* [ ] Remove this from the [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/) project.
* [ ] Remove this from the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project.
* [ ] Remove this from all `pom.xml` files in the [strongbox](https://github.com/strongbox/strongbox/) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by zedd-08** [comment]
I would like to work on this!

**Comment by ragcrix** [comment]
Hi, you can assign this task to me.

I will do it.

**Comment by carlspring** [comment]
Hey, @ragcrix !

I actually finished this last night but didn't get around to creating the pull requests.

**Comment by carlspring** [comment]
Would you mind picking another task? Please, feel free to join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by ragcrix** [comment]
ok then @carlspring. 

I will look at other tasks. 

Thanks.

**Comment by carlspring** [comment]
Thank you for your understanding! And once again -- my apologies!
