### ISSUE TITLE
Upgrade mockito to >= 3.1.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1564]
# Task Description

We are currently using Mockito 2.22. We should consider upgrading to >= 3.1.0.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/)) project.
* [ ] Update this from the [strongbox-parent](https://github.com/strongbox/strongbox-parent/)) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by chace86** [comment]
@carlspring please review https://github.com/strongbox/strongbox-proto-parent/pull/12

**Comment by chace86** [comment]
Also https://github.com/strongbox/strongbox-parent/pull/51

**Comment by chace86** [comment]
I may need advice on how to go through acceptance test criteria.

**Comment by carlspring** [comment]
@chace86 : 

Do a `mvn clean install` of the `strongbox-parent` locally and then try building the `strongbox` and `strongbox-web-integration-tests` projects. If they build successfully, then things should work fine. Just follow the steps outlined in the acceptance tests above.

**Comment by chace86** [comment]
Done!

**Comment by carlspring** [comment]
Thank you!

Congratulations on your first pull request! :)
