### ISSUE TITLE
Drop the org.apache.tomcat:catalina dependency from any pom.xml files that might be using it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1565]
# Task Description

We should no longer need this dependency. This task should verify this theory, and, if so, we should remove this from all `pom.xml` files.

# Tasks

The following tasks will need to be carried out:
* [ ] Remove this from the [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/)) project.
* [ ] Remove this from the [strongbox-parent](https://github.com/strongbox/strongbox-parent/)) project.
* [ ] Remove this from all `pom.xml` files in the [strongbox](https://github.com/strongbox/strongbox/) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by retsbol** [comment]
I'd like to try this.

**Comment by carlspring** [comment]
Go for it!

**Comment by praXin** [comment]
I'd like to take up this issue.

**Comment by carlspring** [comment]
@praXin ,

Somebody already expressed an interest in this task, but -- sure -- go ahead, if you think you could do it quickly! :)
