### ISSUE TITLE
Upgrade awaitility to >= 4.0.1

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1566]
# Task Description

We are currently using Awaitility 3.1.2. We should consider upgrading to >= 4.0.1.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the [strongbox-proto-parent](https://github.com/strongbox/strongbox-proto-parent/) project.
* [ ] Update this from the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by Phitrapy** [comment]
Let's try this!

**Comment by Phitrapy** [comment]
Well, I'm not sure I've done everything th good way. But here's what I've done:

PR for the strongbox-proto-parent project
[strongbox-proto-parent PR#10](https://github.com/strongbox/strongbox-proto-parent/pull/10)

PR for the strongbox-parent project:
[strongbox-parent PR#49](https://github.com/strongbox/strongbox-parent/pull/49)

**Comment by carlspring** [comment]
Resolved by @anki2189! :)
