### ISSUE TITLE
Create a proof-of-concept using Janusgraph and Cassandra

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1573]
# Task Description

We would like to investigate migrating to Janusgraph + Cassandra and completely dropping OrientDB.

We've invested at least about a year in getting different things to work with OrientDB and fixing its bugs. Their team is quite slow in their responses and turnarounds and we can't currently upgrade to OrientDB 3.x because of bugs in it.

# Tasks

The following tasks will need to be carried out:

We should look into these tasks (in roughly the following order):
* [x] Set up a project for this on Github ([strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc))
* [x] Set up a Maven project
* [x] Get things working with Spring Boot
* [x] Create a runnable Spring Boot jar which can be used for testing
* [x] Set up a project in Jenkins ( @steve-todorov )
* [x] Set up embedded cassandra ( @sbespalov / @fuss86 )
* [x] Create schema scripts (@sbespalov)
* [x] Investigate possibility to use `neo4j-ogm` with `cypher-for-gremlin`
* [x] Investigate possibility to use `gremlin query language` (@fuss86) (👍 )
* [x] Inheritance (@sbespalov) |
* [x] Create indexes

| neo4j-ogm | Gremlin DSL  |                                                                                      |
| -------------- | ------------------ | ---------------------------------------------------------------------- |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [x] </li> </ul> | Implement `ArtifactCoordinates` class (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [x] </li> </ul> | Implement `ArtifactEntry` class (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [ ] </li> </ul> | Implement `ArtifactDependency` class (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [x] </li> </ul> | Implement `ArtifactIdGroup` class (@sbespalov)
| <ul><li>- [x] </li> </ul> |  <ul><li>- [x] </li> </ul> | Implement a DAO/service (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [ ] </li> </ul> | Implement `searchArtifactEntriesByArtifactCoordinatesPath` query (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [ ] </li> </ul> | Implement `searchAllDependentArtifactEntries` query (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [ ] </li> </ul> | Implement `searchArtifactEntriesByArtifactId` query (@sbespalov) |
| <ul><li>- [x] </li> </ul> |  <ul><li>- [ ] </li> </ul> | Transaction manager (`spring-data-neo4j` provides the `TransactionManager`) |

* [ ] Management consoles (@steve-todorov )
  * [x] Investigate whether there is a management console for Janusgraph (@fuss86) (👍 )
    * [ ] ~~Investigate whether we can run user-defined queries using web console~~ https://github.com/strongbox/strongbox/issues/1609 ( @anki2189 )
    * [x] Implement custom Web Console which allows to execute Gremlin and Cypher queries (@steve-todorov / #1622 )
  * [ ] Investigate whether there is a management console for Cassandra
* [ ] Set up caching with Hazelcast
* [ ] Elasticsearch (**on hold**)
  * [x] Set up Elasticsearch ( @cbrianhill )
  * [ ] Investigate how to implement full-text search
  * [ ] Implement a service
  * [ ] Implement a search controller
  * [ ] Implement tests
* [x] Populate data with 100k entries (the data doesn't matter)
* [ ] Make an end-point, which can select random data from the 100k records
  * [ ] Make a "search" for the 100k (#1621)
* [ ] Create database backups & rollbacks
* [ ] Create incremental schema updates/migrations ( #1588 ) ( @fuss86 )

Please, note that multiple people can work of these sub-tasks.

# Task Relationships

This task:
* Is the parent of: #1588

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@sbespalov / @steve-todorov ,

I assume we can we proceed with closing this task?

**Comment by steve-todorov** [comment]
Lol... Yeah I believe we're way past the PoC part. :)

**Comment by carlspring** [comment]
Amen for that! :)
