### ISSUE TITLE
Add a "Tool Integration" section to the User Guide and migrate the existing docs for the supported tools to it

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1580]
# Task Description

We need to add a "Tool Integration" page to our "User Guide" and sub-pages for the various tools that we have examples for.

Please, note: This task can be handled by multiple developers as separate pull requests.

# Tasks

The following tasks will need to be carried out:
* [x] Migrate the Ant+Ivy example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the Gradle example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the Maven example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the NPM example ( @anki2189 )
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the NuGet (Mono) example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the NuGet (Visual Studio) example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
* [x] Migrate the SBT example
  * [x] Verify that the example still works and apply any necessary changes to update the documentation.
  * [x] Create a new page for this in the wiki and move the text there.
  * [x] Remove the text from the `README.md`.
  * [x] Move any images to from the example project to the wiki.
# Useful Links

* [Our wiki](https://github.com/strongbox/strongbox-docs/) (Please, read the instructions on how to create new wiki pages)
* The [strongbox-examples](https://github.com/strongbox/strongbox-examples/).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by aayushbhan** [comment]
@carlspring can i pick this up.

**Comment by carlspring** [comment]
Thanks, feel free to look into it. Please, add comments on which parts you'll be working, as maybe somebody else would like to pick a part of the work as well. Thanks! :)

**Comment by aayushbhan** [comment]
I'll pick up the maven and gradle examples and then once they're done if any others are left that haven't been picked up i can look into them.

**Comment by carlspring** [comment]
Great, thanks! :)

**Comment by anki2189** [comment]
@carlspring Added Documentation NPM . Pls review :)

**Comment by aayushbhan** [comment]
@carlspring Documentation for Maven and Gradle. Please take a look.

**Comment by carlspring** [comment]
Thanks, @aayushbhan ! :)

**Comment by carlspring** [comment]
Thanks to everybody who contributed! :)
