### ISSUE TITLE
Rename the NullArtifactCoordinates, NullArtifactGenerator and NullRepository classes

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1582]
# Task Description

We need to rename the `NullArtifactCoordinates`, `NullArtifactGenerator` and `NullRepository` classes to be more consistent. These are meant to be used for the Raw layout proviver.

# Tasks

The following tasks will need to be carried out:
* [ ] Rename the `NullArtifactCoordinates` class to `RawArtifactCoordinates`.
* [ ] Rename the `NullArtifactGenerator` class to `RawArtifactGenerator`.
* [ ] Rename the `NullRepository` class to `RawRepository`.

# Task Relationships

This task:
* Relates to: #1540

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
@carlspring @steve-todorov I would like to pick this task

**Comment by carlspring** [comment]
Great! Please, keep in touch with @wpater , as he's working on #1540 , which might be affected by this.
