### ISSUE TITLE
Incremental Janusgraph schema updates

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1588]
# Task Description
We need to be able to manage Janusgraph schema with incremental versioned updates. This should be done with help of `JanusGraphManagement` which provide Java API to manage schema. We already have a `org.carlspring.strongbox.janusgraph.graph.schema.StrongboxSchema` class that creates initial schema and within this task we should make it work using step-by-step change-sets. The change-sets will be stored as a constant list of `StrongboxSchema` class.

# Tasks

The following tasks will need to be carried out:
* [ ] Implement an interface which will represent single change-set, it should have the `apply(JanusGraphManagement jgm)` method and following attributes:
- name (some meanable change-set name)
- version (Semantic Versioning format)
* [ ] Add `DatabaseSchema` vertex type which will represent current schema
* [ ] Add `ChangeSet` vertex type which will represent applied change-sets
* [ ] Add `DatabaseSchema#ChangeSet` edge type which will represent one-to-many relation between `DatabaseSchema` and `ChangeSet` (it should also have the `applyDate` property)
* [ ] Implement the logic which will create `DatabaseSchema` vertex if it not exists
* [ ] Implement the logic which will apply change-sets delta from current `DatabaseSchema` version.
* [ ] implement `StrongboxSchema.dropSchema` method for test purpose which will be executed on Spring Application context shutdown.

# Task Relationships

This task:
* Is a sub-task of: #1573

# Useful Links

* [Schema and Data Modeling](https://docs.janusgraph.org/basics/schema/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
