### ISSUE TITLE
Update docker-compose files to point to the new docker images

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1595]
# Task Description

We have migrated our docker images into [strongbox/ci-build-image](https://github.com/strongbox/ci-build-images). During the refactoring we have also switched the naming convention for our images.

We need to upgrade the `docker-compose.yaml` files across all projects so that they point to the new tags. The images are published in [docker hub](https://hub.docker.com/u/strongboxci) and you can see the new image tags there. 

** NOTE **: Although there are `jdk11` images, we still DO NOT support it. For the purpose of this task use the images tagged with `jdk8`.

# Tasks

The following tasks will need to be carried out:
* [ ] Fix `docker-compose.yaml` in [strongbox](https://github.com/strongbox/strongbox)
* [ ] Fix `docker-compose.yaml` in [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests)
* [ ] Fix `docker-compose.yaml` in [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-docs)
* [ ] Fix the image tags in the [strongbox-docs](https://github.com/strongbox/strongbox-docs/blob/master/docs/developer-guide/building-the-code-with-docker.md) (check for other pages which)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
@steve-todorov I would like to pick this as i have these changes on my local machine. :)
