### ISSUE TITLE
Reduce the amount of debugging output that we have

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1597]
# Task Description

At the moment, the debugging output has become quite excessive. We need to reign in and get this under control

# Tasks

The following tasks will need to be carried out:
* [ ] Find out what packages/classes are producing the heaviest amount of output.
* [ ] Locate useless debugging output and remove it. (For example, this could be blocks of `logger.debug` calls that are really not that helpful.
* [ ] Add rules to fine-tune the noise.

# Useful Links

* [Strongbos Developer Guide: Logging](https://strongbox.github.io/developer-guide/add-logging.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by TJoker024** [comment]
Hi, i am working on this issue from now !

**Comment by carlspring** [comment]
Hi @TJoker024 ,

Well, I believe @anki2189 is already look into this, but feel free to join our [chat channel](https://chat.carlspring.org/) where we can discuss it further! :)

**Comment by AkshayBabbar** [comment]
Hi Can I work on this??

**Comment by ShraddhaBhojane** [comment]
Hi, can I take this?

**Comment by shuklashwin** [comment]
Hi, interested to work on this.

**Comment by steve-todorov** [comment]
Hi @shuklashwin - there is already an open PR for this #1607. Can you choose another task? :)

**Comment by emanuelconte** [comment]
Hi @carlspring. Can I work on this issue ?

I'm new to open source projects, would like to give this a try.

**Comment by carlspring** [comment]
@emanuelconte ,

As this project is currently on hold, I appreciate your offer to help, but would suggest you don't do so.
