### ISSUE TITLE
Help with Janusgraph PoC: run user-defined gremlin queries in Graphexp

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1609]
# Task Description

We have successfully connected [graphexp](https://github.com/erandal/graphexp) web graph visualization tool to gremlin server started by [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc).

We want to be able to run user defined-queries in [graphexp](https://github.com/erandal/graphexp).
against our gremlin server. There should be some input text box provided where we can put for example `g.V().has('name', 'hercules')` and send it to the server and visualize results.

# Tasks

The following tasks will need to be carried out:
* [ ] Ask @carlspring to join `janusgraph-poc` channel on [our chat](https://chat.carlspring.org/)
* [ ] Clone https://github.com/strongbox/strongbox-janusgraph-cassandra-poc
* [ ] Run `strongbox-janusgraph-cassandra-poc` with `strongbox.graph.gremlin.server.enabled` eq to `true`
* [ ] Fork and clone https://github.com/erandal/graphexp
* [ ] Run `graphexp` against `strongbox-janusgraph-cassandra-poc` (no additional configuration needed, it is straightforward)
* [ ] Verify the the connection between `graphexp` and `strongbox-janusgraph-cassandra-poc` and watch logs in the `strongbox-janusgraph-cassandra-poc` (review queries) 
* [ ] Improve `graphexp` to be able to run user-defined [gremlin queries](https://docs.janusgraph.org/basics/gremlin/) (there should be some input box for it)

# Task Relationships

This task:
* Is a sub-task of: https://github.com/strongbox/strongbox/issues/1573

# Useful Links

* [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc)
* [graphexp](https://github.com/erandal/graphexp)
* [gremlin on janusgraph](https://docs.janusgraph.org/basics/gremlin/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
I would like to  work on this.

**Comment by steve-todorov** [comment]
I'm putting this task on hold as we're exploring another solution for visualizing / running queries which might work better than GraphExp :)

**Comment by steve-todorov** [comment]
This task is now obsolete in favor of #1622. 

@anki2189 thank you very much for looking into this and sorry for having to close your PR!
