### ISSUE TITLE
Store layout specific metadata in DB.

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1620]
# Task Description
Strongbox currently supports multiply Layouts such as:
- Maven
- Npm
- Nuget
- Pypi
- Raw
Almost all of this layouts has specific artifacts metadata such as version, ID, dependencies, author, packaging and many other. Artifacts stored in DB as `ArtifactEntry`, there is also `ArtifactCoordinates` stored as one to many with `ArtifactEntry`. These entities just a part of all metadata that we need to store, for example in case of Maven following should be stored as well (from `pom.xml`):
```
  <name>...</name>
  <description>...</description>
  <url>...</url>
  <inceptionYear>...</inceptionYear>
  <licenses>...</licenses>
  <organization>...</organization>
  <developers>...</developers>
  <contributors>...</contributors>
```
Within this task we should create abstract `ArtifactMetadata` entity, which will be extended as concrete entities for each layout. `ArtifactMetadata` should be one to one with `ArtifactEntry`.

# Tasks

The following tasks will need to be carried out:
* [ ] Create `MavenArtifactMetadata` entity
* [ ] Create `NpmArtifactMetadata` entity
* [ ] Create `NugetArtifactMetadata` entity
* [ ] Create `PypiArtifactMetadata` entity

Each  `ArtifactMetadata` entity implementation should have Liquibase changeset, Unit Test and framed as a standalone Pull Request.

# Task Relationships

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
