### ISSUE TITLE
Implement custom web console which allows to execute Gremlin and Cypher queries

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1622]
# Task Description

We need to create a user interface which can execute queries against the JanusGraph database.

# Tasks

The following tasks will need to be carried out:

* [x] Make it possible to configure the UI to connect to different backends
* [x] Have a query execution page where queires can be executed. Upon query execution, there should be three different query result views:
  * [x] JSON view - always available and should display the response from the server.
  * [x] Table view - whenever possible, should display the results in table view.
  * [x] Graph view - whenever possible, should display the results in graph fiew.
* [x] "Browse Schema" page which displays all node types.

# Task Relationships

This task:
* Is a sub-task of: #1573

**Comment by steve-todorov** [comment]
This task is completed now. However it is far from being "perfect". I've spent a while trying to get the [`gremlin-javascript`](https://github.com/apache/tinkerpop/tree/3.4.4/gremlin-javascript/src/main/javascript/gremlin-javascript/lib) to work but unfortunately the official implementation is intended to be used in Node.js and cannot be used directly in a browser. 

In general, the current UI will be able to execute any cypher / gremlin queries, but it won't be able to display all types of queries in `table` / `graph` views because the returned data can be all sorts of recursive [GraphSON](http://tinkerpop.apache.org/docs/3.4.4/dev/io/#graphson-3d0) data that needs to be properly parsed, then traversed and finally converted in another data structure so that it can be displayed in table/graph view.

If we decide to continue with JasonGraph, we'll probably need reverse engineer `gremlin-javascript` and port it so we can properly traverse the json responses and display the data adequately.
