### ISSUE TITLE
Store Maven layout specific metadata in DB

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1623]
# Task Description
We need to store following `pom.xml` metadata for Maven artifacts:
```
  <name>...</name>
  <description>...</description>
  <url>...</url>
  <inceptionYear>...</inceptionYear>
  <licenses>...</licenses>
  <organization>...</organization>
  <developers>...</developers>
  <contributors>...</contributors>
``` 

# Tasks

The following tasks will need to be carried out:
* [ ] Create `MavenArtifactMetadata` entity
* [ ] Create liquibase changesets for `MavenArtifactMetadata`
* [ ] Create Unit Test with following case:
    * deploy maven artifact with `MavenArtifactsController`
    * read the `ArtifactEntry` from DB and check that there is appropriate `MavenArtifactMetadata` with expected data

# Task Relationships

This task:
* Is a sub-task of: #1620 

# Useful Links

* [Getting started with persistence](https://strongbox.github.io/developer-guide/getting-started-with-persistence.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
