### ISSUE TITLE
Store NPM layout specific metadata in DB

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1624]
# Task Description
We need to store following `package.json` metadata for NPM artifacts:
* "description"
* "keywords"
* "repository"
* "homepage"
* "author"
* "contributors"
* "license"
* "main"
* "engines"
* "os"
* "cpu"
* "_rev"

# Tasks

The following tasks will need to be carried out:
* [ ] Create `NpmArtifactMetadata` entity
* [ ] Create liquibase changesets for `NpmArtifactMetadata`
* [ ] Create Unit Test with following case:
    * deploy npm artifact with `NpmArtifactsController`
    * read the `ArtifactEntry` from DB and check that there is appropriate `NpmArtifactMetadata` with expected data

# Task Relationships

This task:
* Is a sub-task of: #1620 

# Useful Links

* [Getting started with persistence](https://strongbox.github.io/developer-guide/getting-started-with-persistence.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov
