### ISSUE TITLE
Implement support for the data-requires-python attribute as described in PEP 503

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1631]
# Task Description

We need to implement support for `data-requires-python` attribute as described in [PEP 503](https://www.python.org/dev/peps/pep-0503/).

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate how this works
* [ ] Implement support for it in the `PypiArtifactController`.
* [ ] Add a test in the `PypiArtifactControllerTest`.
* [ ] Consider adding tests that require Python 3.x under the `strongbox-web-integration-tests` to make sure that this is properly covered.

# Task Relationships

This task is a sub-task of #807 .

# Useful Links

* [PEP 503](https://www.python.org/dev/peps/pep-0503/).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
@carlspring This feature is dependent on Pypi metadata persistence task.
The value of `data-requires-python` will be populated from `Requires-Python` metadata field from `PKG-INFO` file which we are not persisting in DB as of now.
