### ISSUE TITLE
Move `PypiArtifactController.getHtmlResponse` logic into `PypiBrowsePackageHtmlResponseBuilder` class

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1634]
# Task Description

We need to incapsulate logic needed to generate HTML response for `PypiArtifactController.getPackagePath` into standalone class.

# Tasks

The following tasks will need to be carried out:

* [ ]  Create  `PypiBrowsePackageHtmlResponseBuilder` class (it should be managed as Spring component bean)
* [ ] Replace `PypiArtifactController.getHtmlResponse` usage with `PypiBrowsePackageHtmlResponseBuilder`
* [ ] Remove `PypiArtifactController.getHtmlResponse` and related methods
* [ ] Rename the `PypiArtifactController.getPackagePath` to `PypiArtifactController.browsePackage`
* [ ] Provide Unit Test for `PypiBrowsePackageHtmlResponseBuilder`

# Task Relationships

This task:
* Is a follow-up of: #1625

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@anki2189 : Would you mind picking this up?

**Comment by anki2189** [comment]
Sure will pick this.
