### ISSUE TITLE
OrientDB Gremlin configuration

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1650]
# Task Description
Provide Spring configurations and related compnents for Gremlin.

# Tasks

The following tasks will need to be carried out:
* [x] Gremlin server configuation (should be optional based on environment variable)
* [x] [Spring Data Neo4j](https://docs.spring.io/spring-data/data-neo4j/docs/current/reference/html/#reference) configuation
* [x] Gremlin DSL interfaces
* [ ] ~[strongbox-database-ui](https://github.com/strongbox/strongbox-database-ui) configuration~ (#1669)
* [ ] Unit tests that checks Gremlin server port avaliability (should have cases based on environment variable)
* [x] Unit tests that checks Gremlin Traversal Source avaliability 
* [x] Unit tests that checks transactions management

# Task Relationships

This task:
* Is a sub-task of: #1649

# Useful Links

* [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc)
# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
Where can one find more details regarding the Gremlin server configuration? Could you please share these details and how you envision this? Thanks!

**Comment by sbespalov** [comment]
all the tasks should be done same way like it appears in [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc) (there is Gremlin Server configuration there)

**Comment by sbespalov** [comment]
also we probably should use [orientdb-gremlin](https://github.com/orientechnologies/orientdb-gremlin) here

**Comment by sbespalov** [comment]
there is also some documentation [here](http://orientdb.com/docs/3.0.x/tinkerpop3/OrientDB-TinkerPop3.html)

**Comment by carlspring** [comment]
Could you please be a bit more specific in regards to where the configuration is? Are these the only configuration resources?
* [src/main/resources/application.yaml](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc/blob/master/src/main/resources/application.yaml)
* [src/main/resources/conf/gremlin-server/gremlin-server.yaml](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc/blob/master/src/main/resources/conf/gremlin-server/gremlin-server.yaml)

Is there something else I'm missing?

Is this task for the `strongbox` project itself, or should this first be implemented in the [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc)?

**Comment by steve-todorov** [comment]
@sbespalov could you please give more context:
1. Gremlin DSL interfaces - what interfaces do you think are necessary, do we already have something which needs to be migrated?
2. strongbox-database-ui configuration - what do you mean here?

**Comment by sbespalov** [comment]
@steve-todorov 
> Gremlin DSL interfaces - what interfaces do you think are necessary, do we already have something which needs to be migrated?

by Gremlin DSL interfaces I mean [EntityTraversalDsl](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc/blob/master/src/main/java/org/carlspring/strongbox/janusgraph/gremlin/dsl/EntityTraversalDsl.java). There is some documentation [here](http://tinkerpop.apache.org/docs/current/reference/#dsl). So we alraady have it in PoC and this needs to be migrated to strongbox.

> strongbox-database-ui configuration - what do you mean here?

I mean that we have [strongbox-database-ui](https://github.com/strongbox/strongbox-database-ui) which needs to be embedded in strongbox. So there sould be some Spring and Maven configurations  to make it work.

**Comment by sbespalov** [comment]
@carlspring 

> Could you please be a bit more specific in regards to where the configuration is? Are these the only configuration resources?

Not only resources. By configurations I mean Spring configuration in general. This is basically all that has the `@Configuration` annotation.

**Comment by sbespalov** [comment]
@carlspring 

>> Is this task for the strongbox project itself, or should this first be implemented in the strongbox-janusgraph-cassandra-poc?

it should be implemented in strongbox. The main thing that need to be done is to make gremlin works with OrientDB and this requires some research which I'm currently working on, so I can't exaclty say what classes we need and how it should be configured.

**Comment by carlspring** [comment]
I see, thanks for the clarifications!

I was under the impression that you wanted to try this out in the PoC first.

**Comment by sbespalov** [comment]
no, all this tasks is for strongbox. Most of the work done with the PoC and now we need to migrate it to strongbox.

**Comment by sbespalov** [comment]
Won't fix, due to inappropriateness of spending much time with OrientDB issues. The problem was that seems there is no easy way to use Graph API  together with Object API within same transaction.
