### ISSUE TITLE
Enable Disabled test cases for NugetArtifactControllerTest

### ISSUE THREAD

**Issue by anki2189** [strongbox/strongbox#1652]
# Task Description
Some of the test cases were disabled in `NugetArtifactControllerTest` which uses multipart file.
Currently we are using restassured based `MockMvcRequestSpecification` in our test cases but it doesn't support `PUT` method with multipart file.

# Tasks

The following tasks will need to be carried out:
* [ ] Enable Test `NugetArtifactControllerTest#testPackageCommonFlow`
* [ ] Enable Test `NugetArtifactControllerTest#testChocolatey`
* [ ] Enable Test `NugetArtifactControllerTest#testLastVersionPackageSearch`

# Task Relationships

This task:
* Is a follow-up of: #1637

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
It looks like someone will need to report this to the [restassured](https://github.com/rest-assured/rest-assured/) project. We might even have to submit a pull request for this ourselves.

@anki2189 : Could you please open an issue in their issue tracker on Github and link it back, so that we could start the initial discussion and get things going? Thanks! :)

**Comment by anki2189** [comment]
Created an issue (https://github.com/rest-assured/rest-assured/issues/1262) in restassured project.

**Comment by carlspring** [comment]
Thanks! :)
