### ISSUE TITLE
Implement Gremlin based UserEntry

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1653]
# Task Description

The `UserEnity` should have a new repository class with Gremlin based CRUD and Spring Data Neo4j based custom Cypher queries. The `UserRepository` should be placed under `org.carlspring.strongbox.gremlin.repositories`.

# Tasks

The following tasks will need to be carried out:
* [x] Re-work `UserEntry` class:
    - [x] Create a `UserEntity` class with `neo4j-ogm` annotations
    - [x] Re-work `UserEntryService` into `UserRepository`
    - [x] Re-work `OrientDbUserService` into `GremlinUserService` 
    - [x] Replace all `UserEntry` references with `UserEntity`
    - [x] Implement `UserAdapter` for `UserRepository` class
    - [x] Provide Cypher queries with `@Query` annotation for  `UserQueries` interface

# Task Relationships

This task:
* Is a sub-task of: #1649
* depends on: #1650

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
@sbespalov could you please add a few words about the purpose of each of the mentioned class and what they should be doing?

**Comment by carlspring** [comment]
Some questions:
* What should the `UserAdapter` be for exactly?
* What should one keep in mind while migrating the `OrientDbUserService` into `GremlinUserService`? Are there some common steps to follow that could be used for other such services that will have to be migrated? (If so, could you please list them here for future reference? Thanks!).

**Comment by kaansonmezoz** [comment]
I'd like to work on this issue. But there are some things which should be cleared out.

-  What is the role of UserAdapter, what should be adapting from what ?
-  I've searched for OrientDbUserService in the code base and the only thing I found is that a variable named after orientDbUserService whose type is UserService. Is that what you meant by OrientDbUserService ? Do you mean UserService ?

**Comment by carlspring** [comment]
@kaansonmezoz ,

This is a proof-of-concept based on the [strongbox[(https://github.com/strongbox/strongbox/) project. The code will initially (@sbespalov , please confirm, if this is how you envision it) be in [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc) where we have Janusgraph + Cassandra all set up.

**Comment by sbespalov** [comment]
thank you all for interesing to this issue. There is some general explanations in master task, so please have a look at #1649. Also it would be good to see on how all the things implemented in [strongbox-janusgraph-cassandra-poc](https://github.com/strongbox/strongbox-janusgraph-cassandra-poc). If there still will be a general questions please ask at #1649 comments.

**Comment by steve-todorov** [comment]
@sbespalov what is the state of this task? I believe @carlspring mentioned this has already been done and committed into #1653 ? Can we now close this or is there anything else needed to be done?

**Comment by sbespalov** [comment]
@steve-todorov it's not implemented. probably @carlspring can clarify better what is the status.

**Comment by carlspring** [comment]
@steve-todorov : There seems to be some sort of confusion.
@sbespalov : I thought I saw this implemented on your branch. :-D

**Comment by sbespalov** [comment]
I've just fixed User related compilation issues, but this is just stubs withut implementation

**Comment by carlspring** [comment]
Will be done as part of #1649 via #1676 .
