### ISSUE TITLE
Replace Embedded OrientDB with Embedded JanusGraph+Cassandra

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1654]
# Task Description

We need to adapt the developments made as part of PoC for strongbox.

# Tasks

The following tasks will need to be carried out:
* [x] Replace  OrientDB dependencies with JG+Cassandra dependencies in `strongbox-parent`
* [x] Rename `OrientDbServer` into `EmbeddedDbServer` in `strongbox-db` and provide implementation for JanusGraph+Cassandra
* [x] Replace `OrientDbServerConfiguration` with `JanusGraphServerConfiguration` 
* [x] Rework `strongbox-db-import`, it should setup JanusGraph with DB initialization scripts
* [x] Drop `strongbox-db-liquibase`

# Task Relationships

This task:
* Is a sub-task of:  #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@sbespalov : Just a reminder -- could you please add a proper description for this placeholder task? Thanks!

**Comment by sbespalov** [comment]
this is done witin [PR #1676](https://github.com/strongbox/strongbox/pull/1676)
