### ISSUE TITLE
Embed the `strongbox-database-ui` into` strongbox` application

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1669]
# Task Description

There is [strongbox-database-ui](https://github.com/strongbox/strongbox-database-ui) which provide a UI to execute Gremlin and Cypher queryes on strongbox database. Within this task we need to make it available under `http://localhost:48080/db-ui` URL in strongbox distribution.

# Tasks

The following tasks will need to be carried out:
* [ ] Add `strongbox-database-ui` dependency in [strongbox-parent](https://github.com/strongbox/strongbox-parent) dependency management.
* [ ] Add `strongbox-database-ui` zip dependency for `strongbox-web-core` 
* [ ] Provide nececary Spring MVC configuration for `strongbox-database-ui` in `WebConfig` configuration class
* [ ] Provide nececary Spring MVC configuration for `strongbox-database-ui` in `WebConfig` configuration class

# Task Relationships

This task:
* Is a sub-task of: #1649
* Is a follow-up of: #1650

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by saz9zo** [comment]
Hi, can you please give little idea on how to config UI from dependency in webConfig. It has to be similar to web-ui, right, but I don't see how it was implemented.
