### ISSUE TITLE
Upgrade to Angular 10

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1681]
# Task Description

Upgrade strongbox/strongbox-web-ui to Angular 10

# This task

- [x] Depends on ng-select/ng-select#1499 and ng-select/ng-select#1519 (fixed)
- [x] Depends on ngxs/store#1532 (fixed)
- [ ] Sass 1.23 uses a new module system which will require some work to migrate. (ng 9+ uses [`sass 1.26.3`](https://github.com/angular/angular-cli/blob/9.1.x/packages/angular_devkit/build_angular/package.json#L52)`)

**Comment by GeorgHenkel** [comment]
Hi @steve-todorov I would go for it. Can you please assign me to this task?

**Comment by carlspring** [comment]
Great work, @GeorgHenkel ! Thank you very much! :)
