### ISSUE TITLE
Refactor/rename MavenArtifactController.greet() method

### ISSUE THREAD

**Issue by anki2189** [strongbox/strongbox#1684]
# Task Description

`MavenArtifactController` has greet() Method , find out what is the use of this `greet()` method in the controller.
If it is required, we should rename this method to a better relevant name.

# Tasks

The following tasks will need to be carried out:
* [ ] Find out usage of `MavenArtifactController.greet()`
* [ ] Drop `MavenArtifactController.greet()` if not required.
* [ ] Rename `MavenArtifactController.greet()` to relevant if needed.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
it seems we have similar methods in every controller. I want to say that whether these methods are used or not within concrete protocol we probably could have it just for test purpose, to check that repository avaliable for example. My suggestion is to move this method into `BaseArtifactController` with approproate name (maybe `checkRepositoryAccess` like we have it in `NugetArtifactController`) and default `{storageId}/{repositoryId}` mapping. Then we can override it in concrete controllers if needed or left default.

**Comment by TSchifferG** [comment]
Hello I would like the opportunity to take this task. Should I implement it in the style suggested by sbespalov?

**Comment by carlspring** [comment]
@TSchifferG ,

Yes, could you please follow @sbespalov 's advice? Also, please join our [chat channel](https://chat.carlspring.org/) for help and more details. Thanks! :)

**Comment by sachinmukherjee** [comment]
Is this issue open?

**Comment by pkkht** [comment]
Hi there.. Carl asked me to assign this issue to myself yesterday.. am trying to do that.. :)

**Comment by pkkht** [comment]
working on this

**Comment by ykabusalah** [comment]
Is this still going for pkkht? Or can I get assigned this?

**Comment by pkkht** [comment]
Please assign to yourself

Cheers
Hari

**Comment by carlspring** [comment]
Feel free to proceed.

**Comment by saz9zo** [comment]
Hi, Can I work on this issue?

**Comment by pkkht** [comment]
Hi
You can!

**Comment by parth704131** [comment]
hi i think greet method is only checks user is authenticated or not and i think some this is method is made only for testing purpose.

**Comment by Echidna93** [comment]
Hi is help still needed with this?

**Comment by carlspring** [comment]
Hi @Echidna93 ,

Yes, but please be advised, that there is a set of tasks like this one for the controllers of each of our layout providers. Feel free to pick it up! We had a contributor, who I believe didn't sign our ICLA, hene we were unable to accept their pull request.

**Comment by Echidna93** [comment]
Great I will start looking at it over the weekend! :)

**Comment by Echidna93** [comment]
So it sounds like these have already been determined to be essential for strongbox, but your previous contributor didn't sign the agreement so you couldn't merge. So then all that needs done is the renaming of the greet functions to something more relevant in every layout provider.

**Comment by carlspring** [comment]
More, or less, yes. These are simple set of cleanup tasks. We do require a signing of our ICLA and if such is not provided within reasonable time, we close them. Feel free to have a go at it. It's not much work.

**Comment by parameswaranmarimuthu** [comment]
@carlspring , anyone working on it? I can pick it up if its open.

**Comment by carlspring** [comment]
Go for it!

**Comment by carlspring** [comment]
@parameswaranmarimuthu : I believe @Echidna93 did a pull request for this, but never applied the changes I requested. @Echidna93 , will you be applying the changes anytime soon...?
