### ISSUE TITLE
Fix strongbox-web-ui installation under windows

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1690]
# Task Description

The [strongbox/strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui) project has a `patch-antlr4` script which currently only works on Linux/Unix because of the replace path style. We need to improve this so that it works on Windows as well.

# Tasks

The following tasks will need to be carried out:

* [x] Create a `tools` folder in the `strongbox-web-ui` root path.
* [x] Move `update-webdriver.js` into `tools` and change all references in the `package.json
* [x] Create a `./tools/antlr4-patch.js` javascript which is using [`replace-in-file`](https://www.npmjs.com/package/replace-in-file) to replace the occurrences of `var fs.*` to `var fs = false;` in the files `node_modules/antlr4/FileStream.js` and `node_modules/antlr4/CharStreams.js`
* [x] Replace the current `patch-antlr4` script in the `package.json` so it runs `node ./tools/antlr4-patch.js`

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @steve-todorov

**Comment by aosousa** [comment]
As mentioned in the chat, can I be assigned to this task?

**Comment by steve-todorov** [comment]
Sure - feel free to pick it up! :)

**Comment by aosousa** [comment]
Successfully tested a solution for this following the steps above in both Windows and Linux environments. Will create a pull request after handling the ICLA some time this weekend :)

**Comment by carlspring** [comment]
Excellent! Thank you! I'm looking forward to your pull request and signed ICLA.
