### ISSUE TITLE
Improve strongbox-web-ui build process using custom-webpack

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1691]
# Task Description

Up until now we have been using a rather hackish way to build and package [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui). Although it has been working fine, it introduces some complexity which we can remove with some small changes and switching to `@angular-builders/custom-webpack`. These changes will result in more flexibility and less overall complexity.

# Tasks

The following tasks will need to be carried out:
* [ ] Output all assets to `dist/strongbox-web-ui/static/assets/**`
* [ ] Output `index.html` to `dist/strongbox-web-ui/index.html`
* [ ] ~~Use `@angular-builders/custom-webpack` to extend the `webpack` configuration which Angular generates/uses. This would remove the need to have the `package` npm script since this will be happening as part of the `build`~~ <- this introduces issues due to difference in the execution order; additional assets/steps are generated through steps outside or after `webpack`'s build process.
* [ ] Create a [`Proxy to Backend`](https://angular.io/guide/build#proxying-to-a-backend-server) to proxy requests to a running Strongbox backend. This will also be in handy for serving the `index.html` since the `servePath` is going to be changed (because of the asset path configuration changes)

# Useful Links

* [angular-builders](https://github.com/just-jeb/angular-builders)
* [Proxy to Backend](https://angular.io/guide/build#proxying-to-a-backend-server)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov
