### ISSUE TITLE
Configure Github Actions to run matrix jdk builds

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1695]
# Task Description

We would like to setup Github Actions to test our `master` and `PR`s using the latest LTS versions which as of this moment are `jdk8` and `jdk11`. The build steps should only attempt to do build the project similarly to how we do it in the OS/Linux build stage in our Jenkins. Testing with `s-w-i-t` and `smoke-tests` is out of the scope of this task.

This task will result in better testing of Strongbox under different JDKs and will improve our stability.

# Tasks

The following tasks will need to be carried out:
* [x] Have a step which configures Maven to `3.6.3` since this is the version we use on all builds.
* [x] Make sure that Maven is configured to use the right [`settings.xml`](https://strongbox.github.io/developer-guide/getting-started.html)
* [x] Build the project using `mvn -B -U clean install -T 2 -Daether.connector.resumeDownloads=false -Dintegration.tests -Dprepare.revision --fail-at-end`

# Task Relationships

This task:
* Relates to: #1109, #1110, #1111

# Useful Links

* [actions/setup-java](https://github.com/actions/setup-java)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by ykabusalah** [comment]
Can I try this?

**Comment by steve-todorov** [comment]
Sure! Please join our chat as well. Also note that you will need to sign an ICLAas mentioned on our [Contributing](https://strongbox.github.io/contributing.html) page.

**Comment by steve-todorov** [comment]
@ykabusalah what's the state of this task? :)

**Comment by steve-todorov** [comment]
This task is now up for grabs. @adbjo and @rbratfors you guys might be interested in this task.

**Comment by carlspring** [comment]
Done. This will only be enabled for `jdk-11.0.3` and has been done as part of #1783. Relates to #1111 .
