### ISSUE TITLE
Update colors, logo and sass assets

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1696]
# Tasks

The following tasks will need to be carried out:
* [ ] Remove dead/unused variables
* [ ] Improve scss variable names where possible
* [ ] Update logo(s)
* [ ] Introduce css vars
* [ ] Dark & Light mode
