### ISSUE TITLE
Create a dashboard which shows live graphs of the current cpu, ram and some jvm stats

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1697]
# Task Description

We need to create a dashboard page which displays a line chart for the current cpu,ram and some JVM stats. Most of the statistics should be available under `localhost:48080/api/monitoring/metrics/`.
This task will require usage of `chart.js` and `rxjs`. 

# Tasks

The following tasks will need to be carried out:
* [x] Install and use [ng2-charts](https://github.com/valor-software/ng2-charts)
* [x] Create a `dashboard` module under `src/app/modules`
* [x] Add a route for `/admin/dashboard` under `app.routing.module.ts`
* [x] Create a `services` and `pages` subfolders in the `dashboard` module.
* [x] Create a `dashboard-metrics.service` under `./services` with multiple methods for each of the line charts below. These methods should use the `HttpClient` and return an `Observable<any>` with the retrieved data. 
* [x] Create a new `dashboard` component in `pages` and fix the routing in the `dashboard-routing.module.ts`.
* [x] For each for the charts below create a new component as `./app/modules/dashboard/pages/dashboard/components/{cpu|ram|jvm}-stats-component`
   * [x] Each of these components **MUST** implements [`OnInit`](https://angular.io/api/core/OnInit) and [`OnDestroy`](https://angular.io/api/core/OnDestroy)
    * [x] `ngOnInit` - automatically start sending requests to the backend every 2 seconds using the appropriate `dashboard-metrics.service` method.
    * [x] `ngOnDestroy` - kill switch to stop the `rxjs.interval()` from further polling the backend when you navigate away to another page. (search for `this.destroy$` in the code and you'll find examples)
* [ ] Line charts
  * [ ] CPU load
  * [x] ~~RAM usage~~ - not available in current metrics.
  * [ ] JVM used memory (out of max memory)
  * [ ] JVM live threads (jvm.threads.live)

A note for the live charts - do not keep chart data infinitely. You should maybe keep at most the data for the last 1 minute (or lets say 60 records?) and afterwards discard the oldest record. If you keep on pushing the [Push](https://valor-software.com/ng2-charts/#/LineChart) button in the chart example, at some point you'll get too much data which is what would we'd like to avoid.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by aosousa** [comment]
As mentioned in the chat, will get started on it this weekend :)
