### ISSUE TITLE
Implement UI for the management of the HTTP connection pool settings

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1699]
# Task Description

It should be possible to manage the configuration settings of the HTTP connection pool. At the moment, we have a controller for this (and tests), but no UI for it.

It should be possible to:
* [ ] Set the number of connections for a proxy repository
* [ ] Get the pool stats for a proxy repository
* [ ] Set/view the default number of connections for proxy repositories
* [ ] Set/view the maximum number of connections for proxy repositories

# Classes of Interest

* `org.carlspring.strongbox.controllers.configuration.HttpConnectionPoolConfigurationManagementController`
* `org.carlspring.strongbox.controllers.configuration.HttpConnectionPoolConfigurationManagementControllerTestIT`
* `org.carlspring.strongbox.service.ProxyRepositoryConnectionPoolConfigurationService`

# Useful Links

* [Strongbox Wiki](https://strongbox.github.io/)
* [Strongbox REST API](https://strongbox.github.io/user-guide/rest-api.html)
* [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov
  * @sbespalov
