### ISSUE TITLE
Implement StrongboxUriComponentsBuilder to centralize generating urls

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1704]
# The issue

Strongbox has a configuration field in the `strongbox.yaml` called `baseUrl`. This field contains the `baseUrl` (i.e. `http://my-domain.com`) which is used when generating URLs for search results, download links and so on. This introduces a few inconveniences:

1. The field requires the user to actually configure it properly or else it will point to `localhost` which will result in "strange" behaviors that new users might consider as bugs.
2. No support for reverse proxies.
3. Using the `baseUrl` string directly creates code duplication (you might need to generate the same type of URL at different places/stages).

# Task Description

We need to create a `UriComponentsBuilder` class which can be used to generate any type of Strongbox URLs. 

# Tasks

The following tasks will need to be carried out:
* [ ] Create `StrongboxUriComponentsBuilder` class which extends `org.springframework.web.servlet.support.ServletUriComponentsBuilder`. This will give us `X-Forwarded-*` support out of the box. 
  * [ ] Use `ServletUriComponentsBuilder.getCurrentRequest()` to pre-populate the builder with the details from the current request.
  * [ ] The `baseUrl` in `strongbox.yml` should be `optional` or `blank` by default.
    * [ ] If `baseUrl` is not empty - it takes precedence over `X-Forwarded-*` headers and the generated URL will contain the configured `baseUrl`.
    * [ ] If no `baseUrl` is configured (or is `blank`) then `X-Forwarded-*` headers will be honored; If no `X-Forwarded-*` headers have been found then the `baseUrl` will taken from `HttpServletRequest` (scheme, host, port, path, etc). 
  * [ ] Make it possible to get a "generic" builder so we can build any URL we need using the proper host, port and path.
* [ ] Remove `RepositoryFileAttributeType.RESOURCE_URL` and it's usage (no longer necessary?)
* [ ] Refactor the `DirectoryListingServiceImpl` to use `StrongboxUriComponentsBuilder` 
  * [ ] Apply all/any necessary changes to controllers using the `DirectoryListingService`.

# Task Relationships

This task:
* Relates to: #1698

**Comment by Maganpreet** [comment]
Hi, I would like to take this up, I am new to open source projects so help me out to understand a little if possible and let me know if I can start on digging down into it.

**Comment by steve-todorov** [comment]
Hi @Maganpreet - you are commenting under a finished pull request (in other words the task is completed). Maybe choose another task? :)

**Comment by carlspring** [comment]
@steve-todorov ,

If the work for this is ready, could you please merge the pull requests, so we can close it? Thanks! :)

**Comment by Maganpreet** [comment]
Hi @steve-todorov , my bad couldn't figure it out so the tasks having label help-wanted are gonna be the open issues right? or can you assign me anything if that's alright?

**Comment by carlspring** [comment]
@Maganpreet ,

You can join our [chat channel](https://chat.carlspring.org/) for such discussions.
