### ISSUE TITLE
Workout which Groovy dependencies we really need

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1705]
# Task Description

We currently have several places that are using the groovy dependencies. For example:
* The `strongbox-data-services`. In #1649 this is coming via the `gremlin-*` and `tinkerpop-*` dependencies.
* The `strongbox-cron-api` and `strongbox-cron-tasks`. In #1649 this is coming via the `strongbox-data-services` dependency. In the `master` this is `groovy-all`.

We need to be more specific in regards to which exact Groovy dependencies we really need, because these can be very problematic (if multiple transitive dependencies are bringing different versions of the Groovy dependencies, this causes incompatibility issues).

The work will have to be done against the `issues/1649` branch.

# Tasks

The following tasks will need to be carried out:
* [ ] Identify the required dependencies
* [ ] Add exclusions for all the transitive `groovy-*` dependencies that we don't really need
* [ ] Apply the necessary changes to the `strongbox-parent`
* [ ] Apply the necessary changes to the `strongbox-data-service`
* [ ] Apply the necessary changes to the `strongbox-cron-api` and `strongbox-cron-tasks` modules

# Task Relationships

This task:
* Relates to: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by ykabusalah** [comment]
Can I attempt doing this?

**Comment by anki2189** [comment]
We don't need `groovy-all` dependency as it pull many transitive dependencies which are not compatible with this project. Below are the required groovy dependencies.

- groovy

- groovy-json

- groovy-xml

 After https://github.com/strongbox/strongbox/pull/1701 minimum required version will be 3.0.2

**Comment by carlspring** [comment]
@anki2189 ,

Thanks for the update!

Please, bear in mind that:
* We need to make sure this works in @sbespalov 's branch for #1649 ( pull request #1676 ).
* Apparently, in IntelliJ, we need the dependencies also defined in the `strongbox-aql`.

Could you please make sure this works properly on Sergey's branch?
