### ISSUE TITLE
Sort out the Maven warnings for the org.vafer:jdeb plugin

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1711]
# Task Description

We need to sort out this warning:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.carlspring.strongbox:strongbox-distribution:pom:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.vafer:jdeb is missing. @ line 381, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

# Tasks

In order to fix this, you will need to:
* [ ]  Define the plugin in the `<pluginManagement/>` section of the [`strongbox-parent`](https://github.com/strongbox/strongbox-parent/) and explicitly define a version. 
* [ ] Set the version of the `strongbox-parent` to `1.0-PR-${your-pr-number-goes-here}`.
* [ ] Open a pull request for the fix in the `strongbox-parent`.
* [ ] Switch the modules of the `strongbox` to use the new version of the `strongbox-parent`.
* [ ] Once the acceptance test below passes, swith back the version of the `strongbox-parent` and `strongbox` to `1.0-SNAPSHOT`.

# Acceptance Test

* [ ] Building the code in the `strongbox` project with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
@ykabusalah,

Would you like to look into this?
