### ISSUE TITLE
Upgrade our mkdocs-material docker image and fix any issues

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1715]
# Task Description

We need help with migrating our documentation to [mkdocs-material - 5.0.0](https://github.com/squidfunk/mkdocs-material/issues/1498) when it is released. A live preview of the latest RC is available [here](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/).

# Tasks

The following tasks will need to be carried out:
* [x] Upgrade our docker image so it uses the latest version [ci-build-images/images/mkdocs/Dockerfile.mkdocs](https://github.com/strongbox/ci-build-images/blob/master/images/mkdocs/Dockerfile.mkdocs) and installs the correct `pip` dependencies
* [ ] Make any necessary configuration changes
* [ ] Add support `pymdownx.tabbed` in `markdown_extensions` under `mkdocs.yaml` (this requires `pymdown-extensions>=7.0`)
* [ ] Search for `todo: pymdownx.tabbed` within the project to 

# Task Relationships

This task:
* Relates to: strongbox/strongbox-docs#78

# Useful Links

* [Live RC preview](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/)
* [Material for MkDocs 5 / How to migrate](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/releases/5/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by adbjo** [comment]
Me and @rbratfors would like to pick this one up if available

**Comment by steve-todorov** [comment]
Hi @adbjo and @rbratfors! Thanks for your interest in this issue! I've assigned it to @adbjo (@rbratfors please comment so I can add you to the assignee list). Feel free to work on this, but a heads up - `mkdocs-material` version `5.0` has not been released yet. There are only `RC` versions available at the moment. :)

There are two options:
1) You should be able to do most of the work using the `RC4` version (or if a newer becomes available meanwhile). We will not merge it right away but wait for `5.0` to be released and then apply any necessary final changes that might be needed.
2) You could wait for `5.0` to be released (which might take anywhere between a few weeks and a few months) and do the work then. 

Both options are fine by me, although I believe `1)` would be better for you if you have a fixed deadline.

Please note that since you both are new contributors you would need to sign a standard [ICLA](https://strongbox.github.io/contributing.html#submitting-pull-requests) for your PR to be merged.

**Comment by rbratfors** [comment]
@steve-todorov Didn't see that I had to comment, but here I am!

**Comment by steve-todorov** [comment]
FYI @rbratfors and @adbjo - [`mkdocs-material-5.0`](https://github.com/squidfunk/mkdocs-material/releases/tag/5.0.0) has been just released :)

**Comment by carlspring** [comment]
@gluckzhang, if you're also looking for tasks to work on, let us know! Also, guys, feel free to join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by gluckzhang** [comment]
Hi @carlspring , thanks for the invitation. I am one of the TAs in the courses and I won't have time to contribute now. Maybe later I will join the project :smile:

**Comment by steve-todorov** [comment]
@adbjo , @rbratfors thank you guys for your excellent work on this task! Congratulations on your first merged PR! :) 

If you are looking for more devops related tasks - please ping me in the chat and we'll find you something!

**Comment by adbjo** [comment]
Thanks Steve, it was great working with you guys, might contribute more in the future :)
