### ISSUE TITLE
Import packages from local path (Drop Path)

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [strongbox/strongbox#1719]
# Task Description

[Inedo Proget](https://inedo.com/proget) has a nice feature called [drop path(s)](https://docs.inedo.com/docs/proget/core-concepts/feeds#drop). It is a feature to import packages to a repository from a folder mounted on the local system. The folder may be on a local drive, or on a network drive. It can be enabled per repository by selecting a folder. By default, it is scanned every 60 seconds for packages copied to the folder. There is a global switch for if packages imported by drop path can overwrite existing packages.

This is a useful feature in a couple of use cases. 
1. If you have build automation, is probably simpler to copy to a network folder rather then upload the package to the repo via the build tool(NuGet, etc). The network drive can be mapped at a system level and therefore the build tool does not have to have credentials configured to upload.
2. It is useful for bulk import of packages.
3. It is useful for the modification of packages. This is my primary use case, as I modify certain chocolatey packages.

This may not be simple to implement for every packaging type, for instance, Proget does [not support drop paths for maven packages](https://docs.inedo.com/docs/proget/feeds/maven).

I think it would be useful to have the overwrite allowed switch to be per repository and not global, as I can see the use for both.

# Tasks

The following tasks will need to be carried out:
* [ ] Determine if/how this should be implemented at all in Strongbox.
* [ ] Determine which packaging formats will work with a local import.
* [ ] Implement the general system.
* [ ] Implement for each package type selected above.

# Task Relationships

N/A for the moment

# Useful Links

* [Proget drop path documentation](https://docs.inedo.com/docs/proget/core-concepts/feeds#drop)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
@TheCakeIsNaOH thank you very much for this suggestion! We will take it into consideration at some point.
