### ISSUE TITLE
Make it possible to specify the license types of test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1723]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.TestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.ArtifactGenerator` implementations for the respective layout provider.

An artifact can have no, one, or more licenses.

# Tasks

The following tasks will need to be carried out:
* [x] Add license files for some of the most common license types, such as `Apache 2.0`, `EPL`, `MIT`, `GPLv3`, etc (cover the list from [choosealicense.com](https://choosealicense.com/licenses/)). ( @carlspring )
  * [x] Create `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` (where short name would like `Apache-2.0`, `EPL`, `MIT`, `GPLv3`, etc).
  * [x] Create a `LICENSE.md` (containing the text of the license) in each of these directories.
  * [x] Define constants for these (probably an `enum` would be best).
* [ ] Re-work the licenses annotations to use SPDX, instead of hard-coded values ( #1962 )
* [x] Make it possible to specify the license types of Maven test artifacts ( #1724 ) ( @carlspring )
* [x] Make it possible to specify the license types of NPM test artifacts ( #1725 )
* [x] Make it possible to specify the license types of Nuget test artifacts ( #1726 )
* [x] Make it possible to specify the license types of PyPi test artifacts ( #1727 )
* [ ] Make it possible to specify the license types of RPM test artifacts ( #1728 )

# Task Relationships

This is the parent task for: #1724 , #1725 , #1726 , #1727 , #1728

# Useful Links

* [Choosealicense.com](https://choosealicense.com/licenses/)
* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by AkzharkynDM** [comment]
Hello,

Would you mind if I take this as my first contribution?
I have a couple of question, this is my first time contributing so I apologize for any redundant questions.

- Regarding **strongbox-storage/strongbox-storage api/src/test/resources/licenses/${license_short_name}**:  should it be in src/test or src/main?
- Regarding **Define constants for these (probably an enum would be best)**: where should the enum class be located?

**Comment by carlspring** [comment]
Hi,

Thanks for your interest! I have already done some work on this and, as well as the one for the Maven layout provider, and will commit it today. If you wouldn't mind waiting a few hours up to s day, maybe you could pick up some of the sub-tasks?

I would like to invite you to our our [chat channel](https://chat.carlspring.org/) where we could further discuss this.

**Comment by carlspring** [comment]
@AkzharkynDM ,

I've merged #1732 into the `master`. @despoinasr will take #1723, #1726 and #1727. Feel free to look into #1728. You can join our chat channel for more details.
