### ISSUE TITLE
Make it possible to specify the license types of Maven test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1724]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.MavenTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.MavenArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Notes

FYI: Cases where an artifact might not have a license:
* Artifacts coming from Maven Central, should (in theory) all have a specified license, as it's a requirement for being able to publish an artifact. However, it is possible that some ancient versions of artifacts might not have a license.
* Some third-party (paid) licensed artifacts might not have a license defined, as they may have been manually re-packaged/deployed to an internally hosted repository.
* A proof-of-concept experiment, or other library developed for solely internal purposes.

Typical locations for `LICENSE.md` files:
* The root of the jar.
* Under `META-INF/LICENSE[.md|.txt]`

# Tasks

The following tasks will need to be carried out:
* [x] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.MavenTestArtifact`.
  * [x] Add a `licenses` property. There should be constants for these (check #1723 for more details).
  * [ ] Add a `licensesTargetPaths`. If specified, these would be a mapping for the licenses to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 for more details). If there's just one license, the default should be under `META-INF/LICENSE.md`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.artifact.generator.MavenArtifactGenerator`.
  * [ ] Make sure the produced model for the POM contains the list of `licenses`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.MavenArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a `licensesTargetPaths`.

# Task Relationships

This is a sub-task of: #1723 .

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by mv93** [comment]
can I take this up?

**Comment by carlspring** [comment]
I would rather you hold on with one. If you join 
our [chat channel](https://chat.carlspring.org/), we could discuss it.
