### ISSUE TITLE
Make it possible to specify the license types of NPM test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1725]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.NpmTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Tasks

The following tasks will need to be carried out:

* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NpmTestArtifact`.
  * [ ] Add a `LicenseConfiguration[] licenses() default {};` interface property. Use license contants from `org.carlspring.strongbox.testing.artifact.LicenseType`,
* [ ] Make the necessary changes to the `org.carlspring.strongbox.artifact.generator.NpmArtifactGenerator`.
  * [ ] Implement license file copying. If specified, these would be a mapping for the licenses via the `LicenseConfiguration` to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 and, especially, #1732  for more details). Figure out what the default locations for license files in NPM should be (most-probably in the root).
  * [ ] Make sure the produced `package.json` contains the list of `licenses`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NpmArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a licenses in different destination paths.

# Task Relationships

This is a sub-task of: #1723 . Check #1732 for details of how this was implemented for Maven.

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by despoinasr** [comment]
I am working on it.

**Comment by anki2189** [comment]
@carlspring I will pick this one if no one is working on it.

**Comment by carlspring** [comment]
Thanks, @anki2189 ! :+1:
