### ISSUE TITLE
Make it possible to specify the license types of Nuget test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1726]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.NugetTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.NugetArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Tasks

The following tasks will need to be carried out:
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NugetTestArtifact`.
  * [ ] Add a `LicenseConfiguration[] licenses() default {};` interface property. Use license contants from `org.carlspring.strongbox.testing.artifact.LicenseType`,
* [ ] Make the necessary changes to the `org.carlspring.strongbox.artifact.generator.NugetArtifactGenerator`.
  * [ ] Implement license file copying. If specified, these would be a mapping for the licenses via the `LicenseConfiguration` to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 and, especially, #1732  for more details). Figure out what the default locations for license files in Nuget should be (most-probably in the root).
  * [ ] Make sure the produced `nuspec` contains the list of `licenses`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.NugetArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a licenses in different destination paths.

# Task Relationships

This is a sub-task of: #1723 . Check #1732 for details of how this was implemented for Maven.

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)
* [Packaging License within the nupkg](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by despoinasr** [comment]
I am working on it.

**Comment by szymon-jedrzejewski** [comment]
Hi, I'd like to try solving this issue

**Comment by carlspring** [comment]
Go for it! :)

**Comment by anki2189** [comment]
@carlspring I would like to pick this one.

**Comment by steve-todorov** [comment]
It's yours! Have fun! :)

**Comment by anki2189** [comment]
licenseUrl attribute is deprecated now (link)[https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl]
