### ISSUE TITLE
Make it possible to specify the license types of Pypi test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1727]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.PypiTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.PypiArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Tasks

The following tasks will need to be carried out:
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.PypiTestArtifact`.
  * [ ] Add a `LicenseConfiguration[] licenses() default {};` interface property. Use license contants from `org.carlspring.strongbox.testing.artifact.LicenseType`,
* [ ] Make the necessary changes to the `org.carlspring.strongbox.artifact.generator.PypiArtifactGenerator`.
  * [ ] Implement license file copying. If specified, these would be a mapping for the licenses via the `LicenseConfiguration` to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 and, especially, #1732  for more details). Figure out what the default locations for license files in PyPI packages should be (most-probably in the root).
  * [ ] Make sure the produced metadata file contains the list of `licenses`. (Figure out in which files inside the package this needs to be).
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.PypiArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a licenses in different destination paths.

# Task Relationships

This is a sub-task of: #1723 . Check #1732 for details of how this was implemented for Maven.

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by despoinasr** [comment]
I am working on it.

**Comment by Gyanesha** [comment]
Hey, I would like to resolve this issue. I am new at this, so I might ask you for some guidance or some queries.

**Comment by carlspring** [comment]
Hi @Gyanesha ,

Feel free to pick it up and to join our [chat channel](https://chat.carlspring.org/).

**Comment by kpx3** [comment]
hello I would like to take this up, I am new to open source so I might need help.

**Comment by carlspring** [comment]
Hi @kpx3  ,

Feel free to pick it up and to join our [chat channel](https://chat.carlspring.org/).

**Comment by carlspring** [comment]
@kpx3 : How's it going? Any luck?

**Comment by kpx3** [comment]
a little overwhelmed i am still learning how to use maven.
i saw the related subtask. Should i use the classes you used for maven artifacts or other.
very sorry for this late reply had mid-terms

**Comment by carlspring** [comment]
Hi,

You can use them as reference of what will need to be done for the other layouts.

**Comment by kpx3** [comment]
okay I will use them for reference purposes

**Comment by anki2189** [comment]
@carlspring Pypi packages doesn't support list of licenses. https://docs.python.org/3/distutils/setupscript.html#additional-meta-data

**Comment by carlspring** [comment]
Interesting. Well, we can still add it as a list in our implementation and then just write one license and make it fail, if there are is more than one license.

**Comment by carlspring** [comment]
@anki2189 ,

Would you like to look into this?

**Comment by anki2189** [comment]
> @anki2189 ,
> 
> Would you like to look into this?

Yes, I am working on it.

**Comment by carlspring** [comment]
Excellent! Thank you! :)
