### ISSUE TITLE
Make it possible to specify the license types of RPM test artifacts

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1728]
# Task Description

It should be possible to specify under what license a generated test artifact is. This should be controllable via the implementation of the `org.carlspring.strongbox.testing.artifact.RpmTestArtifact` annotation and `org.carlspring.strongbox.artifact.generator.RpmArtifactGenerator`.

An artifact can have no, one, or more licenses. By default, it should not have one.

# Tasks

The following tasks will need to be carried out:
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.RpmTestArtifact`.
  * [ ] Add a `licenses` property. There should be constants for these (check #1723 for more details).
  * [ ] Add a `licensesTargetPaths`. If specified, these would be a mapping for the licenses to where the `LICENSE.md` files from `strongbox-storage/strongbox-storage-api/src/test/resources/licenses/${license_short_name}` should be copied to (check #1723 for more details).
* [ ] Make ithe necessary changes to the `org.carlspring.strongbox.artifact.generator.RpmArtifactGenerator`.
  * [ ] Make sure the produced metadata file contains the list of `licenses`.
* [ ] Make the necessary changes to the `org.carlspring.strongbox.testing.artifact.RpmArtifactGeneratorStrategy`.
* [ ] Add a test illustrating:
  * [ ] An artifact with no licenses.
  * [ ] An artifact with more than one licenses.
  * [ ] An artifact with a `licensesTargetPaths`.

# Task Relationships

This is a sub-task of: #1723 .

# Useful Links

* [Strongbox Developer Guide: Writing Tests](https://strongbox.github.io/developer-guide/writing-tests.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by valiobojinov** [comment]
@carlspring I can take over those license type related once

**Comment by carlspring** [comment]
@AkzharkynDM ,

Would you like to look into this?

**Comment by Jackxu9946** [comment]
Hey, Im new to open source projects and would like to try this issue. Do I need understanding of the entire strongbox library or would I be fine just understanding the files that need to be changed i.e (org.carlspring.strongbox.testing.artifact.RpmTestArtifact and org.carlspring.strongbox.artifact.generator.RpmArtifactGenerator)

**Comment by kosuruvarunkumar** [comment]
Hi, I would like to work on this.
I am new to this project, Can you please help me figure out how to start looking into this issue?
@carlspring 
@sbespalov 
@steve-todorov

**Comment by anki2189** [comment]
@carlspring `RpmArtifactGenerator` is not yet implemented, pls correct me if I am missing something.

**Comment by carlspring** [comment]
Hi,

This is on a branch. I believe the latest code was on the `rpm-layout` branch.

**Comment by carlspring** [comment]
@anki2189 ,

Would you like to pick this up? :)

**Comment by ReccaFlames** [comment]
Hello :) I would like to contribute to this if the help is still needed. I am new to this project so I would appreciate some intro if possible.
@carlspring
