### ISSUE TITLE
Research possible solutions for centralizing common documentation links

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1730]
# Task Description

Our documentation is using [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) which generates our website at https://strongbox.github.io/. Since we are using [reference links](https://github.com/strongbox/strongbox-docs#guidelines-for-contributors) in the docs, it should be, in theory, possible to create a sort of `meta` markdown page which we can include into other markdown pages. This will reduce the time we would need to spend at fixing internal/external links which could change at any time. 

Essentially the idea is to have a markdown page called `shared-reference-links.md` which contains something like this:

```
[<!-- Global links which can be shared across all pages such as links to JDK8, system requirements, etc -->]: # 

[<!-- Strongbox related links -->]: # 
[strongbox-distribution-setup]: ./user-guide/getting-started.md
[hello-strongbox-gradle]: https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-gradle
[other-commonly-used-referenced-link]: ./developer-guide/some-page.md

[<!-- External links (grouped by domain, sorted by logic or alphanumerical) -->]: # 
[<!-- Gradle links -->]: #
[gradle-homepage]: http://gradle.org/
[gradle-artifact-management]: https://docs.gradle.org/current/userguide/artifact_management.html
[gradle-build-environment]: https://docs.gradle.org/current/userguide/build_environment.html
[gradle-plugins]: https://docs.gradle.org/current/userguide/plugins.html
[gradle-using-tasks]: https://docs.gradle.org/current/userguide/tutorial_using_tasks.html
[spring-gradle-example]:https://spring.io/guides/gs/gradle/
```

Once you include it into a page you could then simply do:

```
You need to setup a [Strongbox distribution instance][strongbox-distribution-setup]
```

and it should result in a correct link:

> You need to setup a [Strongbox distribution instance](http://localhost/user-guide/getting-started.html)

# Tasks

The following tasks will need to be carried out:
* [ ] Research for any possible solutions
* [ ] Make a list of the ones which are likely to work with their pros/cons
* [ ] After we decide on a solution - create a new task.

# Notes

* You might be tempted to use `pymdown-extensions` but before you do - checkout facelessuser/pymdown-extensions#881. 
* [mkdocs_macros_plugin](https://github.com/fralau/mkdocs_macros_plugin) seems like what we might need.
* Might need to create our own plugin for mkdocs in Python? 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by aaryan078** [comment]
i would like to work on this

**Comment by aaryan078** [comment]
please explain me what i have to do i am confuse somewhat

**Comment by 2022bit002** [comment]
Hi @steve-todorov ,
I'd like to work on this issue as part of my open source contribution. Could you please assign it to me?
Thanks!
