### ISSUE TITLE
Figure out what's wrong with strongbox-web-ui build under windows

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1737]
# Task Description

It has been brought to our attention that there are some issues starting the [strongbox/strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui) project under Windows. When you do `npm run start` and try to go to `http://localhost:4200` it will produce a `404 not found` instead of actually serving the assets. This issue has been introduced with strongbox/strongbox#1691 and might be related to the reverse proxy I enabled there (maybe no windows support or a transitive package needs an update?)

Thanks @aosousa for bringing this up!

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate what's causing the issue under Windows
* [ ] Write your findings
* [ ] Open a new task issue at `strongbox/strongbox` with proper description.
* [ ] Feel free to fix the issue (finders - keepers :smile:)

# Task Relationships

This task:
* Relates to: strongbox/strongbox#1691

# Useful Links

* [Angular Backend Proxy](https://angular.io/guide/build#proxying-to-a-backend-server) (most likely causing the issue)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov

**Comment by johnnybigoode** [comment]
So the web-ui was working until -for some reason- it just wasn't anymore. 
If anyone is looking over this and is having some sort of error like this:

```
	internal/modules/cjs/loader.js:1172
		  throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
		  ^

	Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\projetos\strongbox-web-ui\node_modules\is-promise\index.js
	require() of ES modules is not supported.
	require() of C:\projetos\strongbox-web-ui\node_modules\is-promise\index.js from C:\projetos\strongbox-web-ui\node_modules\run-async\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
	Instead rename C:\projetos\strongbox-web-ui\node_modules\is-promise\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\projetos\strongbox-web-ui\node_modules\is-promise\package.json.

		at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
		at Module.load (internal/modules/cjs/loader.js:1000:32)
		at Function.Module._load (internal/modules/cjs/loader.js:899:14)
		at Module.require (internal/modules/cjs/loader.js:1042:19)
		at require (internal/modules/cjs/helpers.js:77:18)
		at Object.<anonymous> (C:\projetos\strongbox-web-ui\node_modules\run-async\index.js:3:17)
		at Module._compile (internal/modules/cjs/loader.js:1156:30)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
		at Module.load (internal/modules/cjs/loader.js:1000:32)
		at Function.Module._load (internal/modules/cjs/loader.js:899:14) {
	  code: 'ERR_REQUIRE_ESM'
	}
```

Use `npm install node@12.11.1` to get it to work. This seems to be related by the reply provided [here](https://github.com/manuelbieh/geolib/issues/208#issuecomment-595461630) and it seems to be a [nodejs thing about running EC Modules](https://dev.to/exacs/practical-guide-node-js-12-supports-es-modules-are-your-apps-ready-5gi). 

PS.: You may find that there [are other solutions](https://stackoverflow.com/questions/57169793/error-err-require-esm-how-to-use-es6-modules-in-node-12) using `--experimental-modules`. Doing that led me to new errors

```
internal/modules/cjs/loader.js:619
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /C:/projetos/strongbox-web-ui/node_modules/is-promise\package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:576:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:616:20)
    at applyExports (internal/modules/cjs/loader.js:505:14)
    at resolveExports (internal/modules/cjs/loader.js:543:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\projetos\strongbox-web-ui\node_modules\run-async\index.js:3:17) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strongbox-web-ui@0.0.0 start: `ng serve --aot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strongbox-web-ui@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dione\AppData\Roaming\npm-cache\_logs\2020-04-25T16_23_23_790Z-debug.log

```

**Comment by steve-todorov** [comment]
Thanks for sharing @johnnybigoode! I'm using `node@v12.16.2` on a Linux machine - haven't bumped into the issue you are mentioning above but I assume somebody using a lower version might.

**Comment by johnnybigoode** [comment]
Here's the kicker then:
If I try using `"node": "^12.16.2",`  I'll get the same problem. 
Maybe it's a Windows 10 thing?

**Comment by steve-todorov** [comment]
Hi @Echidna93 and thanks for your interest in this issue! @johnnybigoode has already made a PR and it fixed the issue. I'll need to `rebase` it and merge it, but unfortunately I haven't had a chance to do that since I'm working on another task right now.
