### ISSUE TITLE
Extract `UserEntity.roles` into standalone vertex

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1753]
# Task Description
Within #1649  it was found that `IN` operator has some issues with `cypher-for-gremlin` query interpreter and this affects on `UserRepository.findUsersWithRole(String role)` query. Another thing is that such query implementation most likely not optimal for using indexes when searching users by role.
The solution to avoid the `IN` operator issue and to use indexes for user by role search is to extract roles into standalone Vertex. 

The `SecurityRole` vertex should be `many-to-many` with `User` vertex with `UserHasSecurityRoles` edge and have following properties:
- uuid (example: `ADMIN`)

The work for this will have to be based on the `issue-1649` branch.

# Tasks

The following tasks will need to be carried out:
* [ ] Create `SecurityRole` and `UserHasSecurityRoles` elements in `StrongboxSchema`
* [ ] Create entity classes
* [ ] Create `SecurityRoleRepository`
* [ ] Create `SecurityRoleService` with `findOneOrCreate` method (see: `ArtifactTagService#findOneOrCreate` as an example)
* [ ] Rework  `UserEntity.roles` property so that it refers to the set of `SecurityRole` vertices
* [ ] Rework `UserRepository.findUsersWithRole(String role)` taking into account  `SecurityRole`

# Task Relationships

This task:
* Is a follow-up of: #1744 
* Relates to: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by rtandle04** [comment]
Hi Sergey,
Can I work on this.

I have 2+ Years of experience in java related technologies, JPA, Hibernate and Ibatis

Regards,
Ramakanth.

**Comment by anki2189** [comment]
@carlspring I am working on this .

**Comment by carlspring** [comment]
@anki2189 , @sbespalov ,

I assume that this task can now nowbe closed?

**Comment by anki2189** [comment]
Yes, we should close this task now.
