### ISSUE TITLE
Get rid of RemoteArtifact inheritance

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1761]
# Task Description
Within current implementation we have `RemoteArtifact` entity inherided from `Artifact` entity. Both entities have the `uuid` index which affects on JG commit performance when adding new entities. We could drop this inheritance and put `cached` attribute dirrectly into `Artifact` entity for the sake of performance.

# Tasks

The following tasks will need to be carried out:
* [x] Moove `cached` attribute to `Artifact` entity
* [x] Drop the `RemoteArtifact` entity
* [x] Rework `RemoteArtifact` specific logic

# Task Relationships

This task:
* Is a sub-task of:  #1754

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
fixed
