### ISSUE TITLE
Upgrade to Cassandra to 4.0-alpha4 or higher

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1775]
# Task Description

We should consider upgrading to `org.apache.cassandra:cassandra-all:4.0-alpha4`, as it can help us with our performance issues.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a branch off `issues/1649` against strongbox/strongbox-parent and bump the version.
* [ ] Sort out the issues that pop up.
* [ ] Check how it affects the build times of `strongbox-against-strongbox`.
* [ ] Investigate how [the vulnerabilities reported by Snyk.io against this version of `cassandra-all`[(https://snyk.io/vuln/maven:org.apache.cassandra:cassandra-all) could be fixed.

# Task Relationships

This task:
* Is a sub-task of: #1649

# Useful Links

* [Cassandra 4.0-alpha4: Benchmarking streaming](https://cassandra.apache.org/blog/2019/04/09/benchmarking_streaming.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
@carlspring above PRs are now latest related with #1775 and #1111.  All the other branches and PRs could be closed and deleted. I've rebased all to corresponding #1649 branches. The `spring-boot:run` with embedded cassandra works well for me. Next will check standalone cassandra and distribution.
The only issue I have for now is that I was forced to delete some Jersey customizations related with [SB-888](https://youtrack.carlspring.org/issue/SB-888) because of broken backward compatibility after Jersey version upgrade. So we'll need to revisit SB-888 and check how it works with new Jersey version.

**Comment by steve-todorov** [comment]
Thanks for the update @sbespalov! 

What is the issue you've found with Jersey? Is this the last remaining issue with #1775 and #1111 or there are others?
I assume it's related to @ptirador 's recent changes in https://github.com/strongbox/strongbox-parent/pull/106. Maybe he can help you out? :)

**Comment by sbespalov** [comment]
not sure what was the issue but I've restored the jersey related changes and now it seems works fine. so never mind with this :)

**Comment by carlspring** [comment]
Could this task now be closed, or is there anything that still needs to be done?

Are the two sub-tasks (above) still relevant and what is their status:
* [ ] Check how it affects the build times of `strongbox-against-strongbox`.
* [x] Fix our `wrapper.conf` problems with the Tanuki wrapper for the `strongbox-distribution`, or replace the Tanuki wrapper with a different solution such as Spring Boot's approach.

**Comment by steve-todorov** [comment]
We are not using `Tanuki` anymore so this can be removed / checked. I'll trigger an `sb-against-sb` task to check if it all works, but this task should be closed since we upgraded to 4.0-beta2 a while ago.

**Comment by carlspring** [comment]
Okay, please, follow-up on this task and close it, when you have checked things. Thanks!
