### ISSUE TITLE
Fix the test failures in the ParallelDownloadRemoteArtifactTest under JDK11

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1782]
# Task Description

Under JDK11, on the `issues/1649` branch, we are getting the following test failure (for tests which are otherwise passing under JDK8):
```
00:40:39.823 | E | Thread-27  | o.c.s.s.ArtifactManagementService     | Failed to create OutputStream.
java.io.IOException: Failed to create OutputStream.
	at org.carlspring.strongbox.io.LazyOutputStream.init(LazyOutputStream.java:90)
	at org.carlspring.strongbox.io.LazyOutputStream.write(LazyOutputStream.java:50)
	at java.base/java.nio.file.Files.write(Files.java:3429)
	at org.carlspring.strongbox.services.ArtifactManagementService.lambda$writeChecksums$0(ArtifactManagementService.java:184)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.carlspring.strongbox.services.ArtifactManagementService.writeChecksums(ArtifactManagementService.java:180)
	at org.carlspring.strongbox.services.ArtifactManagementService.writeArtifact(ArtifactManagementService.java:157)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:110)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:100)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$3ac94441.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:105)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:76)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:91)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:72)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:282)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:91)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
Caused by: org.carlspring.strongbox.providers.io.RepositoryRelativePathConstructionException: 
	at org.carlspring.strongbox.providers.io.RepositoryPath.validateParent(RepositoryPath.java:358)
	at org.carlspring.strongbox.providers.io.RepositoryPath.getParent(RepositoryPath.java:106)
	at org.carlspring.strongbox.providers.io.RepositoryPath.getParent(RepositoryPath.java:34)
	at java.base/java.nio.file.Files.createDirectories(Files.java:766)
	at org.carlspring.strongbox.providers.layout.LayoutFileSystemProvider.lambda$newOutputStream$1(LayoutFileSystemProvider.java:137)
	at org.carlspring.strongbox.io.LazyOutputStream.init(LazyOutputStream.java:82)
	... 33 common frames omitted
00:40:39.824 | E | Thread-27  | o.c.s.s.ArtifactManagementService     | Failed to create OutputStream.
java.io.IOException: Failed to create OutputStream.
	at org.carlspring.strongbox.io.LazyOutputStream.init(LazyOutputStream.java:90)
	at org.carlspring.strongbox.io.LazyOutputStream.write(LazyOutputStream.java:50)
	at java.base/java.nio.file.Files.write(Files.java:3429)
	at org.carlspring.strongbox.services.ArtifactManagementService.lambda$writeChecksums$0(ArtifactManagementService.java:184)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.carlspring.strongbox.services.ArtifactManagementService.writeChecksums(ArtifactManagementService.java:180)
	at org.carlspring.strongbox.services.ArtifactManagementService.writeArtifact(ArtifactManagementService.java:157)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:110)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:100)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$3ac94441.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:105)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:76)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:91)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:72)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:282)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:91)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
Caused by: org.carlspring.strongbox.providers.io.RepositoryRelativePathConstructionException: 
	at org.carlspring.strongbox.providers.io.RepositoryPath.validateParent(RepositoryPath.java:358)
	at org.carlspring.strongbox.providers.io.RepositoryPath.getParent(RepositoryPath.java:106)
	at org.carlspring.strongbox.providers.io.RepositoryPath.getParent(RepositoryPath.java:34)
	at java.base/java.nio.file.Files.createDirectories(Files.java:766)
	at org.carlspring.strongbox.providers.layout.LayoutFileSystemProvider.lambda$newOutputStream$1(LayoutFileSystemProvider.java:137)
	at org.carlspring.strongbox.io.LazyOutputStream.init(LazyOutputStream.java:82)
	... 33 common frames omitted
00:40:39.838 | E | Thread-27  | o.c.s.p.io.RepositoryStreamSupport    | Failed to close [/java/opensource/carlspring/strongbox-clean/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/pdrat-repository/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar].
java.io.IOException: [TempRepositoryPath] target for [/java/opensource/carlspring/strongbox-clean/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/pdrat-repository/.temp/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar] don't exists!
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.moveFromTemporaryDirectory(StorageFileSystemProvider.java:365)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$TempOutputStream.close(StorageFileSystemProvider.java:676)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at org.carlspring.commons.io.MultipleDigestOutputStream.close(MultipleDigestOutputStream.java:170)
	at org.carlspring.strongbox.io.LayoutOutputStream.close(LayoutOutputStream.java:125)
	at org.carlspring.strongbox.io.LazyOutputStream.close(LazyOutputStream.java:68)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.carlspring.strongbox.providers.io.RepositoryStreamSupport$RepositoryOutputStream.close(RepositoryStreamSupport.java:202)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:113)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:100)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$3ac94441.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:105)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:76)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:91)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:72)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:282)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:91)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
00:40:39.838 | E | Thread-27  | o.c.s.p.r.ProxyRepositoryProvider     | Failed to resolve Path for proxied artifact [/java/opensource/carlspring/strongbox-clean/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/pdrat-repository/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar]
java.io.IOException: [TempRepositoryPath] target for [/java/opensource/carlspring/strongbox-clean/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/pdrat-repository/.temp/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar] don't exists!
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.moveFromTemporaryDirectory(StorageFileSystemProvider.java:365)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$TempOutputStream.close(StorageFileSystemProvider.java:676)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at org.carlspring.commons.io.MultipleDigestOutputStream.close(MultipleDigestOutputStream.java:170)
	at org.carlspring.strongbox.io.LayoutOutputStream.close(LayoutOutputStream.java:125)
	at org.carlspring.strongbox.io.LazyOutputStream.close(LazyOutputStream.java:68)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.carlspring.strongbox.providers.io.RepositoryStreamSupport$RepositoryOutputStream.close(RepositoryStreamSupport.java:202)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:113)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:100)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$3ac94441.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:105)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:76)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:91)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:72)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:282)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:91)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
java.io.IOException: [TempRepositoryPath] target for [/java/opensource/carlspring/strongbox-clean/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/pdrat-repository/.temp/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar] don't exists!
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.moveFromTemporaryDirectory(StorageFileSystemProvider.java:365)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$TempOutputStream.close(StorageFileSystemProvider.java:676)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
	at org.carlspring.commons.io.MultipleDigestOutputStream.close(MultipleDigestOutputStream.java:170)
	at org.carlspring.strongbox.io.LayoutOutputStream.close(LayoutOutputStream.java:125)
	at org.carlspring.strongbox.io.LazyOutputStream.close(LazyOutputStream.java:68)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.apache.commons.io.output.ProxyOutputStream.close(ProxyOutputStream.java:116)
	at org.carlspring.strongbox.providers.io.RepositoryStreamSupport$RepositoryOutputStream.close(RepositoryStreamSupport.java:202)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:113)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:100)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$3ac94441.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:105)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:76)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:91)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:72)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:282)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:91)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
java.io.IOException: org.carlspring.strongbox.artifact.ArtifactNotFoundException: Artifact [strongbox:/storage0/pdrat-repository/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar] not found.
	at org.carlspring.strongbox.providers.io.RepositoryStreamSupport$RepositoryInputStream.<init>(RepositoryStreamSupport.java:254)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.decorate(AbstractRepositoryProvider.java:118)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.getInputStream(AbstractRepositoryProvider.java:102)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.getInputStream(AbstractRepositoryProvider.java:47)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$4cc9f99c.getInputStream(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.getInputStream(ArtifactResolutionServiceImpl.java:51)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:36)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
Caused by: org.carlspring.strongbox.artifact.ArtifactNotFoundException: Artifact [strongbox:/storage0/pdrat-repository/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar] not found.
	at org.carlspring.strongbox.providers.io.RepositoryStreamSupport$RepositoryInputStream.<init>(RepositoryStreamSupport.java:245)
	... 10 more
Started [Thread-31]
java.lang.NullPointerException: Repository should be provided
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:44)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:83)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:58)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:84)
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
Started [Thread-32]
java.lang.NullPointerException: Repository should be provided
00:40:39.865 | W | 1-worker-1 | c.c.CronTasksConfigurationFileManager | Skip resource store [class path resource [etc/conf/strongbox-cron-tasks.yaml]]
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:44)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:83)
	at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:58)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:84)
00:40:39.877 | I | 1-worker-3 | o.c.s.gremlin.dsl.EntityTraversalDsl  | Created [Artifact]-[807080]-[storage0-injector-releases-7-rhicst-org/carlspring/properties-injector/1.8/properties-injector-1.8-javadoc.pom]
	at org.carlspring.strongbox.testing.artifact.ArtifactResolutionServiceHelper.assertStreamNotNull(ArtifactResolutionServiceHelper.java:32)
	at org.carlspring.strongbox.providers.repository.ParallelDownloadRemoteArtifactTest$WorkerThread.run(ParallelDownloadRemoteArtifactTest.java:177)
...
[ERROR] Failures: 
[ERROR]   ParallelDownloadRemoteArtifactTest.testConcurrentDownload:125 
Expecting:
 <false>
to be equal to:
 <true>
but was not.
[ERROR] Errors: 
[ERROR]   RepositoryHostedIndexCreatorSearchTest.shouldBeCapableToSearchByJavadoc » IllegalState
[INFO] 
```

Please, note that:
* This test will most-likely pass, if executed on its own in an IDE. It will have to be executed together with all the other parallel tests in the `strongbox-storage-maven-layout-provider` in order to be reproduced.
* The work for this should be done on branch created off the `issues-1775-jdk11` branch.

It might be helpful to play with the [`junit.jupiter.execution.*`](https://junit.org/junit5/docs/snapshot/user-guide/) options in the `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/src/test/resources/junit-platform.properties`.

# Tasks

The following tasks will need to be carried out:
* [ ] Re-enable `ParallelDownloadRemoteArtifactTest` and investigate the issues.
* [ ] Investigate and fix the issue.
* [ ] Test with JDK11.
* [ ] Test with JDK8.

# Task Relationships

This task:
* Is a sub-task of: #1111

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by yusufaslancaliskan** [comment]
Hey, May I help you on this ?

**Comment by carlspring** [comment]
Yes, please! Try and reproduce it and please join our [chat channel](https://chat.carlspring.org/).

**Comment by Rama000777** [comment]
@carlspring  iam getting this issue in this branch. (issues/1649)

Is this the new issue with jdk 11?

01:44:34.933 | E | 1-worker-3 | o.j.g.database.StandardJanusGraph     | Could not commit transaction [1] due to storage exception in system-commit
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception

caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.janusgraph.core.JanusGraph]: Factory method 'JanusGraph' threw exception; nested exception is java.lang.IllegalArgumentException: The transaction has already been closed
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 175 common frames omitted
Caused by: java.lang.IllegalArgumentException: The transaction has already been closed

**Comment by carlspring** [comment]
This looks like a different error. What's the complete utput of `mvn --version`?

**Comment by Rama000777** [comment]
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by carlspring** [comment]
Could you please paste the complete output?

**Comment by Rama000777** [comment]
D:\fullstack\strongbox>mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\apps\maven\bin\..
Java version: 11.0.9, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.9
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Rama000777** [comment]
out log from mvn clean install

[output.txt](https://github.com/strongbox/strongbox/files/5470624/output.txt)

**Comment by Rama000777** [comment]
@carlspring is this my local issue or need to be fixed? Please let us know whether i can continue this task ?

**Comment by carlspring** [comment]
This appears to be a different error. Are you testing this in your own foek, or against our `issues/1649` branch? If it's a fork, perhaps you need to sync and rebase it. You can join our [chat channel](https://chat.carlspring.org/).

@sbespalov : Do your JDK 11 fixes work under Windows?

**Comment by sbespalov** [comment]
it should work

**Comment by steve-todorov** [comment]
This test seems to have been fixed in `issues/1649` so the issue is obsolete. Closing it. Thanks to all participants! :)
