### ISSUE TITLE
Strongbox instance startup fails on jdk11

### ISSUE THREAD

**Issue by anki2189** [strongbox/strongbox#1785]
# Task Description

Strongbox instance startup fails while running `mvn spring-boot:run` in `stronbox-web-core` in the `issues-1775` branch.

**Stacktrace**

```
	... 171 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedDbServer': Invocation of init method failed; nested exception is java.lang.RuntimeException: Unable to start the embedded DB server!
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 185 common frames omitted
Caused by: java.lang.RuntimeException: Unable to start the embedded DB server!
	at org.strongbox.db.server.EmbeddedJanusGraphWithCassandraServer.start(EmbeddedJanusGraphWithCassandraServer.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 198 common frames omitted
Caused by: java.lang.RuntimeException: Exception encountered during startup
	at org.apache.cassandra.service.CassandraDaemon.exitOrFail(CassandraDaemon.java:784)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:680)
	at org.strongbox.db.server.EmbeddedJanusGraphWithCassandraServer.provideCassandraInstance(EmbeddedJanusGraphWithCassandraServer.java:82)
	at org.strongbox.db.server.EmbeddedJanusGraphWithCassandraServer.start(EmbeddedJanusGraphWithCassandraServer.java:57)
	... 205 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1151)
	at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:558)
	at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:348)
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:176)
	at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:160)
	at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:695)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:639)
	... 207 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@493d8aa7/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @63cd2cd2)
	at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:96)
	... 214 common frames omitted
Caused by: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@493d8aa7/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @63cd2cd2)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2206)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2146)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2290)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2283)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1747)
	at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:85)
	... 214 common frames omitted
```

# Tasks

The following tasks will need to be carried out:
* [x] Find out the root cause for exception.
* [x] Apply the fix to the `strongbox-web-core`.
* [ ] Apply the fix to the `strongbox-distribution`.

# Task Relationships

This task:
* Is a sub-task of: #1111

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
I will try to debug this.

**Comment by anki2189** [comment]
There was an issue raised in cassandra for this https://issues.apache.org/jira/browse/CASSANDRA-15468.

Cassandra tries to access jdk internal classes via Reflection and in jdk11 they have put strict checks on internal classes access.

Workaround provided was pass internal class as jvm argument using `--add-exports --add-opens` option.

**Comment by anki2189** [comment]
So, now to run strongbox we have to use below command with `jdk11`

```mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Djdk.attach.allowAttachSelf=true --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.management.rmi/com.sun.jmx.remote.internal.rmi=ALL-UNNAMED --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED --add-exports java.sql/java.sql=ALL-UNNAMED  --add-opens java.base/java.lang.module=ALL-UNNAMED --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/jdk.internal.math=ALL-UNNAMED --add-opens java.base/jdk.internal.module=ALL-UNNAMED --add-opens java.base/jdk.internal.util.jar=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
```

**Comment by carlspring** [comment]
Can we add these parameters to the `spring-boot` plugin?

**Comment by sbespalov** [comment]
fixed with #1924
