### ISSUE TITLE
Repositories generated using the @MavenRepository do not set the basedir variable

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1789]
# Bug Description

When using the `@MavenRepository` (and most-likely the other similar test annotations for NPM, Nuget, PyPi, etc) does not set a value for the `basedir`, which then makes it impossible to get the path to the base directory of the repository.

# Steps To Reproduce

Given:
```java
@ActiveProfiles(profiles = "test")
@SpringBootTest
public class MavenRepositoryAnnotationTest
{

    private static final String REPOSITORY_RELEASES_REMOTE = "releases-remote";

    @ExtendWith({ RepositoryManagementTestExecutionListener.class,
                  ArtifactManagementTestExecutionListener.class })
    @Test
    public void testIncrementalUpdate(@MavenRepository(repositoryId = REPOSITORY_RELEASES_REMOTE)
                                      Repository repositoryRemote)
    {
        ...
    }
```
You should be able to do:
```java
    String repositoryBaseDir = repository.getBasedir();
```

However, this currently returns `null`.

# Expected Behavior

This should return the correct path to the repository's base directory.

# Tasks

* [ ] Investigate and fix this for the `@MavenRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@NpmRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@NugetRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@PypiRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@RpmRepository` annotation, along with a test case.
* [ ] Investigate and fix this for the `@RawRepository` annotation, along with a test case.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov

**Comment by indhupriya** [comment]
@carlspring @sbespalov Can I take a shot at this?

**Comment by carlspring** [comment]
@indhupriya ,

I believe @anki2189 may already be working on this. @anki2189 , have you, or do you plan on working on this?

@indhupriya ,

Feel free to join our [chat channel](https://chat.carlspring.org/) for more details. I'm sure we can find you some tasks to work on, if you like.
