### ISSUE TITLE
Rework `UserController.getUsers` method so that it takes `skip` and `limit` parameters

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1796]
# Task Description

Current implementation fetches all users from DB, which wont work well in real life. We should be able to paginate users on UI with `skip` and `limit` parameters.

# Tasks

The following tasks will need to be carried out:
* [ ] Create `UserRepository.findUsers(Long skip, Integer limit)` method (see `ArtifactIdGroupQueries.findArtifacts` as example)
* [ ] Rework  `UserController.getUsers` to use `UserRepository.findUsers` with `skip` and `limit` parameters
* [ ] Provide Unit Tests for `UserController.getUsers`

# Task Relationships

This task:
* Is a sub-task of: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
@steve-todorov this will also require some work on UI

**Comment by anki2189** [comment]
I would like to pick the backend part of this task.

**Comment by carlspring** [comment]
That's great! Please, proceed! Thanks!

**Comment by anki2189** [comment]
@sbespalov Should we keep default value of `skip` and `limit` or make it mandatory param in `UserController`.?
