### ISSUE TITLE
Storage provider naming refactoring

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1797]
# Task Description

Currently, we have only one storage provider -- the `org.carlspring.strongbox.providers.datastore.FileSystemStorageProvider`. This is the default provider and it writes directly to the file system (on the hard disk). We need to make this more flexible for future implementations that might be working with cloud providers, for example.

We have a registry called `org.carlspring.strongbox.providers.datastore.StorageProviderRegistry`.

We need to carry out a refactoring in order to improve the names of certain classes and make things clearer to use.

# Tasks

The following tasks will need to be carried out:
* [x] Rename the `org.carlspring.strongbox.providers.datastore` package to `org.carlspring.strongbox.providers.storage`.
* [x] Rename the `dataStore` property in `strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.yaml` to `storageProvider`.
* [x] Rename the `implementation` property to `storageProvider` in:
  * [x] `org.carlspring.strongbox.storage.repository.Repository`
  * [x] `org.carlspring.strongbox.storage.repository.RepositoryData`
  * [x] `org.carlspring.strongbox.storage.repository.RepositoryDto`
* [x] Drop the `org.carlspring.strongbox.providers.datastoragee.StorageProviderEnum` class. This should be much more dynamic and it should not be done via an `enum`. Wherever, there's a need to fallback to the default disk file system implementation, replace this with `org.carlspring.strongbox.providers.datastorage.FileSystemStorageProvider`.
* [x] Fix the `strongbox-web-integration-tests`.
* [x] Fix the UI:
  * [x] https://github.com/strongbox/strongbox-web-ui/blob/master/src/app/modules/storage-management/pages/manage-repository/manage-repository.component.html#L31
  * [x] https://github.com/strongbox/strongbox-web-ui/blob/master/src/app/modules/storage-management/pages/manage-repository/manage-repository.component.ts#L65

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
