### ISSUE TITLE
Investigate ways to use custom id generator for JG

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1800]
# Task Description

JanusGraph uses the storage backend to `coordinate` multiple instances. Each node needs to be configured to `allocate` a `block` of `ids` to be used when inserting new data ([`ids.block-size`](https://docs.janusgraph.org/basics/configuration-reference/#ids)). Although this is a cleaver way to avoid `id` collision between different JG instances and removes the need of a `coordinator` (i.e. ZooKeeper), this approach introduces a few possibly deal braking issues.

### The "right" amount of `ids`

You need to closely monitor your system and set the "right" amount of `ids` which are expected to be used at a hourly rate. 
This task becomes nearly impossible because the `ids` you would use on a hourly rate **can** and **will** vary all the time.
To make matters worse - the [`ids.block-size`](https://docs.janusgraph.org/basics/configuration-reference/#ids) is marked as ([`GLOBAL_OFFLINE`](https://docs.janusgraph.org/basics/configuration-reference/#mutability-levels)) which states:

> These options can only be changed for the entire database cluster at once when all instances are shut down

This implies that in order for you to change the parameter - you need to stop **THE ENTIRE JANUSGRAPH CLUSTER**.
It also eliminates the possibility of writing an algorithm which dynamically changes this value based on collected data.

### Performance degradation due to allocation

There are two issues which are caused by allocating the ids is:
1. If you set the `block-size` too high - each instance in the cluster will try to allocate a big `block` of `N ids` causing performance degradation 
2. If you set the `block-size` too low - each instance in the cluster can have it's `id pool` exhausted faster than the instance itself can allocate causing performance degradation.

### Wasted `ids` 

If you decide to over provision `ids` to be "save", you can also run out of `ids`. Of course this depends on how much you over provision, but the theoretical max IDs you can have in JG is `1,000,000,000,000,000,000`. If you set the `block-size` to something like `10M` and you use `1M` but then you need to `restart` the instance - you will end up with `9M` wasted `ids`.
These `ids` cannot be `re-claimed` nor are `re-used` by any instance ever again. This effectively reduces the [`theoretical size limit`](https://docs.janusgraph.org/basics/technical-limitations/#size-limitation) with each restart. If you do weekly maintenance restarts and have a cluster 10 machines - with the above example you would have `90M` wasted ids since when you upgrade the Strongbox instance you would need to go over all 10 machines (`10 machines * 9m wasted ids = 90m`)

Note: It is possible for us to use `JG server` which is deployed at the same machine as the database which will fix the `id` waste. However we will need  to use `Gremlin server` and that might cause totally separate set of performance issues. 

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate ways to use a custom vertex id generator ([`graph.set-vertex-id`](https://docs.janusgraph.org/basics/configuration-reference/#graph))
* [ ] Is it possible to replace the `long` vertex id with `UUID` which is tied to the JG instance id (`graph.unique-instance-id`) ?
* [ ] Make a small PoC project which uses JG and a custom vertex id generator based on the research (could use  https://github.com/strongbox/strongbox-janusgraph-cassandra-poc as a starting point)
  * [ ] Make a test which generates IDs and checks for collision with existing ids

# Task Relationships

This task:
* Relates to: #1649 

# Useful Links

* [JanusGraph Configuration Reference](https://docs.janusgraph.org/basics/configuration-reference)
* [Gitter Chat Answer](https://gitter.im/janusgraph/janusgraph?at=5ef6885347fdfd21ede9986d)
* [StackOverflow Question](https://stackoverflow.com/questions/62604410/is-there-a-way-to-use-uuids-instead-of-id-block-allocation-in-janusgraph) 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
Hey @ptirador, I hear you are interested in this task? (no pressure) :D

**Comment by carlspring** [comment]
> Hey @ptirador, I hear you are interested in this task? (no pressure) :D

You mean he was volunteered, right? :-D

**Comment by ptirador** [comment]
Hey @steve-todorov @carlspring! Sure, I'll look into it!

**Comment by ptirador** [comment]
@steve-todorov:


Custom Long vertex ids are supported in JanusGraph. Note that only Long ids are supported and they must be converted to valid JanusGraph ids for use in `g.addVertex(T.id, id)`. [JavaDoc](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java#L91-L97) for this `addVertex` method specifies that:


- Custom id setting must be enabled via the configuration option `org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration#ALLOW_SETTING_VERTEX_ID`.
- Valid JanusGraph vertex ids must be provided. An exception is thrown if the vertex id is not a valid JanusGraph vertex id or if a vertex with the given id already exists. Only accepts long ids - all others are ignored. 
- Use `org.janusgraph.graphdb.idmanagement.IDManager#toVertexId(long)` to construct a valid JanusGraph vertex id from a user id, where `idManager` can be obtained through 
`org.janusgraph.graphdb.database.StandardJanusGraph#getIDManager()`.

```
long vertexId = ((StandardJanusGraph) graph).getIDManager().toVertexId(userVertexId);
```

I've found an example using custom id assignment in the own tests of JG project:

https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/VertexIDAssignerTest.java#L226

**Comment by steve-todorov** [comment]
Thanks for your investigation @ptirador! This aligns with what I've found as well. Can you do some digging and find the places where the `IDManager` is being used? Maybe we could introduce different `IDManager`s depending on the configured options?

**Comment by carlspring** [comment]
Would it be possible to re-work this in the Janusgraph code base so that we could have the multiple "providers" (implementations) of these ID-s? For example, `LongIdManager` and `UUIDIdManager`.

I understand that this is outside the scope of our project and that it might be a big chunk of work on the side of Janusgraph.

What are our options here? For large instances, (such as what we hope ours could be), there will be a big loss of ID-s which will never be reclaimable with the current implementation. In addition to this, it simply takes too much time to allocate a set of ID-s.

Could you perhaps try to assess how much work would be required if we were to re-work this ID allocating functionality so that it can support multiple implementations?

Can we draft some sort of requirements with more technical details and maybe raise an issue with the JanusGraph folks (they also have a chat channel)? I mean -- if we were to implement this, we would need the JG folks to be happy to sign off on it, so that it could be merged into their codebase. We can't have our own fork of JG.

@sbespalov , @steve-todorov , @ptirador : What are your thoughts?

**Comment by ptirador** [comment]
@steve-todorov, @carlspring, @sbespalov:

As you can see in the [IdManager](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/IDManager.java) class, it's exclusively based on long ids. I think that this could be re-worked to allow multiple implementations depending on type, but I'm not sure of the final impact of these changes (I don't know much about the project). This class used in a lot of places throughout the project and this will be needed to analyze further to see all that implies.

**Comment by carlspring** [comment]
Thanks, @ptirador !

Would you like to have a closer look at the Janusgraph codebase and investigate this further?

**Comment by carlspring** [comment]
@sbespalov ,

Would you like to share your thoughts about this?

**Comment by sbespalov** [comment]
I don't think that id generator could cause any tangible performance degradation for us. The only problem that could be is loosing some id ranges while restarting JG server, but with for example 5k ids batch size it won't be a big problem as well.

**Comment by sbespalov** [comment]
anyway, regarding the string Vertex ids we probably could use current `IdManager` contract and make long hash from UUID string.

**Comment by sbespalov** [comment]
there is also [issues/1221](https://github.com/JanusGraph/janusgraph/issues/1221) for String ids in JG

**Comment by steve-todorov** [comment]
### Thoughts

> Most likely N block size won't mean that you will receive every ID number, but just the range limits.

It seems like you are right on point! Thanks for pointing me in this direction! I looked at the sources yesterday and the database - it confirms your thoughts. This query also gives longs from the cassandra database:

`SELECT blobAsVarint(key), blobAsVarint(column1), value FROM strongbox.janusgraph_ids`

> @steve-todorov why do you think that this will affect on performance? 

It really depends on the amount of data you will be inserting and how fast you will be exhausting the pool. 
Looking at the JG source code and through experiments I've came to the following conclusions on how the ID allocation works:

1. Initially JG will create about 4 blocks in the `janusgraph_ids` table. These seem to be system related - I am not entirely sure what they do, but I assume it's related to the JG schema and internals which are "hidden" from the user. 
2. It asynchronously allocates id blocks/ranges when the first insert happens.
3. It asynchronously allocates id blocks/ranges when you reach the `renew-percentrage` (where 0.3 means `70%` used IDs)
4. `ids.num-partitions >= 1` will create `N` partitions of id blocks/ranges (not sure it this is `ids.block-size / ids.num-partitions` or `ids.num-partitions * ids.block-size`). The higher the number of partitions - the better the concurrency throughput should be since you have more partitions available for the threads requesting IDs.
5. By default, JG will run using `ConflictAvoidanceMode.NONE` (no collision checks - fine when you have a single JG instance). 
6. For multiple JG instances running in a cluster - you will need to deal with ID conflicts/collisions between instances. This is done by using `ConflictAvoidanceMode.GLOBAL_MANUAL` which does `global-quorum-level` checks - meaning 51% of the nodes storing the ids need to reply for a request to be "successful" (necessary to increase the consistency level since C* is eventually consistent).
7. Setting `ids.block-size` too low will make transaction commits frequently block on slow reservation requests. (taken from the docs)
8. Setting `ids.block-size` too high will result in IDs wasted when a graph instance shuts down with reserved but mostly-unused blocks. (taken from the docs)
9. Once you have configured the "id generator" you cannot switch another one because `graph.set-vertex-id` is FIXED, meaning configured for life (which is expected). 
10. If we decide to implement UUID ids at a later stage - any existing production databases will need to be manually migrated. 

I should note `reads` in Cassandra are a bit slower than `writes` - you can insert 100k in under 1s, but reading 100k will likely take 2-3 seconds). 
Combining this knowledge with the huge amount of artifacts we will be getting from feeds/indexes - it is inevitable performance will suffer because of the id allocation. After all - in order to allocate an id block you need do a trip to the db, read the existing ones, do a conflict avoidance at a quorum level which takes more time than usual "read" operations and only then allocate it. And for each time you do this id allocation for a partition block - you will loose time.

Here are some numbers from the experiments I have done so far:

| ids.block-size | ids.num-partitions | sb-against-sb/NO cron tasks/cold | sb-against-sb/NO cron tasks/cold -T4 |
| -------------: | :----------------: | :------------------------------: | :----------------------------------: |
|             10 |         3          |            17:42 min             |              18:30 min               |
|             25 |         3          |            08:07 min             |              08:10 min               |
|             50 |         3          |            05:22 min             |              05:11 min               |
|            100 |         3          |            04:51 min             |              04:05 min               |
|           1000 |         3          |            04:05 min             |              ~03:25 min              |
|           5000 |         3          |            03:53 min             |              ~03:20 min              |
|         10,000 |         3          |            03:49 min             |              ~03:15 min              |
|        100,000 |         3          |            03:40 min             |              ~03:20 min              |
|      1,000,000 |         3          |            03:44 min             |              ~03:25 min              |
|     10,000,000 |         3          |            03:50 min             |              ~03:20 min              |

At this moment we have roughly `2000` dependencies. The numbers above illustrate the performance impact of the build when you haven't properly configured the `block size`. They clearly show that:

1. Having a non-balanced configuration will result in poor performance. 
2. Having a balanced number will result in a pretty decent performance.
   This will cost you having to keep an eye on the cluster all the time and re-balance when needed
3. Having a way too big number doesn't seem to have any performance effect other than the potential wasted IDs upon restarts.

Some data for upstream indexes to bring more context (not entirely accurate, but rather approximate)

``` 
     15,000,000 - Maven Central size (includes all versions)
      3,591,848 - DockerHub images (1 image is on average ~= 20 layers = 21 artifacts)
     75,428,808 - Actual DockerHub artifacts we would need to store (DockerHub images * 21)
      2,394,902 - nuget artifact versions(based on nuget.org/packages count in 2020)
      1,500,000 - npmjs packages (they were 1m in 2019; this is an estimated guess)
      2,000,000 - pypi
          6,090 - ubuntu 20.04 focal (64bit) 
          4,495 - ubuntu 20.04 focal (32bit) 
=====================================================                
     99,926,143 - roughly estimated artifacts from upstream indexes
```



### Conclusion:

I believe this is going to be a problem for us. We can figure out ways to mitigate it by increasing the nodes in the cluster, however the cron tasks are still going to be causing issues unless we limit the hourly inserts which will increase the time needed to sync the local db with the upstream index. 

Right now, we could put this on-hold since it's not an immediate issue, but in the long term we should think about ways to use UUIDs instead of Long. The benefits of doing this are:

* No need to deal with possible id range collisions between different instances, because
* UUIDs were specially designed to be used in Distributed Computing Environments for Apollo. If we use them correctly by ensuring each instance has a unique `instance id` then I believe we should be fine.
* No trips to the database = less time waiting.

The downside of this is - we will need to implement it ourselves and it probably won't be that easy, because JG expects Longs everywhere. If we find a way to convert namespaced UUIDs to Longs without ID collision issues as @sbespalov suggested - we could use `graph.set-vertex-id = true` and then assign the vertex id manually. This would be much easier and faster than re-writing JG's internal code.

**Comment by sbespalov** [comment]
To avoid id allocation using storage backend, the following options are possible in JG:
1. Use `IDManager.toVertexId(long id)` and make corresponding changes within strongbox-data-service (requires `graph.set-vertex-id` option to be enabled)
   
    This is the easiest way which won't require any changes in JG. We could get the unique IDs using `long` hash from `UUID` value. Changes need to be done for `EntityTraversalDsl#addV` method so it should use `org.apache.tinkerpop.gremlin.structure.Graph.addVertex(Object... keyValues)` to add vertices with manually assigned ID.

2. Try to implement custom `IDAuthority` and then contribute to JG

    This seems possible in general but will require approvement form JG developers. The only difference with `.1`  is that IDs will be provided by JG and this will not require support within the application. 

3. Support `UUID` type for IDs on JG side
    
    This will require massive changes on JG side and and it seems unrealistic to do only with our efforts.

**Comment by carlspring** [comment]
https://tools.ietf.org/html/rfc4122#section-3

**Comment by carlspring** [comment]
@steve-todorov ,

Here's an issue @sbespalov found that's related to this research JanusGraph/janusgraph/issues/1514.

**Comment by sbespalov** [comment]
Regarding the options above probably the only reasonable for us now is `2.` It could take few weeks to be done, including conversations with JG team.

Last research shows that `1.` will require JG improvements as well ([janusgraph/issues/1514](https://github.com/JanusGraph/janusgraph/issues/1514)) and this makes that option a losing one compared to the `2.`, and the `3.` is still to complex and does not seem possible to implement.

**Comment by carlspring** [comment]
In my opinion, we'll need janusgraph/issues/1514 either way, regardless of which option we pick. This is correct, right, @sbespalov ?

**Comment by sbespalov** [comment]
with `2.` we don't need this, it needed only for `1.`

**Comment by carlspring** [comment]
Right, would you mind clarifying why?

**Comment by sbespalov** [comment]
because with `1.` we need to provide IDs manually and [`JanusGraph/janusgraph#1514](https://github.com/JanusGraph/janusgraph/issues/1514) is about manual assigned IDs
with `2.` we don't need to manually assign IDs, so it don't need [`JanusGraph/janusgraph#1514](https://github.com/JanusGraph/janusgraph/issues/1514)
