### ISSUE TITLE
Enable test ConfigurableProviderManagerTest#testExternalUserShouldBeReplacedWhenExpired

### ISSUE THREAD

**Issue by anki2189** [strongbox/strongbox#1802]
# Task Description
Currently testcase `ConfigurableProviderManagerTest#testExternalUserShouldBeReplacedWhenExpired` is failing with reason 

```
Expecting:
<"test-concurrent">
to be equal to:
<"test-duplicate">
```

# Tasks

The following tasks will need to be carried out:
* [ ] Find root cause of failure
* [ ] Apply fix to fix
* [ ] Enable test case.

# Task Relationships

This task:
* Is a follow-up of: #1753 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
Thanks for reporting this! Closing in favor of #1988 :)
