### ISSUE TITLE
Disable our Quartz cron tasks

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1806]
# Task Description

We need to disable Quartz, so that it doesn't start up the cron tasks below. At the moment we have bigger issues to debug and this is getting the way. We will have a follow-up task at a later time to re-enable these.

Optimally, this should be controllable via a property in the `strongbox.yaml`. Quartz provides a property for this as well.

### List of Cron jobs to be disabled at runtime
* [x] `org.carlspring.strongbox.cron.jobs.DownloadRemoteFeedCronJob`
* [x] `org.carlspring.strongbox.cron.jobs.DownloadRemoteMavenIndexCronJob`
* [x] `org.carlspring.strongbox.cron.jobs.FetchRemoteNpmChangesFeedCronJob`

# Task Relationships

This task:
* Relates to: #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
List of Cron jobs and tests.

- CleanupExpiredArtifactsFromProxyRepositoriesCronJobTestIT
- DownloadRemoteMavenIndexCronJobTestIT
- ImmediateExecutionCronJobTestIT
- FetchChangesFeedCronJobTestIT
- MergeMavenGroupRepositoryIndexCronJobTestIT
- OneTimeExecutionCronJobTestIT
- RebuildMavenIndexesCronJobTestIT
- RebuildMavenMetadataCronJobTestIT
- RegenerateMavenChecksumCronJobTestIT
- RegenerateNugetChecksumCronJobTestIT
- RemoveTimestampedMavenSnapshotCronJobTestIT
- ClearTrashCronJobFromMaven2RepositoryTestIT


- CleanupExpiredArtifactsFromProxyRepositoriesCronJob
- ClearRepositoryTrashCronJob
- DownloadRemoteFeedCronJob
- DownloadRemoteMavenIndexCronJob
- FetchRemoteNpmChangesFeedCronJob
- GroovyCronJob
- MergeMavenGroupRepositoryIndexCronJob
- RebuildMavenIndexesCronJob
- RebuildMavenMetadataCronJob
- RegenerateChecksumCronJob
- RemoveTimestampedMavenSnapshotCronJob

**Comment by carlspring** [comment]
@anki2189 ,

Are you interested in picking this up?

**Comment by anki2189** [comment]
Yes, will pick this task.

**Comment by carlspring** [comment]
Great! Thank! :)

**Comment by steve-todorov** [comment]
@anki2189 I've made some modifications to the task description. We need to disable the listed cron tasks at runtime by default - not to disable **all** cron tasks and their tests.
