### ISSUE TITLE
Implement a service for managing Quartz

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1807]
# Task Description

We need to be able to enable and disable Quartz programatically via a service class.

We currently have the `strongbox-cron` modules for the common cron task related code. 

# Tasks

The following tasks will need to be carried out:
* [ ] Make it possible to enable/disable Quartz programmatically via a service class.
* [ ] The configurations should be stored in the `strongbox.yaml`.
* [ ] Implement some tests for this.

# Task Relationships

This task:
* Relates to: #1806 , #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by anki2189** [comment]
Currently some of the cron jobs(which are creating problem) have hard coded cron expression, we should provide cron expression using `storage:repository:repositoryConfiguration` from `strongbox.yaml`. 
We can introduce new field **cronEnabled**  in `storage:repository:repositoryConfiguration` to manage Quartz Job.

**Comment by carlspring** [comment]
This sounds reasonable to me. Would you like to look into it?

**Comment by anki2189** [comment]
Sure , @carlspring

**Comment by carlspring** [comment]
Thanks! :)

**Comment by steve-todorov** [comment]
@anki2189 your suggestion sounds like a totally separate task. The current task is aiming at actually having a way to disable cron tasks globally for cases where you might be running into issues. Furthermore - there is a `strongbox-cron-tasks.yaml` file which holds all of the configuration for the cron tasks. It would make more sense to store any related configuration there like `cronTaskConfiguration.enabled: true|false` for globally enabling|disabling all cron tasks. This should be the task at hand.

---

Looking over the `strongbox-cron-tasks.yaml` in the distribution I don't see a field `enabled` per cron task:
```
  - uuid: "7de372ad-2592-4853-940b-8c7d0146e13a"
    name: "Remote feed download for storage-common-proxies:nuget.org"
    jobClass: "org.carlspring.strongbox.cron.jobs.DownloadRemoteFeedCronJob"
    cronExpression: "0 0 0 * * ?"
    oneTimeExecution: false
    immediateExecution: true
    properties:
      repositoryId: "nuget.org"
      storageId: "storage-common-proxies"
```

I know for sure there is a method `enabled` in each of these java classes (i.e. `DownloadRemoteMavenIndexCronJob`), but I don't know if it has been mapped to the actual property in the configuration file. If it isn't mapped - we should create an additional task for this since it will be needed. Afterwards, your would be possible and we can create another task to improve our existing `cron task` endpoints to be able to `disable|enable` all cron tasks for a specific repository by looping through the matching records in the `strongbox-cron-task.yaml`.
