### ISSUE TITLE
Storage refactoring

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1808]
# Task Description

We need to re-think and improve our storage implementation.

This is the master task.

# Tasks

The following tasks will need to be carried out:
* [ ] Storage provider naming refactoring ( #1797 )
* [ ] Make the artifact generators use the associated storage provider for the repository.
* [ ] Each storage should have an associated `storageProvider` and this should be the default for each repository in it.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
