### ISSUE TITLE
Storage provider module refactoring

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1811]
# Task Description

We need to create a separate aggregator for storage providers and extract the default (`local`) storage provider into a s separate module below it.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new aggregator under `strongbox-storage` called `strongbox-storage-providers`.
* [ ] Extract the default storage provider (`org.carlspring.strongbox.providers.storage.FileSystemStorageProvider`) into a separate sub-module under `strongbox-storage-providers` called `strongbox-local-storage-provider`.
* [ ] Apply any required changes to `pom.xml` changes to affected projects.

# Task Relationships

This task:
* Is a sub-task of: #1808 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
