### ISSUE TITLE
Reduce the use of File, FileInputStream, FileOutputStream and path existence checking with alternatives from Files where possible

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1814]
# Task Description

As part of the storage and repository refactoring, we need to reduce the use of the following as much as possible and replace it with respective implementations from `Files`:
- `new File(...)` with `basePath.resolve(path)` (where `path` is a `String`)
- `File.exists(...)` with `Files.exists(path)`
- `new FileInputStream(...)` with `Files.newInputStream(path)`
- `new FileOutputStream(...)` with `Files.newOutputStream(path)`

# Tasks

The following tasks will need to be carried out:
* [x] Re-work the `MavenArtifactGenerator`.
* [x] Re-work the `NugetArtifactGenerator`.
* [x] Re-work the `NpmArtifactGenerator`.
* [x] Re-work the `PypiArtifactGenerator`.
* [x] Re-work the `RawArtifactGenerator`.
* [x] Re-work the `RpmArtifactGenerator`.

# Task Relationships

This task:
* Is a sub-task of: #1808 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by svaddadhi** [comment]
Hey, could I takeover this issue?

**Comment by carlspring** [comment]
@svaddadhi ,

Thanks for offering to help! That would be great! I've already done some work on re-working the `MavenArtifactGenerator` already. Perhaps you could have a look at how I've done it and apply similar fixes to the rest of the `ArtifactGenerator` implementations...?

For more details, please join our [chat channel](https://chat.carlspring.org/).

**Comment by svaddadhi** [comment]
That sounds great @carlspring , I will go ahead and get working on that, and I will join the chat channel as well

**Comment by carlspring** [comment]
We should have a discussion on the chat first.

**Comment by vjtadepalli** [comment]
Hi, I would like to contribute. How to get started?

**Comment by AlexanderSherrow** [comment]
Hello! I'd like to contribute too if theres anything I could help with!

**Comment by carlspring** [comment]
Guys, thanks for offering to help! Please, join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by KamilSynowiec** [comment]
Hi, do you still need some help?

**Comment by rakeswain** [comment]
Hi, Can I contribute to this issue?

**Comment by aminnb** [comment]
Hi, I would like to contribute to this issue. Do you still need help?

**Comment by carlspring** [comment]
Guys, you can just go ahead nad pick this up and proceed with it.

**Comment by liooh** [comment]
Hi,I would like to work in the task, however I don't understand the pipeline:

 Re-work the MavenArtifactGenerator. 
 Re-work the NugetArtifactGenerator.
 Re-work the NpmArtifactGenerator.
 Re-work the PypiArtifactGenerator.
 Re-work the RawArtifactGenerator.
 Re-work the RpmArtifactGenerator.

**Comment by luan-cestari** [comment]
I just opened a PR https://github.com/strongbox/strongbox/pull/1892 for MavenArtifactGenerator . I will wait the pipeline to check all the changes necessary to continue

**Comment by luan-cestari** [comment]
As the old PR closed, I opened a new one: https://github.com/strongbox/strongbox/pull/1919

**Comment by luan-cestari** [comment]
Updated the PR to do all points of this issue, by the way there is no RpmArtifactGenerator or similar for RPM and for P2 there isn`t as well

**Comment by carlspring** [comment]
Please, ignore the P2 layout provider, as it was started and never completed. You are also right about the `RpmArtifactGenerator`. We have some active work the the RPM support a while ago, but the contributor who was working with me disappeared, so we have the code for this on a separate branch -- `rpm-layout-provider`. You can check [here](https://github.com/strongbox/strongbox/blob/rpm-layout-provider/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-rpm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/RpmArtifactGenerator.java) for more details. If you would like to fix it for this as well, you'll need to create a separate pull request for it against the `rpm-layout-provider` branch.

**Comment by carlspring** [comment]
@luan-cestari ,

Would you like to look into the `RpmArtifactGenerator`, as explained above?

**Comment by carlspring** [comment]
I've had a quick look at the [`RpmArtifactGenerator`](https://github.com/strongbox/strongbox/blob/rpm-layout-provider/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-rpm-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator/RpmArtifactGenerator.java) class and it looks like there's nothing to do there.

Thanks for your help, @luan-cestari ! :)
