### ISSUE TITLE
Write documentation for our test artifact generators, test artifact and test repository annotations

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1815]
# Task Description

We need to document how to use the `@TestArtifact` and `@TestRepository` (and their alias annotations for the various layout providers) work.

The page should be placed under the [`Developer's Guide`](https://strongbox.github.io/developer-guide/) under the `Writing Tests` and be called `Test Repository And Test Artifact Annotations`.

# Tasks

The following tasks will need to be carried out:
* [ ] Add documentation for the various implementations of the `ArtifactGenerators` for each of the layour providers.
* [ ] List and document the available implementations for the supported layout providers, along with some examples of how to use them (`MavenRepository`, `MavenTestArtifact`, `NugetRepository`, `NugetTestArtifact`, `NpmRepository`, `NpmTestArtifact`, `PypiRepository`, `PypiTestArtifact`, `RawRepository`, `RpmRepository`, `RpmTestArtifact`).
* [ ] Add some notes for the `TestArtifactContext`.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by simrandeep11** [comment]
@carlspring 
I would like to contribute on this. Let me know how to get started on this.

**Comment by carlspring** [comment]
@simrandeep11 ,

You could start by taking a look at the classes mentioned above and writing an article in the `strongbox-docs` project as mentioned in the task's description.

**Comment by Tapan123456** [comment]
This looks interesting I can get started on this

**Comment by simrandeep11** [comment]
Ok I will have a look and get back.

**Comment by simrandeep11** [comment]
@carlspring 
I had a glance over the code and I am sorry I will not be able to devote sufficient time for this task right now as I am occupied with some important office work for next 2 weeks. 
@Tapan123456 
If you are still interested you can take over.

**Comment by ZivGrin** [comment]
I would love to try helping this project, may I?

**Comment by carlspring** [comment]
Hi @ZivGrin ,

Feel free to give it a go and to join our [chat channel](https://chat.carlspring.org/)!

**Comment by pp2411** [comment]
hey! I wanted to work on thi issue. may I ?

**Comment by carlspring** [comment]
Hi!
Feel free to do so!

**Comment by kanwarpreet25** [comment]
hey! Can I help on this issue ?

**Comment by Radhika14soni** [comment]
Hi! I would like to contribute. Can I help on this issue?

**Comment by carlspring** [comment]
@kanwarpreet25 , @Radhika14soni ,

Have you guys had a look at the code mentioned above? That's the starting point. Have you built the project?

**Comment by sophiya02** [comment]
Hi!. I am totally new to contributing to open source, even though I have forked some repositories but this is going to be my first technical contribution. Can I fork this repository and have a look at the documentation part?

**Comment by KuhanPrakash** [comment]
Hi, is anyone working on this atm,  can I contribute to this?

**Comment by sakshi2207** [comment]
Hi, @steve-todorov is this issue closed? I have gone through the documentation there i find the Test Repository and Test Artifact already there. Is there anything that I can do? If you could give me some context I would like to work on it.

**Comment by manthanindane** [comment]
hey, is anyone currently working on this issue? I would love to contribute

**Comment by carlspring** [comment]
I would recommend you pick another project.

**Comment by manthanindane** [comment]
Okay...thanks

**Comment by AbdelatefM** [comment]
I would like to contribute on this. Let me know how to get started on this.
