### ISSUE TITLE
 Maximum upload size exceeded

### ISSUE THREAD

**Issue by julienmnr** [strongbox/strongbox#1819]
# Original Bug Description

For a work project I had to set up a strongbox repository with which I would look for sources via chocolatey.
So I have to configure this one with the right URL for the push etc.
But when wanted to push my package with my nupkg file I got this error message in my strongbox log file.
I am therefore looking to be able to increase my maximum upload size exceeded
Can you help me please ?

![error 2](https://user-images.githubusercontent.com/69256279/89436647-ccb02580-d746-11ea-9329-38379f780637.PNG)

# Feature Request

It should be possible to define:
* The maximum allowed size of uploaded artifacts globally, (for all repositories)
* Disable the maximum allowed size of uploaded artifacts globally, (for all repositories)
* The maximum allowed size of uploaded artifacts for a repository (this should override the global setting, if enabled.
* Disable the maximum allowed size of uploaded artifacts for a repository

# Tasks

* [ ] Check if Spring allows you to disable the `spring.http.multipart.max-file-size` property.
* [ ] Implement support for this in the `org.carlspring.strongbox.controllers.configuration.ServerConfigurationController`.
* [ ] Implement support for this in the `org.carlspring.strongbox.controllers.configuration.StoragesConfigurationController`.
* [ ] Implement support for this in the `org.carlspring.strongbox.controllers.BaseArtifactController` (and/or wherever necessary in the controllers that inherit this class).
* [ ] Make the necessary change to the respective classes in the `strongbox-web-forms`.
* [ ] Add support for this in the UI (via the [`strongbox-web-ui`](https://github.com/strongbox/strongbox) project).
* [ ] Add new tests to the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project that cover the generation and upload of large artifacts.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
Hi,

So, how large is your file?

**Comment by carlspring** [comment]
Also, please don't ever take screenshots of consoles and copy & paste the output instead.

**Comment by julienmnr** [comment]
Yes sorry for the screenshot , my package is large like 120MB

**Comment by carlspring** [comment]
What is the exact command you executed and the full output (on both the client side and the server side)?

**Comment by carlspring** [comment]
@anki2189 ,

Would you like to look into this?

**Comment by steve-todorov** [comment]
I believe we should be able create a dummy 1G file and include it in the `nuspec`. It looks like you can define a [`<files>`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-assembly-files) section which points to the file and it should get included in the  package (I assume, but have not tested it). 

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata minClientVersion="100.0.0.1">
        <id>dasdas</id>
        <version>2.0.0</version>
        <title />
        <authors>dsadas</authors>
        <owners />
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
    <files>
        <file src="content\one.txt" target="content\one.txt" />
    </files>
</package>
```

**Comment by julienmnr** [comment]
Hello back, I just want to push with this : choco push --source "%REPO_URL%" --force

**Comment by julienmnr** [comment]
Hi, do you have any update ?

Regards,

**Comment by carlspring** [comment]
Hi Julien,

There is no update on this. The issue is up for grabs, if you would like to work on it and fix it. We appreciate pull requests very much! :)

**Comment by julienmnr** [comment]
I search to much to fixe it but I find nothing.. 
But ok thanks anyway.

**Comment by carlspring** [comment]
You should be able to configure this via the `application.yaml` file. Have a look at these links:
* https://spring.io/guides/gs/uploading-files/#:~:text=constrained%20as%20follows%3A-,spring.,file%20size%20cannot%20exceed%20128KB.
* https://stackoverflow.com/questions/40271484/spring-upload-file-size-limit

**Comment by anki2189** [comment]
> I search to much to fixe it but I find nothing..
> But ok thanks anyway.

@julienmnr : Can you please test your use case against PR (https://github.com/strongbox/strongbox/pull/1822)
Before testing you have to change values for `max-file-size` and `max-request-size` in `application.yaml` according to your file size.

**Comment by julienmnr** [comment]
Hi anki, application.yaml is a file of Spring ?

**Comment by carlspring** [comment]
@julienmnr ,

You will have to update the `application.yaml` with a value for the max size and then build the code from pull request #1822 and install Strongbox from the produced zip in the `strongbox/strongbox-distribution/target` directory.

**Comment by anki2189** [comment]
> Hi anki, application.yaml is a file of Spring ?

No, application.yaml of Strongbox which is located at `strongbox-commons/src/main/resources/application.yaml`

**Comment by navkumar258** [comment]
Hi, looking for my first contribution - is the issue still open or is someone working on it or can i take it. thanks :smile:

**Comment by julienmnr** [comment]
> > Salut anki, application.yaml est un fichier de Spring?
> 
> Non, application.yaml de Strongbox qui se trouve à `strongbox-commons/src/main/resources/application.yaml`

Idk why I dont have this folder in my strongbox.. I dont see strongbox-commons idk why

**Comment by carlspring** [comment]
> Hi, looking for my first contribution - is the issue still open or is someone working on it or can i take it. thanks

@navkumar258 ,

Thanks for offering to help, but, as you can see, @anki2189 is already working on it. Please, feel free to join our [chat channel](https://chat.carlspring.org/) to find out how you help with other tasks.

**Comment by carlspring** [comment]
> > > Salut anki, application.yaml est un fichier de Spring?
> > 
> > 
> > Non, application.yaml de Strongbox qui se trouve à `strongbox-commons/src/main/resources/application.yaml`
> 
> Idk why I dont have this folder in my strongbox.. I dont see strongbox-commons idk why

@julienmnr ,

This project is not French-speaking. We all speak English here.

As I explained earlier, if you would like to try out the pull request, you will have to checkout the code and build it from the pull request that @anki2189 has proposed.

**Comment by julienmnr** [comment]
> > > > Salut anki, application.yaml est un fichier de Spring?
> > > 
> > > 
> > > Non, application.yaml de Strongbox qui se trouve à `strongbox-commons/src/main/resources/application.yaml`
> > 
> > 
> > Idk why I dont have this folder in my strongbox.. I dont see strongbox-commons idk why
> 
> @julienmnr ,
> 
> This project is not French-speaking. We all speak English here.
> 
> As I explained earlier, if you would like to try out the pull request, you will have to checkout the code and build it from the pull request that @anki2189 has proposed.

Man calm down no ? It’s just my google chrome who corrected the sentence in French okay ?

**Comment by carlspring** [comment]
> Man calm down no ? It’s just my google chrome who corrected the sentence in French okay ?

Just thought I'd let you know. :)

**Comment by julienmnr** [comment]
Hi all, thanks to @anki2189  for its solution, this one was the right one and everything worked well, thanks again.

**Comment by carlspring** [comment]
> Hi all, thanks to @anki2189 for its solution, this one was the right one and everything worked well, thanks again.

@julienmnr : This was a temporary solution. @anki2189 will work on a more permanent configurable solution.

**Comment by mohamedelkashif** [comment]
@anki2189 Started on it.

**Comment by PayalSainathMehta** [comment]
Hi I would like to contribute to this.

**Comment by carlspring** [comment]
@mohamedelkashif : Any progress...? :)

**Comment by carlspring** [comment]
This task is now up for grabs.

**Comment by JanBucko** [comment]
Hello, i woult like to take a shot on this :)

**Comment by carlspring** [comment]
Hi @JanBucko 

Feel free to pick it up!

**Comment by JanBucko** [comment]
Thank you. Just one last question, could you please point me towards classes where the uploading is handled ?

**Comment by carlspring** [comment]
Have a look at the `BaseArtifactController` and the extending classes.

**Comment by JanBucko** [comment]
Thank you very much :)

**Comment by JanBucko** [comment]
Hi, I was trying to add support for this change to the Web UI, I have forked and cloned the project with the local spring boot server running but when I started ng serve and opened my browser on localhost:4200 I came across an error: Cannot GET /static/assets is there anything I forgot to do before starting the angular dev server ?

**Comment by steve-todorov** [comment]
@JanBucko can you please ping me in the [chat](https://chat.carlspring.org)? This might be because of a build issue under windows (if you are running Windows). You can try if this fixes it for you  https://github.com/strongbox/strongbox-web-ui/pull/40. If not - ping me in the chat.

**Comment by carlspring** [comment]
> @steve-todorov Thank you, your suggestion has solved my problem, but now I am once again battling with the integration tests inside server - ImmediateExecutionCronJobTestIT keeps failing for the reason: Error creating bean with name 'genericReleaseVersionValidator' which goes down to NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.MultipartConfigElement', which is the bean that I have overriden inside class StorageMultipartConfig I have tried to add '@ContextConfigurationAnnotation' but then some other beans get broken, could you help me with that @carlspring please ?

@sbespalov , @ptirador : Any thoughts on this? :)

**Comment by ptirador** [comment]
> > @steve-todorov Thank you, your suggestion has solved my problem, but now I am once again battling with the integration tests inside server - ImmediateExecutionCronJobTestIT keeps failing for the reason: Error creating bean with name 'genericReleaseVersionValidator' which goes down to NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.MultipartConfigElement', which is the bean that I have overriden inside class StorageMultipartConfig I have tried to add '@ContextConfigurationAnnotation' but then some other beans get broken, could you help me with that @carlspring please ?
> 
> @sbespalov , @ptirador : Any thoughts on this? :)

I've added some new comments on https://github.com/strongbox/strongbox/pull/1914, I think it'll fix it.

**Comment by steve-todorov** [comment]
@sbespalov / @ptirador please correct me if I'm wrong, but isn't there a missing `servlet filter` part in this task's description? The `controller` is being called way too far in the pipeline and at that point the request would have received the entire file only to "deny" it. I believe there should be a filter in the beginning and directly deny the request once the `content-length` is bigger than the configured so that the request fails before the entire file is sent to the server. What are your thoughts?

**Comment by JanBucko** [comment]
I was avare of this possible problem when I was figuring out the solution, but in case of embedded tomcat server that comes with spring boot, shouldnt be the servlet limit also configured ?

**Comment by steve-todorov** [comment]
We have replaced Tomcat with Jetty in our use case. Spring has `spring.servlet.multipart.max-file-size=1234` which can be configured for this. But you'd need to hardcode it into the `application.yaml` file. I was thinking that maybe we can use a placeholder `spring.servlet.multipart.max-file-size=${strongbox.max-file-size}` which can be taken from `strongbox.yaml`, but I am not entirely sure if we can change the `spring.servlet.multipart.max-file-size` property at runtime

(you'd need to be able to change it at runtime, because if you change the parameter through the UI it shouldn't require a full restart; this would lower high availability)

**Comment by JanBucko** [comment]
As far as I know spring.servlet.multipart.max-file-size is only used to configure MultipartConfig element which is then being used through the app. Am I wrong ?

**Comment by sbespalov** [comment]
@steve-todorov I think @JanBucko doing it right. We also could have MVC test to confirm that `MultipartConfigElement` works well.

**Comment by JanBucko** [comment]
Hello, @sbespalov. I am planning to add them soon.

**Comment by carlspring** [comment]
@JanBucko / @sbespalov ,

Does the verification happen before, or after the payload has been uploaded? If so, then, as @steve-todorov suggested (in a chat), it might be too late for us, as we're uploading artifacts (some of which might be quite large) and we would like for this to fail early, rather than late, as failing late will mean incurred bandwidth and elapsed time. Could you please check and confirm this?

If this check indeed happens only after the payload has been sent, then we might be better off checking the content size via the `Content-Length` header.

What do you guys think?

**Comment by JanBucko** [comment]
@carlspring The verification is running before the file is fully loaded.

**Comment by JanBucko** [comment]
@carlspring However I can additionally try to add header filter that attempts to find content-length header in request and if such header present, I can reject enormous request, but in the other case when that header wouldn't be present we would have to rely on SpringBoot multipart file handling after all.

**Comment by carlspring** [comment]
I don't think that either of the tools whose layout providers we have implemented don't support the `Content-Length` header. It's a critical pre-requisite for uploading binaries to a repository.

In my opinion, we should implement both the filter and have the Spring Boot check as a fallback.

You have to keep in mind that it might not be a big deal to fail late when you're uploading to on-premise hardware, if you are running in the cloud there will be an incurred incoming traffic cost from this failure and we should do our best to avoid this.

I believe that the `Content-Length` check will catch the majority of the cases and fail early. In the rare cases where we have wild cowboys uploading using `curl` (or some other tool that I can't currently guess), then the Spring Boot check will be a reasonable fallback.

**Comment by JanBucko** [comment]
Okay I'll have a look on that :)

**Comment by carlspring** [comment]
Thank you very much! :)

**Comment by JanBucko** [comment]
Hello, I apologize for the delay but it should be done now.

**Comment by JanBucko** [comment]
Hello, I am sorry for the delay, but the filter is now implemented and working.

**Comment by carlspring** [comment]
Thanks, @JanBucko !

@ptirador , @sbespalov , @steve-todorov : Could you please review? Thanks! :)

**Comment by carlspring** [comment]
@JanBucko ,

Any reason why you've closed these pull requests?

**Comment by kmeet** [comment]
Hello,

Looking for my first contribution with this issue, specifically these points:

- Implement support for this in the org.carlspring.strongbox.controllers.configuration.ServerConfigurationController.
- Implement support for this in the org.carlspring.strongbox.controllers.configuration.StoragesConfigurationController.
- Implement support for this in the org.carlspring.strongbox.controllers.BaseArtifactController (and/or wherever necessary in the controllers that inherit this class).

Can I work on it?

**Comment by carlspring** [comment]
@JanBucko ,

What happened with your pull requests for this issue? Would you like to pair up with @kmeet ?

**Comment by JanBucko** [comment]
Hello, I apologise, but I can't work on this issue currently due to lack of time, surely @kmeet could use changes that I've already made to the controllers if he wants to.

**Comment by chayan-blip** [comment]
Hi @steve-todorov, I want to work on this issue...... I am a beginner in oss.... can you please guide me on this?

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by carlspring** [comment]
No, thanks for offering to help, though.

**Comment by HimanshuKhatarkar** [comment]
Hi @carlspring  If this Issue is resolved please close the ticket. If not I can help you with it. please let me know.
