### ISSUE TITLE
Upgrade the versions of the tools we use in the strongbox-web-integration tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1825]
# Task Description

We need to upgrade the versions of the tools that we use in the [strongbox-web-integration-tests]. This is the master task to cover this work.

# Tasks

The following tasks will need to be carried out:
* [x] Upgrade the version of Chocolatey in [strongbox-web-integration-tests] to the latest ( #1826 )
* [x] Upgrade the version of Gradle in [strongbox-web-integration-tests] to the latest ( #1827 )
* [x] Upgrade the version of NPM in [strongbox-web-integration-tests] to the latest ( #1828 )
* [x] Upgrade the version of Nuget in [strongbox-web-integration-tests] to the latest ( #1829 )
* [x] Upgrade the version of SBT in [strongbox-web-integration-tests] to the latest ( #1830 )

# Useful Links

* [ci-build-images]
* [strongbox-web-integration-tests]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @steve-todorov
  * @carlspring
  * @sbespalov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

**Comment by carlspring** [comment]
Thanks for all the help! :)
