### ISSUE TITLE
Upgrade the version of Chocolatey in strongbox-web-integration to the latest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1826]
# Task Description

As part of #1825 , we need to upgrade the version of Chocolatey in [strongbox-web-integration-tests] to the latest.

# Tasks

The following tasks will need to be carried out:
* [x] Update [ci-build-images] to use the latest version of Chocolatey for Linux.
* [x] Rebuild the images for Chocolatey.
* [x] Check if all the tests in the [strongbox-web-integration-tests] still pass.

# Task Relationships

This task:
* Is a sub-task of: #1825

# Useful Links

* [strongbox-web-integration-tests]
* [ci-build-images]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

**Comment by tanvimehta** [comment]
Can I pick up this task?

**Comment by carlspring** [comment]
Hi @tanvimehta ,

I believe that @avinash28196 is already working on this in strongbox/ci-build-images#17. Are you familiar with Chocolatey? If you are, please feel free to dig in! If you like, you can try out @tanvimehta 's changes and try to further improve his work, by helping to figure out the issue he's facing? Thanks!

Alternatively, feel free to pick up another issue, or to give us a shout on the channel.

**Comment by j4ckofalltrades** [comment]
@carlspring I'd like to take this on, please assign to me when convenient.

**Comment by carlspring** [comment]
Thanks! Feel free to dig in and good luck! :)

**Comment by carlspring** [comment]
Thanks, @j4ckofalltrades ! :)
