### ISSUE TITLE
Upgrade the version of Gradle in strongbox-web-integration to the latest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1827]
# Task Description

As part of #1825 , we need to upgrade the version of Gradle in [strongbox-web-integration-tests] to the latest.

# Tasks

The following tasks will need to be carried out:
* [ ] Update [ci-build-images] to use the latest version of Gradle for Linux.
* [ ] Rebuild the images for Gradle.
* [ ] Check if all the tests in the [strongbox-web-integration-tests] still pass.

# Task Relationships

This task:
* Is a sub-task of: #1825

# Useful Links

* [strongbox-web-integration-tests]
* [ci-build-images]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

**Comment by shambhand** [comment]
@carlspring I would like to work on this issue

**Comment by j4ckofalltrades** [comment]
@carlspring Can you assign this to me if no one else has picked it up?

**Comment by carlspring** [comment]
@j4ckofalltrades : Done! Thanks! Feel free to pick up the other such tasks as well.

**Comment by carlspring** [comment]
> @carlspring I would like to work on this issue

@shambhand : I'm sorry, I've only just seen your comment offering to help! Please, feel free to pick up one of our other tasks! :)
