### ISSUE TITLE
Upgrade the version of Nuget in strongbox-web-integration to the latest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1829]
# Task Description

As part of #1825  , we need to upgrade the version of Nuget in [strongbox-web-integration-tests] to the latest.

# Tasks

The following tasks will need to be carried out:
* [ ] Update [ci-build-images] to use the latest version of Nuget for Linux.
* [ ] Rebuild the images for Nuget.
* [ ] Check if all the tests in the [strongbox-web-integration-tests] still pass.

# Task Relationships

This task:
* Is a sub-task of: #1825

# Useful Links

* [strongbox-web-integration-tests]
* [ci-build-images]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

**Comment by j4ckofalltrades** [comment]
@carlspring Is it okay if I take this on?

**Comment by carlspring** [comment]
Hi,

Yes, please!
