### ISSUE TITLE
Create pages for hackfests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1834]
# Task Description

We need to add pages for hackfests, especially now, with the Grace Hopper Opensource Day and #Hacktoberfest beiing right around the corner.

# Tasks

The following tasks will need to be carried out:
* [x] Create a new section in the wiki for Hackfests
* [x] Create a new generic page for hack fests
* [x] Create a new page for Grace Hopper Celebration Opensource Day
* [x] Create a new page for Hacktoberfest
* [ ] Update the `README.md` to point to the wiki.

# Useful Links

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
