### ISSUE TITLE
Add documentation on how to upgrade dependencies and plugins

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1835]
# Task Description

We need to add a page in our wiki that clearly defines how to upgrade Maven dependencies and plugins, as well as how to test if things are really working properly after an upgrade.

# Tasks

The following tasks will need to be carried out:
* [x] Add a page that outlines the steps that will need to be taken.
* [x] Create a new issue template for this.
* [x] Update all of our existing tasks in our issue tracker to have a link to this page.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
