### ISSUE TITLE
Import / Export / Sync from/to iCloud Keychain

### ISSUE THREAD

**Issue by patrickstigler** [strongbox/strongbox#1839]
# Task Description

I would like to migrate all my passwords from iCloud Keychain. In the best case I'd like to sync my Passwords from/to iCloud with my Keepass container. Since I also use different OS/Hardware I don't want to Lookup my updated password I updated using my iphone on the PC and update it in the Keepass container manually.

# Tasks

The following tasks will need to be carried out:
* [ ] Manage to import from iCloud Keychain
* [ ] Manage to export from iCloud Keychain
* [ ] Update / Sync in both ways - check last changed

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to:

# Useful Links

* [link1]()
* [link2]()
* [link3]()

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
Hi,

You've posted this issue to the wrong project. I assume you're referring to the [strongbox-password-safe/Strongbox project](https://github.com/strongbox-password-safe/Strongbox). I'm therefore closing this bug report.

Kind regards,

Martin
