### ISSUE TITLE
Improve password encoding support for LDAP

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1840]
# Bug Description

In LDAP the `userPassword` attribute contains the hash of the password encoded as `base64` and the end result in LDAP will be something like this `{ALG}base64.encode(md5/sha1/bcrypt(mypassword))`. The `PasswordEncoder` in Spring, however, expects that the part after `{ALG}` is actually the `hash` which causes login failures. If you have saved the `userPassword` using [PasswordEncoderFactories.createDelegatingPasswordEncoder](https://docs.spring.io/spring-security/site/docs/5.2.x/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html) it will work just fine, but in all other cases it will fail since the the compared hashed strings won't match.

# Solution

- [ ] Create a custom version of `org.springframework.security.ldap.userdetails.LdapUserDetailsMapper` which overrides the `mapPassword` with optional `base64.decode` logic 
- [ ] Use this custom version of `LdapUserDetailsMapper` for `LdapUserDetailsService` (see `strongbox-security/strongbox-authentication-providers/strongbox-ldap-authentication-provider/src/main/resources/org/carlspring/strongbox/authentication/external/ldap/strongbox-authentication-providers.xml`)
- [ ] ~~Also, it should be configurable with `strongbox.authentication.ldap.base64EncodedPassword=true|false`~~
- [ ] Write a unit test case for the `CustomUserDetailsMapper` to ensure it works properly with and without `base64` encoded hash as described:
    ```
  {ALG}md5/sha1/bcrypt(mypassword)
  {ALG}base64.encode(md5/sha1/bcrypt(mypassword))
  base64.encode({ALG}md5/sha1/bcrypt(mypassword))
    ```
- [ ] Write an integration test which uses Unboundid so we test against a real LDAP server. Some additional user records will need to be added in the testing `ldif` for this purpose.
org.carlspring.strongbox.config.SecurityConfig to org.carlspring.strongbox.config.WebSecurityConfig
- [ ] [SecurityConfig.java] -
   * Rename this class to `WebSecurityConfig` for better consistency with Spring naming convention.

[SecurityConfig.java]: https://github.com/strongbox/strongbox/blob/f6f280c8e01fe32b8681b5f4f9dd8c9aee9e1d2d/strongbox-web-core/src/main/java/org/carlspring/strongbox/config/SecurityConfig.java

# Useful Links

* [RFC4519#userPassword](https://tools.ietf.org/html/rfc4519#section-2.41)
* [RFC3112](https://tools.ietf.org/html/rfc3112)

# Task Relationships

This bug:
* Is follow-up of: #1670, #1614 
* Relates to: #1679 , #1846 , #1858

**Comment by madhukarbharti** [comment]
@carlspring and @steve-todorov May I work on this issue? Can you please assign this to me?

**Comment by madhukarbharti** [comment]
Thanks @carlspring :)

**Comment by carlspring** [comment]
Yes, please! Feel free to dig into this!

Your points of contact for this (in case you need help), will be @steve-todorov and @sbespalov . Feel free to ask questions either here, or on our [chat channel](https://chat.carlspring.org/).

Good luck! :)

**Comment by steve-todorov** [comment]
@madhukarbharti I've just found another corner case - `base64.encode({ALG}md5/sha1/bcrypt(mypassword))` (this seems to be another interpretation of the RFC). 
Since you have already implemented the first two, would you please slightly modify the logic in the PasswordEncoder to cover this case as well? (and add additional test cases for it)

**Comment by sbespalov** [comment]
@steve-todorov need some of your attention here
> Rename this class to WebSecurityConfig for better consistency with Spring naming convention.

the initial purpose was a bit different:
> org.carlspring.strongbox.config.SecurityConfig to org.carlspring.strongbox.config.WebSecurityConfig

could you please fix it in this task description?

**Comment by sbespalov** [comment]
@madhukarbharti @steve-todorov task description updated with `LdapUserDetailsMapper` approach

**Comment by carlspring** [comment]
Thanks, @sbespalov ! :)
