### ISSUE TITLE
Change default cassandra credentials for `db_EMBEDDED` profile

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1843]
# Task Description
We should change the default cassandra credentials in case of `-Dstrongbox.db.profile=db_EMBEDDED`.  This requires to find the proper way to set custom credentials within first start of the embedded cassandra instance. 

# Tasks

The following tasks will need to be carried out:
* [ ] propose and agree on a suitable way for changing the cassandra login and password
* [ ] make the corresponding changes in [strongbox/strongbox-db](https://github.com/strongbox/strongbox-db) project
* [ ] change default credentials in `janusgraph-cassandra.properties` 

# Task Relationships

This task:
* Is a sub-task of: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
