### ISSUE TITLE
Implement the rest of common `GremlinRepository` methods

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1844]
# Task Description
Methods which throws `UnsupportedOperationException` should be implemented with Gremlin query language.

# Tasks

The following tasks will need to be carried out:
* [ ] provide methods implementation
* [ ] make unit tests

# Task Relationships

This task:
* Is a sub-task of: #1649 

# Useful Links

* [Gremlin](https://docs.janusgraph.org/basics/gremlin/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by kosuruvarunkumar** [comment]
@carlspring, May I start looking into it? If yes, can you please help with some code pointers?
Thank you

**Comment by carlspring** [comment]
@kosuruvarunkumar ,

You will need to create a branch for this off the `issues/1649` branch and work on it there. If you have a look at the class, you'll see that it has a lot of `// TODO` comments for the unimplemented methods. You will need to:
* [ ] Assemble a task list of the methods that will need to be implemented
* [ ] Implement tests for them

Your point of contact for this will be @sbespalov .

**Comment by kosuruvarunkumar** [comment]
The task is open for pickup.
Thank you
