### ISSUE TITLE
Store dates in UTC

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1845]
# Task Description
All dates that we store in DB should have UTC time zone. The example is `UserEntity.lastUpdated`.

# Tasks

The following tasks will need to be carried out:
* [ ] set the JVM default timezone to UTC within application startup
* [ ] check that all dates stored in UTC
* [ ] convert dates to UTC if needed

# Task Relationships

This task:
* Is a sub-task of: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by AricMonary** [comment]
@carlspring Can I work on this issue? If so, could you clarify how to run the database locally to check the timezone?

**Comment by SolangeUG** [comment]
@carlspring I would like to help with this one... if it's still up for grabs 😃

**Comment by carlspring** [comment]
Go for it!
