### ISSUE TITLE
Backport the fixes related to replacing ApacheDS with UnboundID from pull #1783 to the master

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1846]
# Task Description

We should backport the fixes from #1783 that related to ApacheDS being replaced with UnboundID to the `master`. The version of the `com.unboundid:unboundid-ldapsdk:5.0.1` (see [here](https://github.com/strongbox/strongbox/pull/1783/files#diff-f96b8068a631d962b8fd30f5eaaedb24R164)) should be extracted to the [strongbox-parent](https://github.com/strongbox/strongbox-parent/) project (you will find [this article](https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html) useful, as it relates to adding/updating dependencies in the `strongbox-parent`).

# Tasks

The following tasks will need to be carried out:
* [ ] Define the `com.unboundid:unboundid-ldapsdk:5.0.1` dependency in the `<dependencyManagement/>` of the [strongbox-parent](https://github.com/strongbox/strongbox-parent/).
* [ ] Backport only the necessary sub-set of changes from #1783 (including the [LDIF fixes](https://github.com/strongbox/strongbox/pull/1783/files#diff-cd5cfc21b902bf2e72d0aee2b128ed40R19-R62)).
* [ ] Test that things still work properly.

# Task Relationships

This task:
* Relates to: #1783 

# Useful Links

* [Upgrading Dependencies And Plugins](https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by rycuda** [comment]
Hi, GHC participant here. I'll grab this one if that's okay?

**Comment by carlspring** [comment]
Hi, Jay,

Please, feel free to pick this up! Thanks for your help! :)
