### ISSUE TITLE
Upgrade our JUnit dependencies from 5.4.0 to 5.7.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1852]
# Task Description

We need to upgrade our JUnit dependencies from `5.4.0` to `5.7.0`.

Please, note that we are using JUnit Jupiter and that our dependency tree should not be showing any `junit` dependencies from the `4.x` series.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Add a dependency exclusion for `junit` under the `org.codehaus.mojo.appassembler:appassembler-model` of the `strongbox-parent`, (if the `org.codehaus.mojo.appassembler:appassembler-model` dependency isn't explicitly defined, add it with an exclusion). This is what a `mvn dependency:tree` currently shows in the `strongbox-distribution` and with the exclusion, this should go away:
```
[INFO] +- org.codehaus.mojo.appassembler:appassembler-model:jar:2.0.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[INFO] |  +- net.java.dev.stax-utils:stax-utils:jar:20060502:compile
[INFO] |  \- stax:stax:jar:1.1.1-dev:runtime
[INFO] |     \- junit:junit:jar:4.12:runtime
[INFO] |        \- org.hamcrest:hamcrest-core:jar:2.1:runtime
```
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by ptirador** [comment]
Hi @carlspring! Can I take this with my beloved JUnit?

**Comment by ariffebr** [comment]
I've updated junit version and exclude the junit.
please review for Hacktoberfest.
https://github.com/strongbox/strongbox-parent/pull/86
