### ISSUE TITLE
Upgrade our UnboundID dependencies from 4.0.9 to 5.1.1

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1858]
# Task Description

We need to upgrade UnboundID dependencies from `4.0.9` to `5.1.1`.

It would probably be a good idea to do this task together with #1846 (which is not much work).

# Tasks

The following tasks will need to be carried out:
* [x] Update the version in the [strongbox-parent] project.
* [x] Apply any required code changes, or dependency excludes.
* [x] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Task Relationships

This task:
* Relates to: #1846 

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by dms-yondy** [comment]
May I work on this and #1858 please?

**Comment by steve-todorov** [comment]
Hi @dms-yondy - are you from GHC?

**Comment by dms-yondy** [comment]
no, I am doing stuff for hacktoberfest.

**Comment by steve-todorov** [comment]
Thanks for offering to help!

This particular task is mainly for an event that we're hosting today with the Grace Hopper Celebration Open Source Day. Would you mind holding off for day (if no one picks it up during the event, it's yours), (or picking a non-dependency/plugin upgrade task)? For more details, you can join our chat channel where we can discuss what other tasks might be of interest to you. 

Thanks! :)

**Comment by dms-yondy** [comment]
No problem. I'll join the chat and have a look at some other tasks. I am sure I can find something!

Thanks for your time :)

**Comment by steve-todorov** [comment]
Thank you for your understanding! The event will end in about 5 hours so if you nobody picks it and you are still interested - just leave a comment and start working on it.

**Comment by mknutsen79** [comment]
I see no one is yet assigned to this ask is it okay to start working on this?

**Comment by carlspring** [comment]
@dms-yondy , @mknutsen79 ,

This task consists of two parts which should be done together - #1846 + #1858 , so whoever decides to pick this up, should optimally don both.

@mknutsen79 , I know that you need at least two more tasks, so I am therefore more inclinded for you to pick it up, as you've already done one.

@dms-yondy : I hope you're not offended! Would you mind picking one of our many other tasks? :)

**Comment by mknutsen79** [comment]
I appreciate that, thank you!

**Comment by carlspring** [comment]
Thanks for your help @mknutsen79 ! :)
