### ISSUE TITLE
Add a rule using the maven-enforcer plugin that requires Maven 3.6.3

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1864]
# Task Description

We should add a Maven Enforcer rule that requires Maven 3.6.3 in order to build the code.

# Tasks

The following tasks will need to be carried out:
* [ ] Add this rule in the [strongbox-parent].
* [ ] Apply this rule to the [strongbox] project.
* [ ] Apply this rule to the [strongbox-web-integration-tests].

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/

**Comment by madhukarbharti** [comment]
@carlspring
@sbespalov
@steve-todorov May I work on this

**Comment by carlspring** [comment]
Hi @madhukarbharti ,

If you're taking part in the Grace Hopper Open Source Day later on today, then -- yes, please! If not, or if you're taking part in #Hacktoberfest, then please wait until the 2nd of October, before picking this up.

Please, feel free to join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by ripudaman1320** [comment]
Hi @carlspring ,

Can i work on this issue as part of #Hacktoberfest. 

Thanks!
-Ripu

**Comment by carlspring** [comment]
Okay, go for it.

**Comment by steve-todorov** [comment]
Posting this here so people can find it easy. (related to recent changes in https://github.com/strongbox/strongbox-parent/pull/107)

* MVN Version < 3.6.3:
    ```
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-jdk-and-maven-versions) on project strongbox-parent: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
    [ERROR] 
    [ERROR]  You are using an unsupported Maven version! 
    [ERROR]  See https://strongbox.github.io/developer-guide/getting-started.html 
    [ERROR] 
    [ERROR] -> [Help 1]
    ```
