### ISSUE TITLE
Add a rule using the maven-enforcer plugin that requires JDK 8 (or 11)

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1865]
# Task Description

We should add a Maven Enforcer rule that requires:
* JDK 1.8 (if possible, `1.8.0_241` or higher) in order to build the code. This check should be in a Maven profile that's triggered, unless the JDK is 11.x.
* JDK 11 (if possible, `11.3`, or a higher `11.x`) in order to build the code. This check should be in a Maven profile that's triggerred only if the JDK is not JDK 1.8.

Please, note that the code in the `master` does not currently compile using JDK11. If the enforcer rule can be added for this, then this will be pre-work for JDK11 support. (You may want to have a look at the tasks related to #1111).

# Tasks

The following tasks will need to be carried out:
* [ ] Add this rule in the [strongbox-parent].
* [ ] Apply this rule to the [strongbox] project.
* [ ] Apply this rule to the [strongbox-web-integration-tests].

# Task Relationships

This task:
* Is relates to #1111 , #1864

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/

**Comment by suryaprakashraja** [comment]
@carlspring I can work on adding maven enforcer rule for Java 8) over the weekend. Never worked with JDK 11. But i will give it a try. Can you pls assign this to me?

**Comment by steve-todorov** [comment]
Hi @suryaprakashraja - this task is currently meant for the participants in the GraceHopperOSD event. Are you in our slack channel?

**Comment by suryaprakashraja** [comment]
Hello @steve-todorov , I am not in slack channel. but I would love to be a part of this project. Since this issue was tagged for hacktoberfest2020, I took the liberty of requesting assignation.

**Comment by carlspring** [comment]
Hi @suryaprakashraja ,

This task is open for both the Grace Hopper Open Source Day (GHC OSD) and #Hacktoberfest. GHC OSD is taking place on the 1st of October. If nobody takes this task on the day, then it's all yours.

You can also join our [chat channel](https://chat.carlspring.org/) for more details.

**Comment by AricMonary** [comment]
May I be assigned to this task?

**Comment by carlspring** [comment]
@AricMonary ,

Please, feel free to pick it up.

**Comment by carlspring** [comment]
> @carlspring I can work on adding maven enforcer rule for Java 8) over the weekend. Never worked with JDK 11. But i will give it a try. Can you pls assign this to me?

Hi @suryaprakashraja ,

Thanks for offering to help! My reply is a bit late, so I do apologize! Would you like to pick another task instead?

Much appreciated!

**Comment by suryaprakashraja** [comment]
> > @carlspring I can work on adding maven enforcer rule for Java 8) over the weekend. Never worked with JDK 11. But i will give it a try. Can you pls assign this to me?
> 
> Hi @suryaprakashraja ,
> 
> Thanks for offering to help! My reply is a bit late, so I do apologize! Would you like to pick another task instead?
> 
> Much appreciated!

@carlspring Sure. Thanks

**Comment by steve-todorov** [comment]
Posting this here as well so people can find it easy.

Expected failure output:

* JDK != 8 || 11	
    ```
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-jdk-and-maven-versions) on project strongbox-parent: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
    [ERROR] 
    [ERROR]  AdoptOpenJDK 13b13 is not a supported JDK version! 
    [ERROR]  See https://strongbox.github.io/developer-guide/getting-started.html 
    [ERROR] 
    [ERROR] -> [Help 1]
    ```
