### ISSUE TITLE
We need to upgrade the appassembler-maven-plugin from 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1873]
# Task Description

We need to upgrade the `org.codehaus.mojo:appassembler-maven-plugin` from `2.0.0` to `2.1.0`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.
* [ ] Check and confirm that the `tar.gz` and `zip` from the `strongbox/strongbox-distribution` still start up Strongbox properly.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by bmsbharathi** [comment]
@carlspring Can I work on this?

**Comment by carlspring** [comment]
Hi,

Yes, please! Go for it! :)

**Comment by herkura** [comment]
hi,
@carlspring  Can I work on this?

**Comment by carlspring** [comment]
Yes, please!

**Comment by herkura** [comment]
@carlspring  can you please guide me on how to do it since this is my first contribution to an open-source project.

**Comment by carlspring** [comment]
@whalenda ,

I can't guide you beyond:

* Check our article on [how to upgrade dependencies and plugins](https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html).

Could you please read the description and try to work it out? Thanks!

**Comment by herkura** [comment]
@carlspring  thank you. will check the article.

**Comment by ripudaman1320** [comment]
Hello @carlspring ,

I have the strongbox setup running in my local. Can i work on this issue as part #hacktoberfest?

Thanks!
-Ripu

**Comment by carlspring** [comment]
Well, what could I say -- whoever does it first, wins! :)

**Comment by liooh** [comment]
First kkkk, I did a pull request for this task
