### ISSUE TITLE
Upgrade the maven-assembly-plugin from 3.1.1 to 3.3.0

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1877]
# Task Description

We need to upgrade `maven-assembly-plugin` from `3.1.1` to `3.3.0`.

# Tasks

The following tasks will need to be carried out:
* [ ] Update the version in the [strongbox-parent] project.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.
* [ ] Check and confirm that the `tar.gz` and `zip` from the `strongbox/strongbox-distribution` still start up Strongbox properly.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html

**Comment by bmsbharathi** [comment]
@carlspring  can I work on this?

**Comment by steve-todorov** [comment]
Hi @bmsbharathi - are you from GHC?

**Comment by bmsbharathi** [comment]
@steve-todorov I am not from GHC.

**Comment by hirva10** [comment]
@carlspring I am from GHC and want to work on this issue

**Comment by steve-todorov** [comment]
Hi @bmsbharathi ,

Thanks for offering to help!

This particular task is mainly for an event that we're hosting today with the Grace Hopper Celebration Open Source Day. Would you mind holding off for day (if no one picks it up during the event, it's yours), (or picking a non-dependency/plugin upgrade task)? For more details, you can join our chat channel where we can discuss what other tasks might be of interest to you. Thanks! :)

---

@hirva10 the task is yours! :)

**Comment by carlspring** [comment]
Thank you for your contribution, @hirva10 ! :)
