### ISSUE TITLE
Copy our pull request template to the rest of the Strongbox projects

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1901]
# Task Description

The Strongbox project already has a [pull request template](https://github.com/strongbox/strongbox/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and we need to copy this across the rest of the sub-projects.
The template should have the following line changed (in all the sub-projects) from:
```
This pull request closes #
```
To:
```
This pull request closes strongbox/strongbox#
```

# Tasks

The following tasks will need to be carried out:
* [x] Copy the pull request template to [strongbox-parent](https://github.com/strongbox/strongbox-parent).
* [x] Copy the pull request template to [strongbox-db](https://github.com/strongbox/strongbox-db).
* [x] Copy the pull request template to [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests).
* [x] Copy the pull request template to [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata).
* [ ] Copy the pull request template to [strongbox-web-ui](https://github.com/strongbox/strongbox-web-ui).
* [x] Copy the pull request template to [ci-build-images](https://github.com/strongbox/ci-build-images).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by pawelpaszki** [comment]
@carlspring can you assign me to this please?

**Comment by carlspring** [comment]
@pawelpaszki ,

Thanks for offering to help! Please, feel free to pick this up! :)
