### ISSUE TITLE
Set up our project to be able to work with Github Codespaces

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1906]
# Task Description

We would like to set up our project so that it can work with Github Codespaces.

This project can currently only work with JDK8 (in all branches) and it will fail to compile with newer versions. We need to figure out how to set things up so that the Docker image which is being used has JDK8, instead of JDK11.

For the `issues/1649` branch, we need to add configuration for both JDK 8 and 11 (JDK11 is still not supported there, but is a work-in-progress and we should use the current defaults, which are set to JDK11).

# Pre-requisites

* [ ] You **_must_** have been granted access to Github Codespaces (which is in beta and, if you don't have access, you'll probably be placed on a long waiting list).
* [ ] You **_must_** have some Docker experience.

# Tasks

The following tasks will need to be carried out:
* [ ] Apply the necessary configuration changes for JDK8 to be used as a default for all branches.
* [ ] Clarify (and, if possible) implement whatever needs to be done in order to have (switchable) support for both JDK8 (default) and JDK11 in the `issues/1649` branch. 

# Task Relationships

This task:
* Relates to: #1785 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by steve-todorov** [comment]
This might be helpful.

https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/configuring-codespaces-for-your-project#creating-a-custom-codespace-configuration
