### ISSUE TITLE
Refactoring of the strongbox-npm-metadata project

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1915]
# Task Description

We need to re-organize our implementation of the NPM layout provider.

This is the parent task for the work described below.

# Tasks

The following tasks will need to be carried out in exactly this order, as they will depend on each other:
* [ ] Clean up of the NPM layout provider ( # ).
* [ ] Absorb the `strongbox-npm-metadata` project into `strongbox` ( # ).
* [ ] Archive the `strongbox-npm-metadata` project. ( @carlspring / @steve-todorov )
* [ ] Disable our Jenkins job for the old archived project. ( @steve-todorov )

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by KenCox94** [comment]
Could I contribute to this project?

**Comment by Olya-Grygorian** [comment]
Hi. Can I work on this?
