### ISSUE TITLE
Clean up minor build issues with the strongbox-npm-metadata project

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1916]
# Task Description

We need to a minor clean up of our [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata) project.

# Tasks

The following tasks will need to be carried out:
* [x] Drop the need for the [strongbox-npm-metadata-parent](https://github.com/strongbox/strongbox-npm-metadata/blob/master/strongbox-npm-metadata-parent/pom.xml)
  * [x] This module should be removed completely.
  * [x] All the dependencies from its `<dependencyManagement/>` section should be extracted to the [strongbox-parent](https://github.com/strongbox/strongbox-parent), (if this is not yet so).
  * [x] All the plugins from its `<pluginManagement/>` section should be extracted to the [strongbox-parent](https://github.com/strongbox/strongbox-npm-metadata), (if this is not yet so).
  * [x] All the modules in the [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata) should extend the [strongbox-parent](https://github.com/strongbox/strongbox-parent) instead of the `strongbox-npm-metadata-parent`.
  * [x] The `junit:junit:4.12` dependency needs to be dropped and the code should only use JUnit Jupiter (JUnit 5.x), extended from the [strongbox-parent](https://github.com/strongbox/strongbox-parent).
  * [x] None of the dependencies in the project should have a defined `<version/>`.
  * [x] None of the plugins in the project should have a defined `<version>`.
* [x] Remove all `.iml` files and add them to the `.gitignore`.

# Task Relationships

This task:
* Is a sub-task of: #1915
* Is required for: #1917 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by GeorgHenkel** [comment]
Hi @carlspring, I would like to work on this.

**Comment by carlspring** [comment]
Hi @GeorgHenkel ,

Thanks for offering to help! Please, feel free to dig in! :)
