### ISSUE TITLE
Absorb the strongbox-npm-metadata project into strongbox

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1917]
# Task Description

We need to re-organize our implementation of the NPM layout provider.

The whole project builds in 31 secs, when it's built for the first time and the dependencies haven't been download yet; when they're already cached, it only takes 5 secs. There is no good benefit of having the code outside the main codebase for this, as it creates a highly de-coupled modular build and adds a maintenance and build pipeline complexity.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new module under `strongbox-storage/strongbox-storage-layout-providers` called `strongbox-storage-npm-layout`.
* [ ] Copy the code from the `strongbox-npm-metadata` project into the `strongbox-storage-npm-layout/strongbox-npm-metadata`. If you can preserve the history using `git filter-branch`, that would be preferred.
* [ ] Move the `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider` into `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout/strongbox-storage-npm-layout-provider`.
* [ ] Make the necessary adjustments to the aggregators.
  * [ ] Fix the `strongbox-storage/strongbox-storage-layout-providers/pom.xml`.
  * [ ] Add a `strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout/pom.xml`

# Task Relationships

This task:
* Is a sub-task of: #1915
* Depends on: #1916

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by AricMonary** [comment]
@carlspring Can I work on this once #1916 is closed?

**Comment by carlspring** [comment]
I think it would be better, if the same person does it, but let's see, if he's interested first.

**Comment by AricMonary** [comment]
Okay. I accidently spent some time yesterday also working on the issue. I am familiar with the structure of the strongbox-npm-metadata project.

**Comment by Olya-Grygorian** [comment]
Hi. Can I work on this?
