### ISSUE TITLE
Setup a Github Action that deploys our hello-strongbox-* to the Github Package Registry

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1927]
# Task Description

We need to create a Github Action for the [strongbox-examples](https://github.com/strongbox/strongbox-examples) that deploys the artifacts for each of layout providers (that we have an image for) to the Github Package Registry for the [strongbox-examples](https://github.com/strongbox/strongbox-examples).

# Tasks

The following tasks will need to be carried out:
* [ ] Create a Github Action that deploys the [hello-strongbox-ant-ivy](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-ant-ivy).
* [ ] Create a Github Action that deploys the [hello-strongbox-gradle](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-gradle).
* [ ] Create a Github Action that deploys the [hello-strongbox-maven](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-maven).
* [ ] Create a Github Action that deploys the [hello-strongbox-npm](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-npm).
* [ ] Create a Github Action that deploys the [hello-strongbox-nuget-chocolatey
](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-nuget-chocolatey).
* [ ] Create a Github Action that deploys the [hello-strongbox-nuget-mono](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-nuget-mono).
* [ ] Create a Github Action that deploys the [hello-strongbox-pypi](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-pypi).
* [ ] Create a Github Action that deploys the [hello-strongbox-sbt](https://github.com/strongbox/strongbox-examples/tree/master/hello-strongbox-sbt).

# Task Relationships

This task:
* Is required for:

# Useful Links

* [Github Actions](https://github.com/features/actions)
* [Github Packages](https://github.com/features/packages)
* [Github Package Registry](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by BjoernAkAManf** [comment]
Hi,

this sounds easy. Should the actions somehow also use an installed strongbox installation or merely build + deploy to github actions. While the former sound complicated, the latter seems "pointless"? Am i missing something here?

Would gladly help otherwise :)

**Comment by BjoernAkAManf** [comment]
Ah thanks! Guess i'll go and write some github actions code then 😄 .

**Comment by BjoernAkAManf** [comment]
Took more attempts than i wanted it to, however now it builds jars into the package repository.
Just to clarify, is that what you meant by:
[ ]  Create a Github Action that deploys the hello-strongbox-maven into the Github Package Registry.

See:
https://github.com/BjoernAkAManf/strongbox-examples-actions/blob/main/.github/workflows/maven.yml
https://github.com/BjoernAkAManf/strongbox-examples-actions/packages/466292

**Comment by carlspring** [comment]
Awesome, thanks! :)

So, you now have the Maven one covered! Would you like to do the rest of the ones that use Maven repositories as well (first)?

**Comment by BjoernAkAManf** [comment]
Sure i can do that.

**Comment by j4ckofalltrades** [comment]
@BjoernAkAManf @carlspring  I'm currently looking into `hello-strongbox-npm`. Also found this cool [project](https://github.com/nektos/act) that lets you run GitHub Actions locally.

**Comment by carlspring** [comment]
Thanks, @j4ckofalltrades ! This project looks quite useful and I'm sure we'll be using it to try out more of our Github Actions with it in the future!

cc: @steve-todorov

**Comment by carlspring** [comment]
@BjoernAkAManf : How are things going with the Maven-based actions?

**Comment by j4ckofalltrades** [comment]
Just an fyi regarding authentication in GitHub Action workflows, this pertains to the `GITHUB_TOKEN` secret that is used when publishing artifacts to the GitHub Package Registry. This is automatically provided by GitHub for every repository and can be referenced with `${{ secrets.GITHUB_TOKEN }}`.

See https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret for more info.

**Comment by carlspring** [comment]
Thanks for the clarification, @j4ckofalltrades ! :)

There's something else that we'll need to address -- the non-Maven-based tool have no concept of snapshots, which means that every time we merge a pull request, the NPM, NuGet and so on Github Actions will fail. Is there a reasonable way in which we can handle this for these? Can we remove the artifacts before deploying them? (They're all using fixed versions such as `1.0.0`, right?).

cc: @steve-todorov

@j4ckofalltrades ,

Please, feel free to pick up the Maven and SBT ones as well. We haven't heard back from @BjoernAkAManf, nor seen a pull request for them yet, so I assume it would be safe to proceed with them as well. (Please, feel free to give us a shout, if this is not so, @BjoernAkAManf).

**Comment by j4ckofalltrades** [comment]
> Can we remove the artifacts before deploying them? (They're all using fixed versions such as 1.0.0, right?).

Unfortunately this isn't possible for public repos / packages. From[ GitHub docs](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion):

> About public package deletion
To avoid breaking projects that may depend on your packages, you cannot delete an entire public package or specific versions of a public package.
>
> Under special circumstances, such as for legal reasons or to conform with GDPR standards, you can ask GitHub Support to delete a public package for you, using our contact form.

We could maybe skip the publish step as an alternative e.g. `nuget push` has a `-SkipDuplicate` option which does this.

**Comment by carlspring** [comment]
> We could maybe skip the publish step as an alternative e.g. `nuget push` has a `-SkipDuplicate` option which does this.

Yeah, we should probably do this.

**Comment by carlspring** [comment]
@j4ckofalltrades : Could you please make the artifact names more consistent? If possible, they should all be using the following format: `hello-strongbox-*`?

**Comment by BjoernAkAManf** [comment]
Sorry to reply so late, have been unexpectedly busy the last couple of days.

I'll add the maven artifact to the github repository now, but otherwise i'll probably wont be able to help the next days.

**Comment by carlspring** [comment]
Thanks @BjoernAkAManf ! I think that it will be better, if @j4ckofalltrades does the remainder of the sub-tasks, as he's already done with most of the work anyway. 

@j4ckofalltrades , @steve-todorov : Could you please review strongbox/strongbox-examples#28? Thanks! :)

**Comment by carlspring** [comment]
@j4ckofalltrades , @BjoernAkAManf , @steve-todorov ,

There is another problem with the deployment of all these artifacts that I've realized. Basically, when an example sub-module has been changed, we will need to bump the versions for all of the other ones as well, because if they have already been deployed to the Github Package Registry, then the deployment for all of them will fail.

Do you guys have any suggestions on how we could easily sort this our for all of them? Should we use the `maven-versions-plugin` to bump the version on each merged to `master` (and add a step for this as well)?

**Comment by steve-todorov** [comment]
`maven-versions-plugin` will only work for maven artifacts (sbt, mvn and maybe groovy?). `npm` uses the `package.json` and it would need additional work to update the version. We could try doing it :)

However, we'll then need to address this as well: 
https://github.com/strongbox/strongbox-examples/pull/28#discussion_r513837469

**Comment by j4ckofalltrades** [comment]
One other option is to append the latest commit hash (maybe trimmed to first ~6-10 characters) to the version number. like in https://maven.apache.org/maven-ci-friendly.html and it should be fairly simple to do in other non-Maven based packages as well.

GitHub Actions provides it via the [GITHUB_SHA](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables) environment variable.

**Comment by carlspring** [comment]
Another option would be to switch the version to `YYYYMMDD-hhmm` or something along these lines.

**Comment by carlspring** [comment]
The hash would probably be easier and cleaner...

**Comment by j4ckofalltrades** [comment]
@carlspring 

Okay let's go with the append timestamp `yyyyMMdd-hhmm` to the version approach. I've opened pull requests for updating the existing gradle workflow strongbox/strongbox-examples#31 plus the other remaining mvn-based ones - sbt strongbox/strongbox-examples#30 and ant-ivy strongbox/strongbox-examples#32.

If all good then it should also be applied to the maven workflow.
