### ISSUE TITLE
Check if all of our artifacts contain a LICENSE file and add one where necessary

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1928]
# Task Description

We need to check, if all of our artifacts contain a `META-INF/LICENSE` file and add it, if wherever this may be missing.

You can find which modules don't have such a file quite easily:
1. Build the artifacts:
```
mvn clean install -DskipTests
```
2. Check which artifacts don't have the `META-INF/LICENSE` (ignore `tests` artifacts, but it should be in the default jar, as well as in the `sources` one):
```bash
#!/bin/bash

cd $1

jarFiles=`find . -name \*.jar`

for jarFile in $jarFiles
do
    echo "Scanning ${jarFile}..."
    matches=`jar -tvf ${jarFile} | grep $2`
    
    if [ -n "$matches" ]; then
	echo " --> Matches found <-- "
	jar -tvf ${jarFile} | grep $2
    fi
done

hpiFiles=`find . -name \*.hpi`

for hpiFile in $hpiFiles
do
    echo "Scanning ${hpiFile}..."
    matches=`jar -tvf ${hpiFile} | grep $2`

    if [ -n "$matches" ]; then
        echo " --> Matches found <-- "
        jar -tvf ${hpiFile} | grep $2
    fi
done
```

Of course, you can do the check by hand, if you like.

# Tasks

The following tasks will need to be carried out:
* [ ] Scan all the artifacts of the `strongbox` projects and check if they have a `src/main/resources/META-INF/LICENSE` file (this is only for modules that have sources).
* [ ] Copy `strongbox/strongbox/blob/master/strongbox-commons/src/main/resources/META-INF/LICENSE` to `src/main/resources/META-INF/LICENSE` under each of module where this is missing.
* [ ] Do the above steps for the [strongbox-db](https://github.com/strongbox/strongbox-db) project.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by BhuwanUpadhyay** [comment]
may I work on this issue?

**Comment by carlspring** [comment]
Hi @BhuwanUpadhyay ,

Sure! Feel free to dig in! :)
