### ISSUE TITLE
Improve our tests in the strongbox-web-integration-tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1931]
# Task Description

We need to improve the tests that we have in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/).

This is the master task for all of the work that will need to be done.

# Tasks

The following tasks will need to be carried out:
* [ ] Improve the tests for our Maven support in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/). ( # )
* [ ] Improve the tests for our NPM support in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/). ( # )
* [ ] Improve the tests for our NuGet support in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/). ( # )
* [ ] Improve the tests for our Raw support in the [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/). ( # )

# Task Relationships

This task:
* Is a follow-up of: #1927

# Useful Links

* [strongbox-web-integration-tests](https://github.com/strongbox/strongbox-web-integration-tests/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by BhuwanUpadhyay** [comment]
@carlspring may I work on this issue?

**Comment by carlspring** [comment]
Yes, but not yet. I need to create the sub-tasks with proper descriptions for this.

**Comment by carlspring** [comment]
@BhuwanUpadhyay ,

You can have a look at #1934 , which is the first sub-task of this master issue that can be worked on. The other sub-tasks are either waiting on other tasks to be done first, or have still not been posted.

**Comment by BhuwanUpadhyay** [comment]
@carlspring ok I will complete all subtask with this issue.
