### ISSUE TITLE
Fix strongbox-npm-metadata-jackson Windows build error

### ISSUE THREAD

**Issue by AricMonary** [strongbox/strongbox#1932]
# Task Description
The [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata) project was configured to build only using Linux while the [strongbox](https://github.com/strongbox/strongbox) builds on both Linux and Windows. As a result, the Windows build fails upon integrating [strongbox-npm-metadata](https://github.com/strongbox/strongbox-npm-metadata) into [strongbox](https://github.com/strongbox/strongbox) from #1917. The build error on Windows is not caused by a recent upgrade of the jsonschema2pojo plugin from 0.5.1 to 1.0.2 in https://github.com/strongbox/strongbox-parent/pull/111.

# Pre-requisites
* [ ]  You **_must_** be able to build on Windows.

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate the cause of the build error on windows.
* [ ] Implement fix for build error.
* [ ] Test the build on both Linux and Windows

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: #1915 
* Is a follow-up of: 
* Relates to: #1917 

# Useful Links

* [Mention of Windows build error](https://github.com/strongbox/strongbox/issues/1771)
* [Build Error Logs (using original plugin version](https://pastebin.com/K3H1BPxi)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
