### ISSUE TITLE
Fix the strongbox-distribution with embedded cassandra under JDK-11

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1933]
# Task Description
It should be fixed same was as for `spring-boot:run`, so there should be different `wrapper.conf` files depending on JDK environment.

Should be done in `issues/1649`.

# Tasks

The following tasks will need to be carried out:
* [ ] research how to use different `wrapper.conf` files depending on JDK
* [ ] create two `wrapper.conf` files, one for JDK 11 should contain additional JVM parameters for cassandra
* [ ] check that the same distribution package works on JDK 11 and JDK 1.8

# Task Relationships

This task:
* Is a follow-up of:  #1775 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
after some research it's seems not possible to have different `wrapper.cont` files within same distribution due to limitations of `appassembler-maven-plugin`. Will consider to proceed with #1459 instead.
