### ISSUE TITLE
Test our NPM support with the Github Package Registry and improve our strongbox-web-integration-tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1934]
# Task Description

We have already implemented support for the NPM layout via our [NPM layout provider](https://strongbox.github.io/developer-guide/layout-providers/npm-layout-provider.html). At the moment, we have one NPM proxy defined as [`storage-npm:npmjs`](https://github.com/strongbox/strongbox/blob/master/strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.yaml#L299).

We need to check if our NPM support is compatible with Github's implementation of NPM registries. If there are bugs, we should collect, investigate and fix them.

Please, note: This task can only be picked up once #1927 has been implemented.

# Tasks

The following tasks will need to be carried out:
* [ ] Add a new test in the [strongbox-web-integration-tests] project that:
  * [ ] Creates a new proxy repository called `storage-npm:github-test-npm-registry` which points to the new NPM registry (created in #1927 and strongbox/strongbox-examples#24) during the tests.
  * [ ] Add the `storage-npm:github-test-npm-registry` to a group repository for NPM called `storage-npm:npm-group`.
  * [ ] Test resolving artifacts via the Strongbox proxy above (`storage-npm:github-test-npm-registry`).
  * [ ] Test resolving artifacts via the Strongbox group above (`storage-npm:npm-group`).
  * [ ] Test resolving artifacts via group where the artifacts only exist in the Github NPM registry.
  * [ ] Test resolving artifacts via group where the artifacts only exist in the npmjs.org registry.

# Task Relationships

This task:
* Depends on: #1927 , strongbox/strongbox-examples#24

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox/

**Comment by BhuwanUpadhyay** [comment]
@carlspring May I start with this task?

**Comment by carlspring** [comment]
Hi!

Yes, please!
