### ISSUE TITLE
Test our NuGet support with the Github Package Registry and improve our strongbox-web-integration-tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1938]
# Task Description

We have already implemented support for the NuGet layout via our [NuGet layout provider](https://strongbox.github.io/developer-guide/layout-providers/nuget-layout-provider.html). At the moment, we have one NuGet proxy defined as [`storage-nuget:nuget.org`](https://github.com/strongbox/strongbox/blob/master/strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.yaml#L150).

We need to check if our NuGet support is compatible with Github's implementation of NuGet registries. If there are bugs, we should collect, investigate and fix them.

Please, note: This task can only be picked up once #1927 has been implemented.

# Tasks

The following tasks will need to be carried out:
* [ ] Add a new test in the [strongbox-web-integration-tests] project that:
  * [ ] Creates a new proxy repository called `storage-nuget:github-test-nugt-registry` which points to the new NuGet registry (created in #1927 and strongbox/strongbox-examples#25) during the tests.
  * [ ] Add the `storage-nuget:github-test-nuget-registry` to a group repository for NuGet called `storage-nuget:nuget-group`.
  * [ ] Test resolving artifacts via the Strongbox proxy above (`storage-npm:github-test-npm-registry`). (This should be our corresponding artifact from the [strongbox-examples](https://github.com/strongbox/strongbox-examples/) project).
  * [ ] Test resolving artifacts via the Strongbox group above (`storage-nuget:nuget-group`).
  * [ ] Test resolving artifacts via group where the artifacts only exist in the Github NuGet registry (this should be our corresponding artifact from the [strongbox-examples](https://github.com/strongbox/strongbox-examples/) project).
  * [ ] Test resolving artifacts via group where the artifacts only exist in the nuget.org registry. (Please, pick a very small artifact for this. It should not be larger that 200-300 KB).

# Task Relationships

This task:
* Depends on: #1927 , strongbox/strongbox-examples#25

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox/
