### ISSUE TITLE
Test our Maven support with the Github Package Registry and improve our strongbox-web-integration-tests

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1945]
# Task Description

We have already implemented support for the Maven layout via our [Maven layout provider](https://strongbox.github.io/developer-guide/layout-providers/maven-layout-provider.html). At the moment, we have a bunch of pre-defined Maven proxies in the [`storage-common-proxies`](https://github.com/strongbox/strongbox/blob/master/strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.yaml#L70) storage.

We need to check if our Maven support is compatible with Github's implementation of Maven registries. If there are bugs, we should collect, investigate and fix them.

Please, note: This task can only be picked up once sub-task for Maven in #1927 has been implemented.

# Tasks

The following tasks will need to be carried out:
* [ ] Add a new test in the [strongbox-web-integration-tests] project that:
  * [ ] Creates a new proxy repository called `storage-common-proxies:github-test-maven-registry` which points to the new Maven registry (created in #1927) during the tests.
  * [ ] Add the `storage-common-proxies:github-test-maven-registry` to the group repository for Maven called [`storage-common-proxies:group-common-proxies`](https://github.com/strongbox/strongbox/blob/master/strongbox-resources/strongbox-storage-api-resources/src/main/resources/etc/conf/strongbox.yaml#L133).
  * [ ] Test resolving artifacts via the Strongbox proxy above (`storage-common-proxies:github-test-maven-registry`). (This should be our corresponding artifact from the [strongbox-examples](https://github.com/strongbox/strongbox-examples/) project).
  * [ ] Test resolving artifacts via group repository (this should be our corresponding artifact from the [strongbox-examples](https://github.com/strongbox/strongbox-examples/) project).
* [ ] Add a new test that:
  * [ ] Creates a proxy repository to a repository on Bintray (in the storage-common-proxies` storage).
  * [ ] Add this proxy repository to the `storage-common-proxies:group-common-proxies`.
  * [ ] Test resolving an artifact from Bintray using the proxy repository.
  * [ ] Test resolving an artifact from Bintray using the group repository.

# Task Relationships

This task:
* Is a sub-task of: #1931
* Depends on: #1927

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox/
