### ISSUE TITLE
Re-work the licenses annotations to use SPDX, instead of hard-coded values

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1962]
# Task Description

Currently, we've hard-coded some more common licenses in the `LicenseType` enum class. We should replace this with the [Java SPDX library](https://github.com/spdx/Spdx-Java-Library) and drop the need for this class, or make it work with SPDX.

# Tasks

The following tasks will need to be carried out:
* [ ] Introduce the SPDX library to Strongbox.
* [ ] Investigate what will need to be done.
* [ ] Refactor the code.
* [ ] Add some tests.

# Task Relationships

This task:
* Is a sub-task of: #1723

# Useful Links

* [Java SPDX library](https://github.com/spdx/Spdx-Java-Library)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov
