### ISSUE TITLE
Refactor the setup-jdk script

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1967]
# Task Description

The [`setup-jdk.sh`](https://github.com/strongbox/ci-build-images/blob/5aab53304122f0b917edf22d289a18eec995df48/common-scripts/setup-jdk.sh) script file needs to be refactored so that it's more portable and usable in `Vagrant`, `Ansible` and still work in `Docker`.

# Tasks

The following tasks will need to be carried out:

* [x] Convert the env variables to options, but fallback to using env variables if no options were set (useful for Docker) 
* [x] Switch to official AdoptJDK packages.
* [x] Move JMeter into a separate script.
