### ISSUE TITLE
Implement JanusGraph id block queues

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1968]
# Task Description

# Tasks

The following tasks will need to be carried out:
* [x] Make it possible to have custom `GraphDatabaseConfiguration`
* [x] Implement a `TransactionVertexIDAssigner` attached to corresponding ID queue
* [x] Make `VertexIDAssigner` stored as a resource of `TransactionSynchronizationManager`
* [x] Provide corresponding `TransactionManager` for cron job tasks execution
* [x] Provide tests with at least two `TransactionManager` instances which ensures that different transactions start IDs from its queue
* [x] fix cassandra shutdown

# Task Relationships

This task:
* Is a sub-task of: #1649 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by sbespalov** [comment]
fixed with #1971
