### ISSUE TITLE
Fix gradle build issues

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1970]
# Bug Description

Some of the operations in `setup-mvn.sh` are causing issues in other images (i.e. gradle), because it relies on `$(id -u):$(id -g)`. This causes the `$HOME` path to be `chowned` by `root` user instead of the correct user.

# Tasklist

- [ ] Move the `settings.xml` related logic into a separate script which can accept `--user` arguments to allow for manually overriding the `$USER_ID` and `$GROUP_ID`.
- [ ] Add `--owner` which should be the username for which we're setting up the `settings.xml`
- [ ] All of the script arguments should fallback to `id -u` and `id -g`. 

# Task Relationships

This bug:

* Is caused by: #1967
