### ISSUE TITLE
Make the log files rolling

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1976]
# Task Description

We're using Logback and SLF4J. We need to add rolling logs.

The logging configuration is in `strongbox-resources/strongbox-common-resources/src/main/resources/logback-spring.xml`.

# Tasks

The following tasks will need to be carried out:
* [ ] Rolling logs should be generated on a daily basis.
* [ ] Rolled log files should be compressed using `gz`.
* [ ] Log files should not be larger than (let's say) 1 GB.

# Task Relationships

This task:
* Is a follow-up of: #1649 ( #1676 )

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

**Comment by carlspring** [comment]
Well, they actually _**are**_ rolling. My bad!

**Comment by steve-todorov** [comment]
This task was finished very fast! 😀

**Comment by carlspring** [comment]
Yeah... :rofl:
