### ISSUE TITLE
Upgrade to Angular 11

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1987]
# Task Description

We need to upgrade our `@angular/*` dependencies from `10.*` to version `11.*`.

# Notable changes

* [Angular >= 11 drops support for IE 9, 10 and Mobile](https://blog.angular.io/version-10-of-angular-now-available-78960babd41#c357)
* Angular requires TypeScript 4.0+.
* Allows for opt-in to webpack 5 by using Yarn and adding "resolutions": {"webpack": "^5.0.0"} to your package.json.
  * This also allows to use webpack module federation which will be handy.
* See other changes [here](https://update.angular.io/?l=3&v=10.0-11.0)

# Tasks

The following tasks will need to be carried out:

* [ ] Update the version in the [strongbox-web-ui] project.
* [ ] Apply any required code changes, or dependency excludes.
* [ ] Test and confirm that there are no issues with the core projects ([strongbox], [strongbox-web-integration-tests], etc) after upgrading.

# Help

* Check our article on [how to upgrade dependencies and plugins].
* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox]: https://github.com/strongbox/strongbox/
[strongbox-parent]: https://github.com/strongbox/strongbox-parent/
[strongbox-web-ui]: https://github.com/strongbox/strongbox-web-ui/
[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[how to upgrade dependencies and plugins]: https://strongbox.github.io/developer-guide/upgrading-dependencies-and-plugins.html
