### ISSUE TITLE
Implement a PypiArtifactController

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#811]
# Task Description

We need to:
* [ ] Implement a controller that handles incoming requests for PyPi packages
* [ ] Investigate what PyPi commands, (if any), we need to support

The code should be located in a class called `PypiArtifactController` under `strongbox/strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/pypi`.

# Tasks

* [ ] Implement downloading of artifacts
  * [ ] Implement support for the `data-requires-python` attribute as described in [PEP 503](https://www.python.org/dev/peps/pep-0503/)
* [ ] Implement uploading of artifacts
* [ ] Fix the browsing and downloading of PyPi artifacts

# Task Relationships

This is a sub-task of #807. It should be relatively straight-forward to implement this and you should get acquainted with the master task, before proceeding.

This task depends on #1190.

# See Also

* pypa/pipenv#2075 : Allow users to override default PyPI index URL with PyPI mirror URLs (without modifying Pipfile)
* [Mulit-part handling](https://stackoverflow.com/questions/55894007/how-to-read-multipart-using-sring-boot/)
* [Browseable PyPi directory structure](https://mirrors.aliyun.com/pypi/simple/)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by ror6ax** [comment]
Warehouse( pypi.org ) api methods are basically new and legacy ones:

https://warehouse.pypa.io/api-reference/json/
https://warehouse.pypa.io/api-reference/legacy/

Legacy in this context is relatively fresh (see http://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html), so there is a possibility we still want it done, if you guys feel like it.

JSON methods look like a good match for this ticket's work.

**Comment by carlspring** [comment]
# Uploading
```
carlspring@carlspring:/java/opensource/carlspring/strongbox/strongbox-web-core> sudo tcpdump -i any -c10 -nn -A port 48080
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
02:17:32.247089 IP6 ::1.57278 > ::1.48080: Flags [S], seq 1365359884, win 43690, options [mss 65476,sackOK,TS val 1253082674 ecr 0,nop,wscale 7], length 0
`..u.(.@....................................Qa...........0.........
J..2........
02:17:32.247104 IP6 ::1.48080 > ::1.57278: Flags [S.], seq 136223775, ack 1365359885, win 43690, options [mss 65476,sackOK,TS val 1253082674 ecr 1253082674,nop,wscale 7], length 0
`.A..(.@........................................Qa.......0.........
J..2J..2....
02:17:32.247114 IP6 ::1.57278 > ::1.48080: Flags [.], ack 1, win 342, options [nop,nop,TS val 1253082674 ecr 1253082674], length 0
`..u. .@....................................Qa..... ...V.(.....
J..2J..2
02:17:32.247751 IP6 ::1.57278 > ::1.48080: Flags [P.], seq 1:3963, ack 1, win 342, options [nop,nop,TS val 1253082674 ecr 1253082674], length 3962
`..u...@....................................Qa..... ...V.......
J..2J..2POST /storages/storage-pypi/pypi-releases/ HTTP/1.1
Accept-Encoding: identity
Content-Length: 3641
Connection: close
User-Agent: Python-urllib/2.7
Host: localhost:48080
Content-Type: multipart/form-data; boundary=--------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Authorization: Basic ZGVwbG95ZXI6cGFzc3dvcmQ=


----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="comment"


----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="metadata_version"

1.0
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="filetype"

sdist
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="protcol_version"

1
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="author"

Martin Todorov
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="home_page"

https://github.com/strongbox/strongbox-examples
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="download_url"

UNKNOWN
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="content";filename="hello-strongbox-pip-1.0.tar.gz"

....,..\..dist/hello-strongbox-pip-1.0.tar..Zmo.6..g.
.......Kv`....[..q...."P....J.@Qn._....8.c;M.t..AD..o:>.;Jc........Z..Y..v.2......<}...U..]........x..z .;..kP.....b..F.d.g2JG....7LROd~.I0^c..."k...#..S....ng..piw..B.?9>.......$....".C.....).e......u./..B....K..K.|..w..........?..OC..S?../yK.......j.6.....>.......?.|.......o.........]..>....7.....T..6%5K..!F....._#[..[E.N.0.<.}@.]kd.M...Jd~.'<.v!#.W-.H......yn.E.....b..1.o.^$.....S....Y.dE..H.&.=.Nk..gsU..t/.!.D....tcJey.4G.....@$...e..7,.b..W.......TQJ.E(.....OX....h...D7K..........cN......2....x-R.Se.O3P.tzr:.8....~...
.,%........q...k....(.cJ...]@..w....8^.....f.[I..............>......s..}......on.v.....n......)D...Q.P.........G.B.!.................W-a.....;......... .1....G..q....o{.........@H`!....8...b......".H.,......".j.B..\...o]...fS oJ.o.h.F...M.Y.pd...G...5.j.|......4.........@&..t...E+w.8ll.....,..%,.....0.9mn.R.......?Tp.........[..Q...[VZ3\..l.+..-.....Z.....Q.......Kr.....=M.?.{.......M....&.m.....:.=m.+>..]]..g.}.I^..../&.q4..L.1.........!.qJp.Z...$i...~.r...]'..<..^s...........A.....c...{l...........M......c.r.E...1Q..L@.F...:...I.'.....7.....2.k.#5
.c.U...t..
.i9.|...8P.*+..C]......".Q
.@.....\..0...vf..V3..l./...!.........q/.......N...._......R$.....s.%....T.....#...J...T.`..}......~sMV.j.......nq./..~.....B....I..Wya....A
./.....3.$GxH.@ .....@ .....@ .....@ ..g...M.)f.P..
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="platform"

UNKNOWN
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="version"

1.0
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="description"

UNKNOWN
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="md5_digest"

2d4a3272f6fe89e5ada252c4eeea4d48
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name=":action"

file_upload
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="name"

hello-strongbox-pip
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="license"

Apache 2.0
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="pyversion"


----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="summary"

Hello, Strongbox [pip]!
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254
Content-Disposition: form-data; name="author_email"

carlspring@gmail.com
----------------GHSKFJDLGDS7543FJKLFHRE75642756743254--

02:17:32.247761 IP6 ::1.48080 > ::1.57278: Flags [.], ack 3963, win 1365, options [nop,nop,TS val 1253082674 ecr 1253082674], length 0
`.A.. .@....................................... Qa.....U.(.....
J..2J..2
02:17:33.000526 IP6 ::1.48080 > ::1.57278: Flags [P.], seq 1:290, ack 3963, win 1365, options [nop,nop,TS val 1253083427 ecr 1253082674], length 289
`.A..A.@....................................... Qa.....U.I.....
J..#J..2HTTP/1.1 405 Method Not Allowed
Connection: close
Date: Mon, 08 Apr 2019 01:17:32 GMT
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Content-Type: application/json
Allow: GET

{"error":"Request method 'POST' not supported"}
02:17:33.000543 IP6 ::1.57278 > ::1.48080: Flags [.], ack 290, win 350, options [nop,nop,TS val 1253083427 ecr 1253083427], length 0
`..u. .@....................................Qa.....A...^.(.....
J..#J..#
02:17:33.001264 IP6 ::1.57278 > ::1.48080: Flags [F.], seq 3963, ack 290, win 350, options [nop,nop,TS val 1253083428 ecr 1253083427], length 0
`..u. .@....................................Qa.....A...^.(.....
J..$J..#
02:17:33.006336 IP6 ::1.48080 > ::1.57278: Flags [F.], seq 290, ack 3964, win 1365, options [nop,nop,TS val 1253083433 ecr 1253083428], length 0
`.A.. .@.......................................AQa.....U.(.....
J..)J..$
02:17:33.006351 IP6 ::1.57278 > ::1.48080: Flags [.], ack 291, win 350, options [nop,nop,TS val 1253083433 ecr 1253083433], length 0
`..u. .@....................................Qa.....B...^.(.....
J..)J..)
10 packets captured
20 packets received by filter
0 packets dropped by kernel
```

**Comment by Firstmol** [comment]
### **1. UPLOAD ARTIFACTS**

_Command_: `twine upload --repository-url http://localhost:80 dist/dokr-0.1-py3-none-any.whl`

**Request:**
_Method_:POST
_URI_: /
_Content-Type_: multipart/form-data
_Accept-Encoding:_ gzip, deflate
_Authorization_: Basic knRzdjk1QadtYWlsLmNvbto4MTI4MTk5cQ==

**Response:**
_Status code_: 200
_Content-Length_: 0
_Content-Type_: text/html; charset=UTF-8

### **2. SEARCH ARTIFACTS**

_Command_: `pip3 search --index http://localhost:8080 do`

**Request:**
_Method_: POST
_URI_: /RPC2
_Content-Type_: Content-Type: text/xml
_Accept-Encoding:_ gzip, deflate
_Body_:
```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
   <methodName>search</methodName>
   <params>
      <param>
         <value>
            <struct>
               <member>
                  <name>name</name>
                  <value>
                     <array>
                        <data>
                           <value>
                              <string>do</string>
                           </value>
                        </data>
                     </array>
                  </value>
               </member>
               <member>
                  <name>summary</name>
                  <value>
                     <array>
                        <data>
                           <value>
                              <string>do</string>
                           </value>
                        </data>
                     </array>
                  </value>
               </member>
            </struct>
         </value>
      </param>
      <param>
         <value>
            <string>or</string>
         </value>
      </param>
   </params>
</methodCall>
```
 
**Response:**
_Status code_: 200
_Content-Length_: 497
_Content-Type_: text/html; charset=UTF-8
_Body_: 
```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
   <methodName>search</methodName>
   <params>
      <param>
         <value>
            <array>
               <data>
                  <value>
                     <struct>
                        <member>
                           <name>_pypi_ordering</name>
                           <value>
                              <int>0</int>
                           </value>
                        </member>
                        <member>
                           <name>version</name>
                           <value>
                              <string>0.1</string>
                           </value>
                        </member>
                        <member>
                           <name>name</name>
                           <value>
                              <string>dokr</string>
                           </value>
                        </member>
                        <member>
                           <name>summary</name>
                           <value>
                              <string>0.1</string>
                           </value>
                        </member>
                     </struct>
                  </value>
               </data>
            </array>
         </value>
      </param>
   </params>
</methodCall>
```
### **3. INSTALL ARTIFACTS**
_Command_: `pip3 install dokr`

There are 3 requests:

a) Dependcy request with redirect(first request from pip3)

**Request:**
_Method_: GET
_URI_: /dokr/
_Accept-Encoding:_ gzip, deflate
_Accept_: text/html

**Response:**
_Status code_: 303
_Location_: http://localhost/simple/dokr/


a) Dependcy ref request

**Request:**
_Method_: GET
_URI_:simple/dokr/
_Accept-Encoding:_ gzip, deflate
_Accept_: text/html

**Response:**
_Status code_: 200
_Content-Type_: text/html; charset=UTF-8
_Body_:  

```
    <html>
        <head>
            <title>Links for dokr</title>
        </head>
        <body>
            <h1>Links for dokr</h1>
                 <a href="/packages/dokr-0.1-py3-none-any.whl#md5=740858363b87414908204473d0eab277">dokr-0.1-py3-none-any.whl</a><br>
        </body>
    </html>
 ```
P/S: Above we return reffs on ALL versions dokr package

b) File request

**Request:**
_Method_: GET
_URI_:  /packages/dokr-0.1-py3-none-any.whl
_Accept-Encoding_: identity
_Accept_: */*

**Response:**
_Status code_: 200
_Content-Type_: application/octet-stream
_Accept-Ranges_: bytes
_Body_:  (dep file)

**Comment by Firstmol** [comment]
### **1. UPLOAD ARTIFACTS**

_Command_: `twine upload --repository-url http://localhost:80 dist/dokr-0.1-py3-none-any.whl`

**Request:**
_Method_:POST
_URI_: /
_Content-Type_: multipart/form-data
_Accept-Encoding:_ gzip, deflate
_Authorization_: Basic knRzdjk1QadtYWlsLmNvbto4MTI4MTk5cQ==

**Response:**
_Status code_: 200
_Content-Length_: 0
_Content-Type_: text/html; charset=UTF-8

### **2. SEARCH ARTIFACTS**

_Command_: `pip3 search --index http://localhost:8080 do`

**Request:**
_Method_: POST
_URI_: /RPC2
_Content-Type_: Content-Type: text/xml
_Accept-Encoding:_ gzip, deflate
_Body_:
```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
   <methodName>search</methodName>
   <params>
      <param>
         <value>
            <struct>
               <member>
                  <name>name</name>
                  <value>
                     <array>
                        <data>
                           <value>
                              <string>do</string>
                           </value>
                        </data>
                     </array>
                  </value>
               </member>
               <member>
                  <name>summary</name>
                  <value>
                     <array>
                        <data>
                           <value>
                              <string>do</string>
                           </value>
                        </data>
                     </array>
                  </value>
               </member>
            </struct>
         </value>
      </param>
      <param>
         <value>
            <string>or</string>
         </value>
      </param>
   </params>
</methodCall>
```
 
**Response:**
_Status code_: 200
_Content-Length_: 497
_Content-Type_: text/html; charset=UTF-8
_Body_: 
```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
   <methodName>search</methodName>
   <params>
      <param>
         <value>
            <array>
               <data>
                  <value>
                     <struct>
                        <member>
                           <name>_pypi_ordering</name>
                           <value>
                              <int>0</int>
                           </value>
                        </member>
                        <member>
                           <name>version</name>
                           <value>
                              <string>0.1</string>
                           </value>
                        </member>
                        <member>
                           <name>name</name>
                           <value>
                              <string>dokr</string>
                           </value>
                        </member>
                        <member>
                           <name>summary</name>
                           <value>
                              <string>0.1</string>
                           </value>
                        </member>
                     </struct>
                  </value>
               </data>
            </array>
         </value>
      </param>
   </params>
</methodCall>
```
### **3. INSTALL ARTIFACTS**
_Command_: `pip3 install dokr`

There are 3 requests:

a) Dependcy request with redirect(first request from pip3)

**Request:**
_Method_: GET
_URI_: /dokr/
_Accept-Encoding:_ gzip, deflate
_Accept_: text/html

**Response:**
_Status code_: 303
_Location_: http://localhost/simple/dokr/


a) Dependcy ref request

**Request:**
_Method_: GET
_URI_:simple/dokr/
_Accept-Encoding:_ gzip, deflate
_Accept_: text/html

**Response:**
_Status code_: 200
_Content-Type_: text/html; charset=UTF-8
_Body_:  

```
    <html>
        <head>
            <title>Links for dokr</title>
        </head>
        <body>
            <h1>Links for dokr</h1>
                 <a href="/packages/dokr-0.1-py3-none-any.whl#md5=740858363b87414908204473d0eab277">dokr-0.1-py3-none-any.whl</a><br>
        </body>
    </html>
 ```
P/S: Above we return reffs on ALL versions dokr package

b) File request

**Request:**
_Method_: GET
_URI_:  /packages/dokr-0.1-py3-none-any.whl
_Accept-Encoding_: identity
_Accept_: */*

**Response:**
_Status code_: 200
_Content-Type_: application/octet-stream
_Accept-Ranges_: bytes
_Body_:  (dep file)

### **4. DOWNLOAD ARTIFACTS**
_Command_: `pip3 download dokr`

Works same as install.

**Comment by carlspring** [comment]
Thanks for providing all this really useful information, @Firstmol!

Please, feel free to dig into my `issue-811` branch and to continue my initial work on this.
