### ISSUE TITLE
Implement a hello-strongbox-pypi example

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#812]
# Task Description

We need a simple "Hello, World!"-styled application that illustrates:
* [x] The creation of a PyPi package
* [x] Deploying PyPi packages to Strongbox
* [ ] Resolving PyPi packages
* [ ] A detailed step-by-step `README.md` illustrating how to configure things, as well as how to execute the steps above, along with actual successful output

The code should be located under the [strongbox-examples](https://github.com/strongbox/strongbox-examples) project and it should be called `strongbox-pypi`.

It would probably be helpful to have a look at how things have been done in the other examples under the [strongbox-examples](https://github.com/strongbox/strongbox-examples) project.

This is a sub-task of #807. It should be relatively straight-forward to implement this and you should get acquainted with the master task, before proceeding. This task depends on #811, or should be implemented in parallel with it.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by Firstmol** [comment]
What do you mean by `Resolving PyPi packages`?

**Comment by carlspring** [comment]
(Apologies for the late reply, I seem to have missed this message). I mean downloading the package using `pip`.
