### ISSUE TITLE
Implement an RPMArtifactGenerator

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#846]
# Task Description

We need to implement a simple RPM package generator to be used during testing.

The code should be located in a class called `RpmArtifactGenerator` under `strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-yum-layout-provider/src/test/java/org/carlspring/strongbox/artifact/generator`.

The generator must produce packages that are valid, along with all the required metadata and resource files.

A test case covering the functionality will be required.

For a reference of existing generators for other providers have a look at:
* `MavenArtifactGenerator`
* `NpmArtifactGenerator`
* `NugetArtifactGenerator`

# Tasks

The following tasks will need to be carried out:
* [x] Implement an `RpmArtifactGenerator`.
* [x] Implement an `RpmTestArtifact` annotation to be used for testing (see `TestArtifact` and all the available derived annotations).
* [x] Implement an `RpmRepository` annotation to be used for testing (see `TestRepository` and all the available derived annotations).

# Task Relationships

This task:
* Is a sub-task of: #845

# See also:
* [Redline Java RPM library](https://github.com/craigwblake/redline)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
Implemented in #1600 .
