### ISSUE TITLE
Implement a YumLayoutProvider

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#848]
We need to implement a layout provider which handles the logic of managing Yum (RPM) artifacts. Most of this functionality should be implemented as part of the layout provider.

The code should be located in a class called `YumLayoutProvider` under `strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-yum-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout`.

As a reference you can have a look at:
* [Maven2LayoutProvider](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/Maven2LayoutProvider.java)
* [NpmLayoutProvider](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-npm-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/NpmLayoutProvider.java)
* [NugetLayoutProvider](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/providers/layout/NugetLayoutProvider.java)

This is a sub-task of #845 and you should get acquainted with the master task, before proceeding.

# Task List

The following classes will need to be implemented:
* [x] `org.carlspring.strongbox.providers.layout.RpmFileSystem`
* [x] `org.carlspring.strongbox.providers.layout.RpmFileSystemProvider`
* [x] `org.carlspring.strongbox.providers.layout.RpmLayoutProvider`
  * ~~[ ] Figure out how to implement `isArtifactMetadata(RepositoryPath path)`~~
  * ~~[ ] Figure out how to implement `isMetadata(RepositoryPath path)`~~
* [x] `org.carlspring.strongbox.repository.RpmRepositoryFeatures`
* [x] `org.carlspring.strongbox.repository.RpmRepositoryManagementStrategy`
* [x] `org.carlspring.strongbox.storage.repository.RpmRepositoryFactory`

The implementations for the analoguous classes in the `strongbox-storage-npm-layout-provider` could serve as an example and could be copied with minor modifications.

# See Also:
* [How To Implement Your Own Repository Format](https://strongbox.github.io/developer-guide/layout-providers/how-to-implement-your-own-repository-format.html)

**Comment by carlspring** [comment]
Implemented in #1600 .
