### ISSUE TITLE
Implement PHP Composer layout support

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#872]
# Task Description

This is the master task for the implementation of the PHP Composer layout support support.

The code should be located in a new module called `strongbox-storage-composer-layout-provider` under [strongbox-storage/strongbox-storage-layout-providers](https://github.com/strongbox/strongbox/tree/master/strongbox-storage/strongbox-storage-layout-providers).

The work on these tasks will have to be based against the `composer-layout-provider` feature branch, until things are sufficiently stable and usable to consider them getting merged to the `master`.

Please, gather all the requirements and useful links here.

# Getting Started

To get started, check out the "Developer Guide" section of our [wiki](https://strongbox.github.io/developer-guide/getting-started.html) and,
more specifically:
* [Getting Started](https://strongbox.github.io/developer-guide/getting-started.html)
* [Building the code](https://strongbox.github.io/developer-guide/building-the-code.html)
* [Coding Convention](https://strongbox.github.io/developer-guide/coding-convention.html)

# Sub-tasks

The following is roughly the order in which the tasks will need to be implemented:
- [ ] [Implement a ComposerArtifactGenerator](https://github.com/strongbox/strongbox/issues/873)
- [ ] [Implement a ComposerArtifactCoordinates](https://github.com/strongbox/strongbox/issues/874)
- [ ] [Implement a ComposerLayoutProvider](https://github.com/strongbox/strongbox/issues/875)
- [ ] [Implement a ComposerArtifactController](https://github.com/strongbox/strongbox/issues/876)
- [ ] [Implement a hello-strongbox-composer example](https://github.com/strongbox/strongbox/issues/877)
- [ ] [Implement Composer hosted repositories](https://github.com/strongbox/strongbox/issues/878)
- [ ] [Implement Composer proxy repositories](https://github.com/strongbox/strongbox/issues/879)
- [ ] [Implement Composer group repositories](https://github.com/strongbox/strongbox/issues/880)
- [ ] [Implement Composer integration tests in the strongbox-web-integration-tests module](https://github.com/strongbox/strongbox/issues/881)

# Follow-up tasks

* Update the documentation, as and when necessary.
* Create a page in the wiki detailing the Composer layout provider

# See Also

* [Layout Providers](https://strongbox.github.io/knowledge-base/layout-providers.html)
* [How To Implement Your Own Repository Format](https://strongbox.github.io/developer-guide/layout-providers/how-to-implement-your-own-repository-format.html)

# See Also

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86
