### ISSUE TITLE
Convert the strongbox configuration files from XML to YAML format

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#965]
# Task Description

We would like to convert our configuration files from XML into YAML.

* [x] Re-work the `XmlFileManager` into `YamlFileManager`, so that we could start converting the XML files into YAML. The property names will have to be changed and they'll have to be camel case instead of using hyphens.
* `etc/conf/strongbox.xml`:
  * [x] Convert to `yaml`
  * [ ] Add a page called "The strongbox.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* `etc/conf/strongbox-authorization.xml`:
  * [x] Convert to `yaml`
  * [ ] Add a page called "The strongbox-authorization.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* `etc/conf/strongbox-cron-tasks.xml`:
  * [x] Convert to `yaml`
  * [ ] Add a page called "The strongbox-cron-tasks.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* `etc/conf/strongbox-security-users.xml`:
  * [x] Convert to `yaml`
  * [ ] Add a page called "The strongbox-security-users.yaml file" to the "User Guide" in the [strongbox-docs](https://github.com/strongbox/strongbox-docs).
* [ ] Update the [Application Properties](https://strongbox.github.io/user-guide/application-properties.html) page.
* [ ] Update the [Routing Rules](https://strongbox.github.io/user-guide/artifact-routing-rules.html) page.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by kdpapado** [comment]
Hi @sbespalov . I' d like to try this..

**Comment by ptirador** [comment]
Hi @kdpapado, are you still working on this? If not, I'd like to take it.

**Comment by carlspring** [comment]
Thanks, @ptirador !

Please, feel free to proceed! :)

**Comment by ptirador** [comment]
Hi @sbespalov @steve-todorov, I have a question, what do I do about any controller methods related with this? For example:

```
    @ApiOperation(value = "Retrieves the strongbox-authorization.xml configuration file.")
    @ApiResponses(value = { @ApiResponse(code = 200, message = SUCCESSFUL_GET_CONFIG),
                            @ApiResponse(code = 500, message = FAILED_GET_CONFIG) })
    @GetMapping(value = "/xml",
                produces = { MediaType.APPLICATION_XML_VALUE,
                             MediaType.APPLICATION_JSON_VALUE })
    public ResponseEntity getAuthorizationConfig(@RequestHeader(HttpHeaders.ACCEPT) String acceptHeader)
    {
        return processConfig(null, acceptHeader);
    }
```

Do I need to convert it to this?

```
    @ApiOperation(value = "Retrieves the strongbox-authorization.yaml configuration file.")
    @ApiResponses(value = { @ApiResponse(code = 200, message = SUCCESSFUL_GET_CONFIG),
                            @ApiResponse(code = 500, message = FAILED_GET_CONFIG) })
    @GetMapping(value = "/yaml",
                produces = { "application/x-yaml",
                             MediaType.APPLICATION_JSON_VALUE })
    public ResponseEntity getAuthorizationConfig(@RequestHeader(HttpHeaders.ACCEPT) String acceptHeader)
    {
        return processConfig(null, acceptHeader);
    }
```

**Comment by sbespalov** [comment]
I think it should be just GET without `/xml` or `/yaml`. Content
negotiation should work out of the box in Spring depending on `Accept`
header.

сб, 2 февр. 2019 г. в 18:59, Pablo Tirado <notifications@github.com>:

**Comment by steve-todorov** [comment]
I agree with @sbespalov :+1: :)

**Comment by carlspring** [comment]
I also agree with @sbespalov and @steve-todorov.

**Comment by carlspring** [comment]
@ptirador / @fuss86 ,

Could you guys please also look into updating our documentation?
Thanks! :)

**Comment by fuss86** [comment]
> Could you guys please also look into updating our documentation?
> Thanks! :)

https://github.com/strongbox/strongbox-docs/pull/10

@ptirador feel free to update it.

@carlspring this part of doc depends on:
* pre-defined set of roles and privileges:
  * we need to list and explain them in the docs (it's missing now, is that correct ?)
* security-users (I think @sbespalov knows best how it currently works, honestly)
* cron-tasks (this will probably be reworked somehow, see SB-540)

**Comment by carlspring** [comment]
Just saw your comments, @fuss86! strongbox/strongbox-docs#10 looks like it's shaping up quite well, thanks!
